// web/ui/dashboard-react/src/app/projects_/$projectId/endpoints/index.tsx
import { createFileRoute, Link } from '@tanstack/react-router';
import { z } from 'zod';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import React, { useEffect, useState } from 'react';
import {
	Copy,
	MoreVertical,
	PlayCircle,
	PauseCircle,
	Trash2,
	Send,
} from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogClose,
	DialogDescription,
} from '@/components/ui/dialog';
import { Form, FormField, FormItem } from '@/components/ui/form';
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from '@/components/ui/table';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select';
import { DashboardLayout } from '@/components/dashboard';

import { groupItemsByDate } from '@/lib/pipes';
import { useLicenseStore, useProjectStore } from '@/store';
import { endpointsService } from '@/services/endpoints.service';

import type { ENDPOINT } from '@/models/endpoint.model';
import type { Pagination } from '@/models/global.model';

import viewEventsImg from '../../../../../assets/svg/view-events-icon.svg';
import searchIcon from '../../../../../assets/svg/search-icon.svg';
import { ConvoyLoader } from '@/components/convoy-loader';

export const Route = createFileRoute('/projects_/$projectId/endpoints/')({
	component: ListEndpointsPage,
});

const ExpireSecretFormSchema = z.object({
	expiration: z
		.enum([
			'0',
			'3600',
			'7200',
			'14400',
			'28800',
			'43200',
			'57600',
			'72000',
			'86400',
		])
		.pipe(z.coerce.number())
		.refine(v => v !== 0),
});

function EndpointsPageContent() {
	const { projectId } = Route.useParams();
	const { project } = useProjectStore();
	const [isLoadingEndpoints, setIsLoadingEndpoints] = useState(false);
	const [displayedEndpoints, setDisplayedEndpoints] = useState<ENDPOINT[]>([]);
	const [pagination, setPagination] = useState<Pagination | null>(null);
	const [showExpireSecretSelectOptions, setShowExpireSecretSelectOptions] =
		useState(false);
	const [selectedEndpoint, setSelectedEndpoint] = useState<ENDPOINT | null>(
		null,
	);
	const [isSendingTestEvent, setIsSendingTestEvent] = useState(false);
	const [searchString, setSearchString] = useState('');
	const [isTogglingEndpoint, setIsTogglingEndpoint] = useState(false);
	const [isDeletingEndpoint, setIsDeletingEndpoint] = useState(false);
	const [showSecretModal, setShowSecretModal] = useState(false);
	const [showDeleteModal, setShowDeleteModal] = useState(false);
	const { licenses } = useLicenseStore();

	const expireSecretForm = useForm<z.infer<typeof ExpireSecretFormSchema>>({
		resolver: zodResolver(ExpireSecretFormSchema),
		defaultValues: {
			expiration: 0,
		},
		mode: 'onTouched',
	});

	useEffect(() => {
		getEndpoints();
	}, []);

	// Function to get endpoints from API
	const getEndpoints = async (params: Record<string, string> = {}) => {
		setIsLoadingEndpoints(true);
		try {
			const response = await endpointsService.getEndpoints(params);
			// The response contains a flat array of ENDPOINT objects

			setDisplayedEndpoints(/* response.data?.content ||  */ []);
			setPagination(response.data?.pagination);
		} catch (error) {
			console.error('Error fetching endpoints:', error);
		} finally {
			setIsLoadingEndpoints(false);
		}
	};

	// Function to handle search form submission
	const handleSearch = (e: React.FormEvent) => {
		e.preventDefault();
		getEndpoints({ q: searchString });
	};

	// Function to handle pagination
	const handlePagination = (params: Record<string, string>) => {
		getEndpoints({
			...params,
			...(searchString ? { search: searchString } : {}),
		});
	};

	// Function to toggle endpoint status (pause/unpause)
	const toggleEndpoint = async (endpointId: string) => {
		setIsTogglingEndpoint(true);
		try {
			await endpointsService.toggleEndpoint(endpointId);
			await getEndpoints();
		} catch (error) {
			console.error('Error toggling endpoint:', error);
		} finally {
			setIsTogglingEndpoint(false);
		}
	};

	// Function to delete an endpoint
	const deleteEndpoint = async () => {
		if (!selectedEndpoint) return;

		setIsDeletingEndpoint(true);
		try {
			await endpointsService.deleteEndpoint(selectedEndpoint.uid);
			setShowDeleteModal(false);
			await getEndpoints();
		} catch (error) {
			console.error('Error deleting endpoint:', error);
		} finally {
			setIsDeletingEndpoint(false);
		}
	};

	async function sendTestEvent() {
		const testEvent = {
			data: {
				data: 'test event from Convoy',
				convoy: 'https://getconvoy.io',
				amount: 1000,
			},
			endpoint_id: selectedEndpoint?.uid,
			event_type: 'test.convoy',
		};

		setIsSendingTestEvent(true);
		try {
			const response = await endpointsService.sendEvent({ body: testEvent });
			// TODO: Add toast notification
		} catch (error) {
			console.error(error);
		} finally {
			setIsSendingTestEvent(false);
		}
	}

	// Function to copy text to clipboard
	const copyToClipboard = (text: string) => {
		navigator.clipboard.writeText(text);
		// TODO: Add toast notification
	};

	// Get appropriate status color for badges
	const getStatusColor = (status: 'active' | 'paused' | 'inactive') => {
		switch (status.toLowerCase()) {
			case 'active':
				return 'bg-new.success-50 text-new.success-700';
			case 'paused':
				return 'bg-neutral-a3 text-neutral-11';
			default:
				return 'border border-neutral-10';
		}
	};

	// Loading state
	if (isLoadingEndpoints) {
		return <ConvoyLoader isTransparent={true} isVisible={true} />;
	}

	// Empty state
	if (!searchString && displayedEndpoints.length === 0) {
		return (
			<div className="py-[80px] min-h-[500px] flex flex-col items-center justify-center">
				<img
					src="/assets/img/events-log-empty-state.png"
					alt="Empty state"
					className="mb-6 h-40"
				/>
				<h2 className="text-[18px] font-bold text-neutral-12 mb-2">
					{searchString
						? `${searchString} endpoint does not exist`
						: 'You currently do not have any endpoints'}
				</h2>
				<p className="text-neutral-11 text-sm mb-9">
					Endpoints will be listed here when available
				</p>
				<Button
					asChild
					size="sm"
					className="mt-9 mb-9 hover:bg-new.primary-400 bg-new.primary-400 text-white-100 hover:text-white-100 "
				>
					<Link to="/projects/$projectId/endpoints/new" params={{ projectId }}>
						<svg
							width="22"
							height="22"
							className="scale-100"
							fill="#ffffff"
						>
							<use xlinkHref="#plus-icon"></use>
						</svg>
						Create Endpoint
					</Link>
				</Button>
			</div>
		);
	}

	// Main content with endpoints table
	return (
		<div className="mx-auto px-4 py-6">
			<div className="flex justify-between items-end mb-[24px]">
				<div className="flex items-center">
					<h1 className="text-[18px] font-bold text-neutral-12 mr-[10px]">
						Endpoints
					</h1>
				</div>
			</div>

			<div className="flex items-center justify-between mb-[24px] mt-[18px]">
				<div className="flex items-center">
					<form
						className="border border-primary-400 h-[36px] px-[14px] py-0 max-w-[350px] w-full rounded-[10px] flex items-center bg-white-100"
						onSubmit={handleSearch}
					>
						<img src={searchIcon} alt="search icon" className="mr-[10px]" />
						<input
							type="search"
							placeholder="Search endpoints"
							className="w-full text-neutral-11 text-xs outline-none"
							value={searchString}
							onChange={e => setSearchString(e.target.value)}
						/>
						{searchString && (
							<Button
								type="submit"
								variant="ghost"
								size="sm"
								className="transition-all duration-200 hover:bg-transparent"
							>
								<img src={searchIcon} alt="enter icon" className="w-[16px]" />
							</Button>
						)}
					</form>
				</div>

				{displayedEndpoints.length > 0 && (
					<Button
						size="sm"
						asChild
						variant="ghost"
						className="hover:bg-new.primary-400 text-white-100 text-xs hover:text-white-100 bg-new.primary-400 h-[36px]"
					>
						<Link
							to="/projects/$projectId/endpoints/new"
							params={{ projectId }}
						>
							<svg width="22" height="22" fill="#ffffff">
								<use xlinkHref="#plus-icon"></use>
							</svg>
							Endpoint
						</Link>
					</Button>
				)}
			</div>

			<div className="convoy-card bg-white rounded-lg border shadow-sm">
				<div
					className="min-h-[70vh] overflow-y-auto overflow-x-auto w-full min-w-[485px]"
					id="event-deliveries-table-container"
				>
					{/* TODO: make content of table scrollable without scrolling the page and the header*/}
					<Table>
						<TableHeader className="border-b border-b-new.primary-25">
							<TableRow>
								<TableHead className="pl-[20px] uppercase text-xs text-new.black">
									Name
								</TableHead>
								<TableHead className="uppercase text-xs text-new.black w-[100px]">
									Status
								</TableHead>
								<TableHead className="uppercase text-xs text-new.black">
									Url
								</TableHead>
								<TableHead className="uppercase text-xs text-new.black">
									ID
								</TableHead>
								{licenses.includes('CIRCUIT_BREAKING') ? (
									<TableHead className="uppercase text-xs text-new.black text-nowrap">
										Failure Rate
									</TableHead>
								) : null}
								<TableHead className="uppercase text-xs text-new.black"></TableHead>
								<TableHead className="uppercase text-xs text-new.black"></TableHead>
							</TableRow>
						</TableHeader>
						<TableBody>
							{Array.from(groupItemsByDate(displayedEndpoints)).map(
								([dateKey, endpoints]) => {
									return [
										<TableRow
											key={dateKey}
											className="hover:bg-transparent border-new.primary-25 border-t border-b-0"
										>
											<TableCell className="font-normal text-neutral-10 text-xs bg-neutral-a3 py-2">
												{dateKey}
											</TableCell>
											<TableCell className="bg-neutral-a3 py-2"></TableCell>
											<TableCell className="bg-neutral-a3 py-2"></TableCell>
											<TableCell className="bg-neutral-a3 py-2"></TableCell>
											<TableCell className="bg-neutral-a3 py-2"></TableCell>
											{licenses.includes('CIRCUIT_BREAKING') ? (
												<TableCell className="bg-neutral-a3 py-2"></TableCell>
											) : null}
											<TableCell className="bg-neutral-a3 py-2"></TableCell>
										</TableRow>,
									].concat(
										endpoints.map(ep => (
											<TableRow
												key={ep.uid}
												className="border-b border-b-new.primary-25 duration-300 hover:bg-new.primary-25 transition-all py-3"
											>
												<TableCell className="w-[300px]">
													<div className="truncate max-w-[290px] pl-[16px] font-normal text-neutral-12 text-xs">
														{ep.name || ep.title}
													</div>
												</TableCell>
												<TableCell className="w-[100px]">
													{ep.status && (
														<span
															className={`${getStatusColor(ep.status)} text-xs p-2 rounded-[22px]`}
														>
															{ep.status}
														</span>
													)}
												</TableCell>
												<TableCell className="relative">
													<div className="flex items-center gap-[10px] bg-neutral-3 px-2 rounded-[22px] w-[200px]">
														<span className="w-[200px] truncate font-normal text-neutral-12 text-xs whitespace-nowrap">
															{ep.url || ep.target_url}
														</span>
														<Button
															className="hover:bg-transparent p-0"
															variant="ghost"
															size="sm"
															onClick={e => {
																e.stopPropagation();
																copyToClipboard(ep.url || ep.target_url);
															}}
														>
															<Copy className="stroke-neutral-10" />
														</Button>
													</div>
												</TableCell>
												<TableCell className="relative">
													<div className="flex items-center gap-[10px] bg-neutral-3 px-2 rounded-[22px] w-[150px]">
														<span className="w-[150px] truncate font-normal text-neutral-12 text-xs whitespace-nowrap">
															{ep.uid}
														</span>
														<Button
															className="hover:bg-transparent p-0"
															variant="ghost"
															size="sm"
															onClick={e => {
																e.stopPropagation();
																copyToClipboard(ep.uid);
															}}
														>
															<Copy className="stroke-neutral-10" />
														</Button>
													</div>
												</TableCell>
												{licenses.includes('CIRCUIT_BREAKING') ? (
													<TableCell className="font-normal text-neutral-12 text-xs text-center">
														{ep.failure_rate}%
													</TableCell>
												) : null}
												<TableCell></TableCell>
												<TableCell>
													<div className="w-full flex items-center justify-end">
														<Button
															asChild
															variant="ghost"
															size="sm"
															className="hover:bg-new.primary-25 bg-new.primary-25 hover:text-new.primary-400 text-new.primary-400 text-xs py-1 px-4 rounded-md"
														>
															<Link
																// @ts-expect-error TODO: I'll create this route soon
																// TODO: I'll create this route soon
																to="/projects/$projectId/events"
																// @ts-expect-error TODO: I'll create this route soon
																// TODO: I'll create this route soon
																params={{ projectId }}
																// @ts-expect-error TODO: I'll create this route soon
																// TODO: I'll create this route soon
																search={prev => ({
																	...prev,
																	endpointId: ep.uid,
																})}
															>
																<img
																	src={viewEventsImg}
																	alt="View Events"
																	className="w-[14px] mr-[10px]"
																/>
																View Events
															</Link>
														</Button>

														<DropdownMenu>
															<DropdownMenuTrigger
																asChild
																onClick={e => e.stopPropagation()}
															>
																<Button
																	variant="ghost"
																	size="sm"
																	className="ml-[40px] pr-[24px] p-1 focus-visible:ring-0 focus-visible:ring-offset-0 hover:bg-transparent"
																>
																	<span>
																		<MoreVertical className="stroke-new.primary-200" />
																	</span>
																</Button>
															</DropdownMenuTrigger>
															<DropdownMenuContent className="w-48 p-[10px]">
																<DropdownMenuItem
																	className="mb-[4px] rounded-[8px] py-[4px] px-[6px] hover:bg-new.primary-25 duration-300 transition-all w-full justify-start cursor-pointer"
																	onClick={e => {
																		e.stopPropagation();
																		setSelectedEndpoint(ep);
																		setShowSecretModal(true);
																	}}
																>
																	<svg
																		width="24"
																		height="24"
																		className="mr-8px fill-primary-100 stroke-neutral-10"
																	>
																		<use xlinkHref="#shield-icon"></use>
																	</svg>
																	<span className="text-xs fill-neutral-10 text-neutral-10 cursor-pointer">
																		View Secret
																	</span>
																</DropdownMenuItem>

																<DropdownMenuItem
																	className="mb-[4px] rounded-[8px] py-[4px] px-[6px] hover:bg-new.primary-25 duration-300 transition-all w-full justify-start cursor-pointer"
																	asChild
																>
																	<Link
																		// @ts-expect-error I'll create this route soon
																		to="/projects/$projectId/subscriptions"
																		// @ts-expect-error I'll create this route soon
																		params={{ projectId }}
																		// @ts-expect-error I'll create this route soon
																		search={prev => ({
																			...prev,
																			endpointId: ep.uid,
																		})}
																	>
																		<svg
																			width="24"
																			height="24"
																			className="mr-8px fill-primary-100 stroke-neutral-10"
																		>
																			<use xlinkHref="#subscriptions-icon"></use>
																		</svg>
																		<span className="text-xs text-neutral-10 cursor-pointer">
																			View Subscriptions
																		</span>
																	</Link>
																</DropdownMenuItem>

																<DropdownMenuItem
																	className="mb-[4px] rounded-[8px] py-[4px] px-[6px] hover:bg-new.primary-25 duration-300 transition-all w-full justify-start cursor-pointer"
																	onClick={e => {
																		e.stopPropagation();
																		toggleEndpoint(ep.uid);
																	}}
																	disabled={isTogglingEndpoint}
																>
																	{ep.status === 'paused' ? (
																		<PlayCircle className="h-4 w-4 stroke-neutral-10" />
																	) : (
																		<PauseCircle className="h-4 w-4 stroke-neutral-10" />
																	)}
																	<span className="text-xs text-neutral-10 cursor-pointer">
																		{ep.status === 'paused'
																			? 'Unpause'
																			: 'Pause'}
																	</span>
																</DropdownMenuItem>

																{ep.status === 'inactive' && (
																	<DropdownMenuItem
																		className="mb-[4px] rounded-[8px] py-[4px] px-[6px] hover:bg-new.primary-25 duration-300 transition-all w-full justify-start cursor-pointer"
																		onClick={async e => {
																			e.stopPropagation();
																			setIsTogglingEndpoint(true);
																			try {
																				await endpointsService.activateEndpoint(
																					ep.uid,
																				);
																				await getEndpoints();
																			} catch (error) {
																				console.error(
																					'Error activating endpoint:',
																					error,
																				);
																			} finally {
																				setIsTogglingEndpoint(false);
																			}
																		}}
																		disabled={isTogglingEndpoint}
																	>
																		<PlayCircle className="mr-[8px] h-4 w-4 stroke-neutral-10" />
																		<span className="text-xs text-neutral-10 cursor-pointer">
																			Activate Endpoint
																		</span>
																	</DropdownMenuItem>
																)}

																<DropdownMenuItem
																	className="mb-[4px] rounded-[8px] py-[4px] px-[6px] hover:bg-new.primary-25 duration-300 transition-all w-full justify-start cursor-pointer"
																	asChild
																>
																	<Link
																		// @ts-expect-error I'll create this route soon
																		to="/projects/$projectId/endpoints/$endpointId"
																		params={{
																			// @ts-expect-error I'll create this route soon
																			projectId,
																			endpointId: ep.uid,
																		}}
																	>
																		<svg
																			width="24"
																			height="24"
																			className="mr-8px  stroke-[0.25px] stroke-neutral-10 fill-neutral-10"
																		>
																			<use xlinkHref="#edit-icon"></use>
																		</svg>
																		<span className="text-xs text-neutral-10 cursor-pointer">
																			Edit
																		</span>
																	</Link>
																</DropdownMenuItem>

																<DropdownMenuItem
																	className="mb-[4px] rounded-[8px] py-[4px] px-[6px] hover:bg-new.primary-25 duration-300 transition-all w-full justify-start cursor-pointer"
																	onClick={e => {
																		e.stopPropagation();
																		setSelectedEndpoint(ep);
																		setShowDeleteModal(true);
																	}}
																>
																	<Trash2 className="h-4 w-4 fill-transparent stroke-destructive" />
																	<span className="text-xs text-destructive cursor-pointer">
																		Delete
																	</span>
																</DropdownMenuItem>

																{project?.type === 'outgoing' ? (
																	<DropdownMenuItem
																		disabled={isSendingTestEvent}
																		className="mb-[4px] rounded-[8px] py-[4px] px-[6px] hover:bg-new.primary-25 duration-300 transition-all w-full justify-start cursor-pointer"
																		onClick={e => {
																			e.stopPropagation();
																			sendTestEvent();
																		}}
																	>
																		<Send className="h-4 w-4 stroke-neutral-10" />
																		<span className="text-xs text-neutral-10 cursor-pointer">
																			Send Test Event
																		</span>
																	</DropdownMenuItem>
																) : null}
															</DropdownMenuContent>
														</DropdownMenu>
													</div>
												</TableCell>
											</TableRow>
										)),
									);
								},
							)}
						</TableBody>
					</Table>
				</div>

				{/* Pagination */}
				{/* TODO: Add pagination */}
			</div>

			{/* Secret Modal */}
			<Dialog
				open={showSecretModal}
				onOpenChange={() => {
					setShowSecretModal(!showSecretModal);
					setShowExpireSecretSelectOptions(false);
				}}
			>
				<DialogContent className="rounded-lg">
					<DialogHeader>
						<DialogTitle className="text-start">Endpoint Secret</DialogTitle>
						<DialogDescription className="sr-only">
							Endpoint Secret
						</DialogDescription>
					</DialogHeader>
					<div className="">
						{selectedEndpoint && selectedEndpoint.secrets?.length && (
							<div>
								{selectedEndpoint.secrets?.map((secret, index, arr) => {
									if (index != arr.length - 1) return null;
									return (
										<div key={index} className="mt-4">
											<p className="text-xs text-neutral-10 mb-8px">Secret</p>
											<div className="flex mt-2 border items-center rounded-md">
												<p className="p-3 bg-gray-100  rounded flex-1 text-base text-neutral-10 font-normal truncate overflow-auto">
													{secret.value}
												</p>
												<Button
													variant="ghost"
													size="sm"
													className="hover:bg-transparent ring-0 focus-visible:ring-0 focus-visible:ring-offset-0"
													onClick={() => copyToClipboard(secret.value)}
												>
													<Copy className="h-4 w-4 stroke-neutral-10" />
												</Button>
											</div>
											<Form {...expireSecretForm}>
												<form>
													<div
														className={`${
															showExpireSecretSelectOptions ? 'block' : 'hidden'
														} mt-4`}
													>
														<FormField
															control={expireSecretForm.control}
															name="expiration"
															render={({ field }) => (
																<FormItem>
																	<Select
																		onValueChange={field.onChange}
																		defaultValue={`${field.value}`}
																	>
																		<SelectTrigger className="">
																			<SelectValue placeholder="Select expiry duration" />
																		</SelectTrigger>
																		<SelectContent>
																			{[
																				{ name: '1 hour', uid: 3600 },
																				{ name: '2 hour', uid: 7200 },
																				{ name: '4 hour', uid: 14400 },
																				{ name: '8 hour', uid: 28800 },
																				{ name: '12 hour', uid: 43200 },
																				{ name: '16 hour', uid: 57600 },
																				{ name: '20 hour', uid: 72000 },
																				{ name: '24 hour', uid: 86400 },
																			].map(duration => (
																				<SelectItem
																					className="cursor-pointer
														"
																					key={duration.uid}
																					value={`${duration.uid}`}
																				>
																					{duration.name}
																				</SelectItem>
																			))}
																		</SelectContent>
																	</Select>
																</FormItem>
															)}
														></FormField>
													</div>

													<div className="flex items-center gap-4 justify-end my-4 pt-3">
														<DialogClose asChild>
															<Button
																variant="ghost"
																size="sm"
																className="px-4 py-2 border border-new.primary-400 text-new.primary-400 bg-white-100 hover:bg-white-100 hover:text-new.primary-400"
															>
																Close
															</Button>
														</DialogClose>

														<Button
															disabled={
																!expireSecretForm.formState.isValid &&
																showExpireSecretSelectOptions
															}
															onClick={async e => {
																e.stopPropagation();
																e.preventDefault();
																if (!showExpireSecretSelectOptions) {
																	setShowExpireSecretSelectOptions(true);
																	return;
																}
																const expiration = Number(
																	expireSecretForm.getValues().expiration,
																);
																await endpointsService.expireSecret(
																	selectedEndpoint.uid,
																	{ expiration },
																);
																await getEndpoints();
																setShowSecretModal(false);
															}}
															type="submit"
															variant="ghost"
															size="sm"
															className="px-4 py-2 hover:bg-destructive bg-destructive text-white-100 hover:text-white-100"
														>
															Expire Secret
														</Button>
													</div>
												</form>
											</Form>
										</div>
									);
								})}
							</div>
						)}
					</div>
				</DialogContent>
			</Dialog>

			{/* Delete Modal */}
			<Dialog open={showDeleteModal} onOpenChange={setShowDeleteModal}>
				<DialogContent>
					<DialogHeader>
						<DialogTitle>Delete Endpoint</DialogTitle>
					</DialogHeader>
					<div className="p-4">
						<p>
							Are you sure you want to delete &quot;
							{selectedEndpoint?.name || selectedEndpoint?.title}&quot;?
						</p>
						<p className="text-sm text-gray-600 mt-2">
							This action cannot be undone.
						</p>
						<div className="flex justify-end gap-2 mt-6">
							<Button
								variant="outline"
								onClick={() => setShowDeleteModal(false)}
							>
								Cancel
							</Button>
							<Button
								variant="destructive"
								onClick={deleteEndpoint}
								disabled={isDeletingEndpoint}
							>
								{isDeletingEndpoint ? 'Deleting...' : 'Delete'}
							</Button>
						</div>
					</div>
				</DialogContent>
			</Dialog>
		</div>
	);
}

function ListEndpointsPage() {
	return (
		<DashboardLayout showSidebar={true}>
			<EndpointsPageContent />
		</DashboardLayout>
	);
}

// web/ui/dashboard/src/app/private/pages/project/endpoints/endpoints.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PrivateService } from 'src/app/private/private.service';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { ButtonComponent } from 'src/app/components/button/button.component';
import { ENDPOINT } from 'src/app/models/endpoint.model';
import { CURSOR, PAGINATION } from 'src/app/models/global.model';
import { CardComponent } from 'src/app/components/card/card.component';
import { EmptyStateComponent } from 'src/app/components/empty-state/empty-state.component';
import { DropdownComponent, DropdownOptionDirective } from 'src/app/components/dropdown/dropdown.component';
import { ListItemComponent } from 'src/app/components/list-item/list-item.component';
import { ModalComponent, ModalHeaderComponent } from 'src/app/components/modal/modal.component';
import { CreateEndpointComponent } from 'src/app/private/components/create-endpoint/create-endpoint.component';
import { GeneralService } from 'src/app/services/general/general.service';
import { FormsModule } from '@angular/forms';
import { TableComponent, TableCellComponent, TableRowComponent, TableHeadCellComponent, TableHeadComponent } from 'src/app/components/table/table.component';
import { TagComponent } from 'src/app/components/tag/tag.component';
import { StatusColorModule } from 'src/app/pipes/status-color/status-color.module';
import { TooltipComponent } from 'src/app/components/tooltip/tooltip.component';
import { ProjectService } from '../project.service';
import { PaginationComponent } from 'src/app/private/components/pagination/pagination.component';
import { CopyButtonComponent } from 'src/app/components/copy-button/copy-button.component';
import { PermissionDirective } from 'src/app/private/components/permission/permission.directive';
import { DeleteModalComponent } from 'src/app/private/components/delete-modal/delete-modal.component';
import { EndpointSecretComponent } from './endpoint-secret/endpoint-secret.component';
import { EndpointsService } from './endpoints.service';
import { LoaderModule } from 'src/app/private/components/loader/loader.module';

@Component({
	selector: 'convoy-endpoints',
	standalone: true,
	imports: [
		CommonModule,
		ButtonComponent,
		TableCellComponent,
		TableHeadComponent,
		TableHeadCellComponent,
		TableRowComponent,
		TableCellComponent,
		TableComponent,
		CardComponent,
		EmptyStateComponent,
		DropdownComponent,
		DropdownOptionDirective,
		ListItemComponent,
		ModalComponent,
		ModalHeaderComponent,
		CreateEndpointComponent,
		TagComponent,
		FormsModule,
		RouterModule,
		StatusColorModule,
		TooltipComponent,
		PaginationComponent,
		CopyButtonComponent,
		PermissionDirective,
		EndpointSecretComponent,
		DeleteModalComponent,
		LoaderModule
	],
	templateUrl: './endpoints.component.html',
	styleUrls: ['./endpoints.component.scss']
})
export class EndpointsComponent implements OnInit {
	showCreateEndpointModal = this.router.url.split('/')[4] === 'new';
	showEditEndpointModal = this.router.url.split('/')[5] === 'edit';
	endpointsTableHead = ['Name', 'Status', 'ID', '', '', ''];
	displayedEndpoints?: { date: string; content: ENDPOINT[] }[];
	endpoints?: { pagination?: PAGINATION; content?: ENDPOINT[] };
	selectedEndpoint?: ENDPOINT;
	isLoadingEndpoints = true;
	showEndpointSecret = false;
	isDeletingEndpoint = false;
	showDeleteModal = false;
	isTogglingEndpoint = false;
	isSendingTestEvent = false;
	endpointSearchString!: string;

	constructor(public router: Router, public privateService: PrivateService, public projectService: ProjectService, private endpointService: EndpointsService, private generalService: GeneralService, public route: ActivatedRoute) {}

	ngOnInit() {
		this.getEndpoints();
	}

	async getEndpoints(requestDetails?: CURSOR & { search?: string; hideLoader?: boolean }) {
		this.isLoadingEndpoints = !requestDetails?.hideLoader;

		try {
			const response = await this.privateService.getEndpoints({ ...requestDetails, q: requestDetails?.search || this.endpointSearchString });
			this.endpoints = response.data;
			this.displayedEndpoints = this.generalService.setContentDisplayed(response.data.content);
			this.isLoadingEndpoints = false;
		} catch {
			this.isLoadingEndpoints = false;
		}
	}

	searchEndpoint(searchDetails: { searchInput?: any }) {
		const searchString: string = searchDetails?.searchInput?.target?.value || this.endpointSearchString;
		this.getEndpoints({ search: searchString, hideLoader: true });
	}

	async deleteEndpoint() {
		if (!this.selectedEndpoint) return;
		this.isDeletingEndpoint = true;

		try {
			const response = await this.endpointService.deleteEndpoint(this.selectedEndpoint?.uid || '');
			this.getEndpoints({ hideLoader: true });

			this.generalService.showNotification({ style: 'success', message: response.message });
			this.showDeleteModal = false;
			this.isDeletingEndpoint = false;
		} catch {
			this.isDeletingEndpoint = false;
		}
	}

	async toggleEndpoint() {
		this.isTogglingEndpoint = true;
		if (!this.selectedEndpoint?.uid) return;

		try {
			const response = await this.endpointService.toggleEndpoint(this.selectedEndpoint?.uid);
			this.displayedEndpoints?.forEach(item => {
				item.content.forEach(endpoint => {
					if (response.data.uid === endpoint.uid) endpoint.status = response.data.status;
				});
			});
			this.generalService.showNotification({ message: `${this.selectedEndpoint?.title} status updated successfully`, style: 'success' });
			this.isTogglingEndpoint = false;
		} catch {
			this.isTogglingEndpoint = false;
		}
	}

	async sendTestEvent() {
		const testEvent = {
			data: { data: 'test event from Convoy', convoy: 'https://getconvoy.io', amount: 1000 },
			endpoint_id: this.selectedEndpoint?.uid,
			event_type: 'test.convoy'
		};

		this.isSendingTestEvent = true;
		try {
			const response = await this.endpointService.sendEvent({ body: testEvent });
			this.generalService.showNotification({ message: response.message, style: 'success' });
			this.isSendingTestEvent = false;
		} catch {
			this.isSendingTestEvent = false;
		}
	}

	cancel() {
		this.router.navigateByUrl('/projects/' + this.projectService.activeProjectDetails?.uid + '/endpoints');
	}
}

<!-- empty state  -->
<div class="py-80px min-h-[500px]" *ngIf="!userSearch && !isLoadingEndpoints && !displayedEndpoints?.length">
	<div
		convoy-empty-state
		imgSrc="/assets/img/events-log-empty-state.png"
		[heading]="endpointSearchString ? endpointSearchString + ' endpoint does not exist' : 'You currently do not have any endpoints'"
		description="Endpoints will be listed here when available"
		id="endpoints-empty-state"
	>
		<button convoy-permission="Endpoints|MANAGE" emptyStateCTA convoy-button size="sm" class="mt-36px" id="create-endpoint-modal-button" routerLink="./new">
			<svg width="22" height="22" class="mr-2 scale-75" fill="#ffffff">
				<use xlink:href="#plus-icon"></use>
			</svg>
			Create Endpoint
		</button>
	</div>
</div>

<div class="relative min-h-[500px] flex items-center justify-center" *ngIf="isLoadingEndpoints">
	<convoy-loader position="relative"></convoy-loader>
</div>

<!-- If user has endpoints -->
<ng-container *ngIf="userSearch || (!isLoadingEndpoints && displayedEndpoints?.length)">
	<div class="flex justify-between items-end mb-24px">
		<div class="flex items-center">
			<h1 class="text-18 font-bold text-neutral-12 mr-10px">Endpoints</h1>
			<!-- <convoy-tooltip tooltipContent="Endpoints are receivers, they recieve the webhook events from sources it is subscribed to" position="right"></convoy-tooltip> -->
		</div>
	</div>

	<div class="flex items-center justify-between mb-24px mt-18px">
		<div class="flex items-center">
			<form class="border border-primary-400 h-36px px-14px py-0 max-w-[350px] w-full rounded-[10px] flex items-center bg-white-100" (ngSubmit)="getEndpoints({ search: endpointSearchString, hideLoader: true })">
				<img src="/assets/img/search-icon.svg" alt="search icon" class="mr-10px" />
				<input type="search" placeholder="Search endpoints" class="w-full text-neutral-11 text-12 outline-none" [(ngModel)]="endpointSearchString" [ngModelOptions]="{ standalone: true }" />
				<button convoy-button *ngIf="endpointSearchString && endpointSearchString.length > 0" class="transition-all duration-200" fill="text" (click)="getEndpoints({ search: endpointSearchString, hideLoader: true })" size="sm">
					<img src="/assets/img/enter-icon.png" alt="enter icon" class="w-16px" />
				</button>
			</form>
		</div>

		<button convoy-permission="Endpoints|MANAGE" *ngIf="displayedEndpoints?.length" convoy-button size="sm" class="h-36px" id="create-endpoint-modal-button" routerLink="./new">
			<svg width="22" height="22" class="mr-2 scale-75" fill="#ffffff">
				<use xlink:href="#plus-icon"></use>
			</svg>
			Endpoint
		</button>
	</div>

	<div convoy-card>
		<div class="min-h-[70vh] overflow-y-auto overflow-x-auto w-full min-w-[485px]" id="event-deliveries-table-container">
			<table convoy-table>
				<thead convoy-table-head class="border-b border-b-new.primary-25">
					<th convoy-table-head-cell [class]="i === 0 ? 'pl-20px' : ''" *ngFor="let head of endpointsTableHead; let i = index">{{ head }}</th>
				</thead>
				<tbody>
					<ng-container *ngFor="let endpointGroup of displayedEndpoints; let i = index">
						<tr convoy-table-row [forDate]="true">
							<td convoy-table-cell [forDate]="true">{{ endpointGroup.date }}</td>
							<td convoy-table-cell [forDate]="true"></td>
							<td convoy-table-cell [forDate]="true"></td>
							<td convoy-table-cell [forDate]="true"></td>
							<td convoy-table-cell [forDate]="true"></td>
							<td convoy-table-cell [forDate]="true"></td>
						</tr>
						<tr convoy-table-row *ngFor="let endpoint of endpointGroup.content; let index = index" [id]="'endpoint' + i" class="border-b border-b-new.primary-25" (click)="selectedEndpoint = endpoint">
							<td convoy-table-cell class="w-[300px]">
								<div class="truncate max-w-[290px] pl-16px">{{ endpoint.name || endpoint.title }}</div>
							</td>
							<td convoy-table-cell class="w-100px">
								<convoy-tag *ngIf="endpoint.status" [color]="endpoint.status | statuscolor" className="ml-4px">{{ endpoint.status }}</convoy-tag>
							</td>
							<td convoy-table-cell class="relative">
								<div convoy-tag class="!gap-10px flex items-center">
									<span class="w-[200px] truncate">{{ endpoint.url || endpoint.target_url }}</span>

									<convoy-copy-button size="sm" [notificationText]="endpoint.name || endpoint.title + ' Url has been copied to clipboard'" [text]="endpoint.url || endpoint.target_url"></convoy-copy-button>
								</div>
							</td>
							<td convoy-table-cell class="relative">
								<div convoy-tag class="!gap-10px flex items-center">
									<span class="w-[150px] truncate">{{ endpoint.uid }}</span>

									<convoy-copy-button size="sm" [notificationText]="endpoint.name || endpoint.title + ' ID has been copied to clipboard'" [text]="endpoint.uid"></convoy-copy-button>
								</div>
							</td>

							<td convoy-table-cell colspan="2"></td>
							<td convoy-table-cell>
								<div class="w-full flex items-center justify-end">
									<button convoy-button size="xs" fill="soft" [routerLink]="['../events']" [relativeTo]="route" [queryParams]="{ endpointId: endpoint.uid }">
										<img src="/assets/img/view-events-icon.svg" class="w-14px mr-10px" alt="view events icon" />
										View Events
									</button>

									<div convoy-dropdown position="right">
										<button dropdownTrigger convoy-button size="xs" fill="text" class="ml-40px pr-24px">
											<svg width="21" height="20">
												<use xlink:href="#more-icon"></use>
											</svg>
										</button>

										<ul dropdownOptions class="p-10px">
											<li class="mb-4px rounded-8px py-4px px-6px hover:bg-new.primary-25 duration-300 transition-all">
												<button convoy-dropdown-option convoy-button color="neutral" class="w-full !justify-start" fill="text" (click)="secretDialog.showModal()">
													<svg width="16" height="16" class="mr-8px">
														<use xlink:href="#shield-icon"></use>
													</svg>
													View Secret
												</button>
											</li>
                                            <li class="mb-4px rounded-8px py-4px px-6px hover:bg-new.primary-25 duration-300 transition-all">
												<button convoy-dropdown-option convoy-button color="neutral" class="w-full !justify-start" fill="text" (click)="viewSubscription()">
													<svg width="18" height="18" class="stroke-neutral-10 mr-8px scale-90">
														<use xlink:href="#subscriptions-icon"></use>
													</svg>
													View Subscription
												</button>
											</li>
											<li class="mb-4px rounded-8px py-4px px-6px hover:bg-new.primary-25 duration-300 transition-all">
												<button convoy-dropdown-option convoy-button color="neutral" class="w-full !justify-start" fill="text" (click)="toggleEndpoint()" [disabled]="isTogglingEndpoint">
													<svg width="14" height="14" class="stroke-neutral-10 mr-8px">
														<use [attr.xlink:href]="selectedEndpoint?.status === 'paused' ? '#play-icon' : '#pause-icon'"></use>
													</svg>
													{{ selectedEndpoint?.status === 'paused' ? 'Unpause' : 'Pause' }}
												</button>
											</li>
											<li class="mb-4px rounded-8px py-4px px-6px hover:bg-new.primary-25 duration-300 transition-all">
												<button convoy-dropdown-option convoy-button color="neutral" fill="text" class="w-full !justify-start" [routerLink]="'./' + selectedEndpoint?.uid">
													<svg width="17" height="16" class="fill-neutral-10 mr-8px">
														<use xlink:href="#edit-icon"></use>
													</svg>
													Edit
												</button>
											</li>

											<li class="mb-4px rounded-8px py-4px px-6px hover:bg-new.primary-25 duration-300 transition-all">
												<button convoy-dropdown-option convoy-button color="error" class="w-full !justify-start" fill="text" (click)="deleteDialog.showModal()">
													<svg width="14" height="14" class="fill-transparent stroke-new.error-400 mr-8px">
														<use xlink:href="#delete-icon2"></use>
													</svg>
													Delete
												</button>
											</li>

											<li *ngIf="privateService.getProjectDetails?.type === 'outgoing'" class="mb-4px rounded-8px py-4px px-6px hover:bg-new.primary-25 duration-300 transition-all">
												<button convoy-dropdown-option convoy-button color="neutral" class="w-full !justify-start" fill="text" (click)="sendTestEvent()" [disabled]="isSendingTestEvent">
													<svg width="16" height="17" class="mr-8px">
														<use xlink:href="#send-icon"></use>
													</svg>
													Send Test Event
												</button>
											</li>
										</ul>
									</div>
								</div>
							</td>
						</tr>
					</ng-container>
				</tbody>
			</table>
		</div>

		<!-- Pagination -->
		<div class="border-t border-new.primary-25 px-16px" *ngIf="endpoints?.pagination?.has_next_page || endpoints?.pagination?.has_prev_page">
			<convoy-pagination [pagination]="endpoints?.pagination" (paginate)="getEndpoints($event)"></convoy-pagination>
		</div>
	</div>
</ng-container>
<!-- end If user has endpoints -->

<!-- create endpoint modal -->
<dialog #endpointDialog convoy-dialog position="full">
	<div convoy-dialog-header fullscreen="true" (closeDialog)="cancel()">
		<h2 class="font-semibold text-14 capitalize">{{ action === 'update' ? 'Edit Endpoint' : 'Create Endpoint' }}</h2>
	</div>
	<div class="h-full w-full">
		<div class="max-w-[770px] m-auto">
			<convoy-create-endpoint showAction="true" (onAction)="$event.action === 'close' ? cancel() : getEndpoints(); cancel()" [editMode]="action === 'update'"></convoy-create-endpoint>
		</div>
	</div>
</dialog>

<!-- endpoint secret  -->
<dialog #secretDialog convoy-dialog position="center">
	<convoy-endpoint-secret [endpointDetails]="selectedEndpoint" (closeSecretModal)="secretDialog.close()" (expireCurrentSecret)="getEndpoints()"></convoy-endpoint-secret>
</dialog>

<!-- delete modal  -->
<dialog #deleteDialog convoy-dialog position="center" size="sm">
	<app-delete-modal [isLoading]="isDeletingEndpoint" [deleteText]="'delete “' + selectedEndpoint?.name + '”'" (closeModal)="deleteDialog.close()" (deleteData)="deleteEndpoint()"></app-delete-modal>
</dialog>
