// web/components/app-portal-vue/src/lib-components/loader-component.vue
<script>
export default {
	data() {
		return {
			count: 0
		};
	},
	props: ['isTransparent']
};
</script>

<template>
	<div :class="'loader ' + (isTransparent ? 'transparent' : '')">
		<img v-bind:src="require('../assets/img/loader.gif')" alt="loader" />
	</div>
</template>

<style>
.loader {
	position: absolute;
	left: 0;
	right: 0;
	top: 0;
	bottom: 0;
	display: flex;
	justify-content: center;
	align-items: center;
	background: #fff;
	border-radius: 8px;
	z-index: 1;
}

.loader img {
	width: 100%;
	height: 100%;
	max-width: 150px;
	max-height: 110px;
}

.loader.transparent {
	opacity: 0.5;
}
</style>

// web/ui/dashboard/src/app/private/components/loader/loader.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
	selector: 'convoy-loader',
	templateUrl: './loader.component.html',
	styleUrls: ['./loader.component.scss']
})
export class LoaderComponent implements OnInit {
	@Input() isTransparent: boolean = false;
	@Input() position: 'absolute' | 'fixed' = 'absolute';

	constructor() {}

	ngOnInit(): void {}
}

<div class="absolute left-0 right-0 top-0 bottom-0 flex items-center justify-center bg-gradient-radial from-[#fefefecf] to-transparent rounded-8px h-full z-[1]" [ngClass]="{ 'opacity-50': isTransparent }">
	<img src="/assets/img/page-loader.gif" alt="loader" class="w-150px" />
</div>
