// web/ui/dashboard/src/app/public/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { LoginService } from './login.service';

@Component({
	selector: 'app-login',
	templateUrl: './login.component.html',
	styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
	showLoginPassword = false;
	disableLoginBtn = false;
	loginForm: FormGroup = this.formBuilder.group({
		username: ['', Validators.required],
		password: ['', Validators.required]
	});

	constructor(private formBuilder: FormBuilder, private router: Router, private loginService: LoginService) {}

	ngOnInit(): void {}

	async login() {
		if (this.loginForm.invalid) return this.loginForm.markAsTouched();

		this.disableLoginBtn = true;
		try {
			const response: any = await this.loginService.login(this.loginForm.value);
			localStorage.setItem('CONVOY_AUTH', JSON.stringify(response.data));
			this.router.navigateByUrl('/');
			this.disableLoginBtn = false;
		} catch {
			this.disableLoginBtn = false;
		}
	}
}

<div class="min-h-screen flex flex-col items-center justify-center w-full">
	<img src="/assets/img/logo.svg" alt="convoy logo" class="mb-28px w-130px" />
	<section class="max-w-[445px] mx-auto my-0 p-24px w-full bg-white-100 shadow-default rounded-8px">
		<form [formGroup]="loginForm" (ngSubmit)="login()">
			<div convoy-input-field>
				<label for="username" convoy-label>Username</label>
				<input type="text" id="username" convoy-input autocomplete="username" formControlName="username" placeholder="super@default.com" />
				<convoy-input-error *ngIf="loginForm.controls.username.touched && loginForm.controls.username.invalid">Please enter your username</convoy-input-error>
			</div>

			<div convoy-input-field>
				<label convoy-label for="password">Password</label>
				<convoy-password-field>
					<input [type]="showLoginPassword ? 'text' : 'password'" convoy-input autocomplete="username" formControlName="password" placeholder="super@default.com" id="password" />
					<button class="bg-transparent w-18px h-18px absolute top-[55%] right-16px border-none translate-x-0 translate-y-[-50%]" type="button" (click)="showLoginPassword = !showLoginPassword">
						<img class="w-full" [src]="!showLoginPassword ? '/assets/img/password-invisible-icon.svg' : '/assets/img/password-visible-icon.svg'" alt="showLoginPassword ? 'hide password icon' : 'view password icon'" />
					</button>
				</convoy-password-field>
				<convoy-input-error *ngIf="loginForm.controls.password.touched && loginForm.controls.password.invalid">Please enter your password</convoy-input-error>
			</div>

			<div class="flex items-center text-12 mb-20px -mt-18px">
				Forgot password?
				<button convoy-button fill="link" type="button" class="px-0 ml-6px" (click)="router.navigateByUrl('/forgot-password')" size="sm">Reset it here</button>
			</div>

			<button convoy-button [disabled]="disableLoginBtn" size="lg" class="mb-12px">
				<span class="text-14 text-white-100" *ngIf="!disableLoginBtn">Login</span>
				<img *ngIf="disableLoginBtn" src="assets/img/button-loader.gif" alt="loader" class="h-18px" />
			</button>

			<button *ngIf="isSSOEnabled" convoy-button size="sm" type="button" fill="text" class="w-full" (click)="loginWithSSO()">Login with SSO</button>

			<button *ngIf="isGoogleOAuthEnabled" convoy-button size="sm" type="button" fill="text" class="w-full mt-12px" (click)="loginWithGoogle()" [disabled]="isGoogleSigningIn">
				<img *ngIf="!isGoogleSigningIn" src="/assets/img/svg/google.svg" alt="Google icon" class="w-16px h-16px inline mr-8px" />
				<div *ngIf="isGoogleSigningIn" class="loading-dots inline mr-8px">
					<span></span>
					<span></span>
					<span></span>
				</div>
				<span *ngIf="!isGoogleSigningIn">Sign in with Google</span>
				<span *ngIf="isGoogleSigningIn">Signing in...</span>
			</button>
		</form>

		<button *ngIf="isSignupEnabled && licenseService.hasLicense('user_limit')" convoy-button fill="link" class="mt-12px w-full" (click)="router.navigateByUrl('/signup')" size="sm">Signup</button>
	</section>
</div>

<convoy-loader [isTransparent]="false" *ngIf="isLoadingProject || isFetchingConfig"></convoy-loader>

// web/ui/react-app/src/pages/login/index.js
import React, { useState } from 'react';
import * as axios from 'axios';
import ConvoyLogo from '../../assets/img/logo.svg';
import PasswordInvisibleIcon from '../../assets/img/password-visible-icon.svg';
import PasswordVisibleIcon from '../../assets/img/password-invisible-icon.svg';
import { useHistory } from 'react-router-dom';
import { APIURL } from '../../helpers/get-details';
import './style.scss';

const _axios = axios.default;
const request = _axios.create({ baseURL: APIURL });

function LoginPage() {
	const [showLoginPassword, toggleShowLoginPassword] = useState(false);
	const [disableLoginBtn, toggleDisableLoginBtn] = useState(false);
	const [loginDetails, updateLoginDetails] = useState({ username: '', password: '' });
	let route = useHistory();

	const handleUserInput = (event) => {
		const { name, value } = event.target;
		loginDetails[name] = value;
		updateLoginDetails(loginDetails);
	};

	const userLogin = async (event) => {
		event.preventDefault();
		toggleDisableLoginBtn(true);
		try {
			const loginResponse = await (await request({ method: 'POST', url: '/auth/login', data: loginDetails })).data;
			localStorage.setItem('CONVOY_AUTH', JSON.stringify(loginResponse.data));
			toggleDisableLoginBtn(false);
			route.push('/');
		} catch (error) {
			toggleDisableLoginBtn(false);
		}
	};

	return (
		<div className="auth-page">
			<section className="auth-page--container">
				<img src={ConvoyLogo} alt="convoy logo" />

				<form onSubmit={userLogin}>
					<div className="input">
						<label htmlFor="username">Username</label>
						<input type="text" id="username" name="username" autoComplete="username" placeholder="Enter username here" onChange={handleUserInput} />
					</div>

					<div className="input">
						<label htmlFor="password">Password</label>
						<div className="input--password">
							<input type={showLoginPassword ? 'text' : 'password'} id="password" name="password" autoComplete="current-password" placeholder="Enter your password" onChange={handleUserInput} />
							<button className="input--password__view-toggle" type="button" onClick={() => toggleShowLoginPassword(!showLoginPassword)}>
								<img src={showLoginPassword ? PasswordVisibleIcon : PasswordInvisibleIcon} alt={showLoginPassword ? 'hide password icon' : 'view password icon'} />
							</button>
						</div>
					</div>

					<div className="button-container  margin-top">
						<button disabled={disableLoginBtn} className="primary full-100">
							{disableLoginBtn ? 'loading....' : 'Login to Dashboard'}
						</button>
					</div>
				</form>
			</section>
		</div>
	);
}

export { LoginPage };
