// web/components/app-portal-vue/src/lib-components/loader-component.vue
<script>
export default {
	data() {
		return {
			count: 0
		};
	},
	props: ['isTransparent']
};
</script>

<template>
	<div :class="'loader ' + (isTransparent ? 'transparent' : '')">
		<img v-bind:src="require('../assets/img/loader.gif')" alt="loader" />
	</div>
</template>

<style>
.loader {
	position: absolute;
	left: 0;
	right: 0;
	top: 0;
	bottom: 0;
	display: flex;
	justify-content: center;
	align-items: center;
	background: #fff;
	border-radius: 8px;
	z-index: 1;
}

.loader img {
	width: 100%;
	height: 100%;
	max-width: 150px;
	max-height: 110px;
}

.loader.transparent {
	opacity: 0.5;
}
</style>

// web/ui/dashboard-component/projects/convoy-dashboard/src/lib/loader-component/loader.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
	selector: 'convoy-loader',
	template: `
		<div [class]="'loader ' + (isTransparent ? 'transparent' : '')">
			<img src="/assets/img/loader.gif" alt="loader" />
		</div>
	`,
	styles: [
		`
			.loader {
				position: absolute;
				left: 0;
				right: 0;
				top: 0;
				bottom: 0;
				display: flex;
				justify-content: center;
				align-items: center;
				background: #fff;
				border-radius: 8px;
				z-index: 1;
			}

			.loader img {
				width: 25%;
			}

			.loader.transparent {
				opacity: 0.5;
			}
		`
	]
})
export class ConvoyLoaderComponent implements OnInit {
	constructor() {}
	@Input('isTransparent') isTransparent: boolean = false;

	async ngOnInit() {}
}
