// web/ui/dashboard-react/src/app/signup.tsx
import { useState } from 'react';
import { z } from 'zod';
import { cn } from '@/lib/utils';
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import * as signUpService from '@/services/signup.service';
import * as hubSpotService from '@/services/hubspot.service';
import * as licensesService from '@/services/licenses.service';
import { router } from '@/lib/router';
import { CONVOY_DASHBOARD_DOMAIN } from '@/lib/constants';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm, type UseFormReturn } from 'react-hook-form';
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessageWithErrorIcon,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { EyeIcon, EyeOffIcon } from 'lucide-react';

type FormFieldInputComponentProps = {
	form: UseFormReturn<z.infer<typeof formSchema>>;
};

function BusinessNameInputField({ form }: FormFieldInputComponentProps) {
	return (
		<FormField
			control={form.control}
			name="orgName"
			render={({ field, fieldState }) => (
				<FormItem className="w-full relative mb-6 block">
					<div className="w-full mb-2 flex items-center">
						<FormLabel className="w-full flex items-center justify-between">
							<span className="text-xs/5 text-neutral-9 block">
								Business Name
							</span>
							{/* <Badge
															variant={'outline'}
															className="text-[11px] font-normal px-1 ml-2 bg-new.gray-200"
														>
															required
														</Badge> */}
						</FormLabel>
					</div>
					<FormControl>
						<Input
							autoComplete="organization"
							type="text"
							className={cn(
								'mt-0 outline-none focus-visible:ring-0 border-neutral-4 shadow-none w-full h-auto transition-all duration-300 bg-white-100 py-3 px-4 text-neutral-11 !text-xs/5 rounded-[4px] placeholder:text-new.gray-300 placeholder:text-sm/5 font-normal disabled:text-neutral-6 disabled:border-new.primary-25',
								fieldState.error
									? 'border-new.error-500 focus-visible:ring-0 hover:border-new.error-500'
									: ' hover:border-new.primary-100 focus:border-new.primary-300',
							)}
							placeholder="Convoy"
							{...field}
						/>
					</FormControl>
					<FormMessageWithErrorIcon />
				</FormItem>
			)}
		/>
	);
}

function EmailInputField({ form }: FormFieldInputComponentProps) {
	return (
		<FormField
			control={form.control}
			name="email"
			render={({ field, fieldState }) => (
				<FormItem className="w-full relative mb-6 block">
					<div className="w-full mb-2 flex items-center">
						<FormLabel className="w-full flex items-center justify-between">
							<span className="text-xs/5 text-neutral-9 block">Email</span>
						</FormLabel>
					</div>
					<FormControl>
						<Input
							autoComplete="email"
							type="email"
							className={cn(
								'mt-0 outline-none focus-visible:ring-0 border-neutral-4 shadow-none w-full h-auto transition-all duration-300 bg-white-100 py-3 px-4 text-neutral-11 !text-xs/5 rounded-[4px] placeholder:text-new.gray-300 placeholder:text-sm/5 font-normal disabled:text-neutral-6 disabled:border-new.primary-25',
								fieldState.error
									? 'border-new.error-500 focus-visible:ring-0 hover:border-new.error-500'
									: ' hover:border-new.primary-100 focus:border-new.primary-300',
							)}
							placeholder="super@default.com"
							{...field}
						/>
					</FormControl>
					<FormMessageWithErrorIcon />
				</FormItem>
			)}
		/>
	);
}

function FirstNameInputField({ form }: FormFieldInputComponentProps) {
	return (
		<FormField
			control={form.control}
			name="firstName"
			render={({ field, fieldState }) => (
				<FormItem className="w-full relative mb-6 block">
					<div className="w-full mb-2 flex items-center">
						<FormLabel className="w-full flex items-center justify-between">
							<span className="text-xs/5 text-neutral-9 block">First Name</span>
						</FormLabel>
					</div>
					<FormControl>
						<Input
							autoComplete="name"
							type="text"
							className={cn(
								'mt-0 outline-none focus-visible:ring-0 border-neutral-4 shadow-none w-full h-auto transition-all duration-300 bg-white-100 py-3 px-4 text-neutral-11 !text-xs/5 rounded-[4px] placeholder:text-new.gray-300 placeholder:text-sm/5 font-normal disabled:text-neutral-6 disabled:border-new.primary-25',
								fieldState.error
									? 'border-new.error-500 focus-visible:ring-0 hover:border-new.error-500'
									: ' hover:border-new.primary-100 focus:border-new.primary-300',
							)}
							placeholder="John"
							{...field}
						/>
					</FormControl>
					<FormMessageWithErrorIcon />
				</FormItem>
			)}
		/>
	);
}

function LastNameInputField({ form }: FormFieldInputComponentProps) {
	return (
		<FormField
			control={form.control}
			name="lastName"
			render={({ field, fieldState }) => (
				<FormItem className="w-full relative mb-6 block">
					<div className="w-full mb-2 flex items-center">
						<FormLabel className="w-full flex items-center justify-between">
							<span className="text-xs/5 text-neutral-9 block">Last Name</span>
						</FormLabel>
					</div>
					<FormControl>
						<Input
							autoComplete="family-name"
							type="text"
							className={cn(
								'mt-0 outline-none focus-visible:ring-0 border-neutral-4 shadow-none w-full h-auto transition-all duration-300 bg-white-100 py-3 px-4 text-neutral-11 !text-xs/5 rounded-[4px] placeholder:text-new.gray-300 placeholder:text-sm/5 font-normal disabled:text-neutral-6 disabled:border-new.primary-25',
								fieldState.error
									? 'border-new.error-500 focus-visible:ring-0 hover:border-new.error-500'
									: ' hover:border-new.primary-100 focus:border-new.primary-300',
							)}
							placeholder="Doe"
							{...field}
						/>
					</FormControl>
					<FormMessageWithErrorIcon />
				</FormItem>
			)}
		/>
	);
}

function PasswordInputField({ form }: FormFieldInputComponentProps) {
	const [isPasswordVisible, setIsPasswordVisible] = useState(false);

	return (
		<FormField
			control={form.control}
			name="password"
			render={({ field, fieldState }) => (
				<FormItem className="w-full relative mb-6 block">
					<div className="w-full mb-[8px] flex items-center justify-between">
						<FormLabel
							className="text-xs/5 text-neutral-9"
							htmlFor="password_input"
						>
							Password
						</FormLabel>
					</div>
					<FormControl className="w-full relative">
						<div className="relative">
							<Input
								id="password_input"
								autoComplete="current-password"
								type={isPasswordVisible ? 'text' : 'password'}
								className={cn(
									'hide-password-toggle mt-0 outline-none focus-visible:ring-0 border-neutral-4 shadow-none w-full h-auto transition-all duration-300 bg-white-100 py-3 px-4 text-neutral-11 !text-xs/5 rounded-[4px] placeholder:text-new.gray-300 placeholder:text-sm/5 font-normal disabled:text-neutral-6 disabled:border-new.primary-25',
									fieldState.error
										? 'border-new.error-500 focus-visible:ring-0 hover:border-new.error-500'
										: 'hover:border-new.primary-100 focus:border-new.primary-300',
								)}
								{...field}
							/>
							<Button
								type="button"
								variant="ghost"
								size="sm"
								className="absolute right-[1%] top-0 h-full px-3 py-2 hover:bg-transparent"
								onClick={() => setIsPasswordVisible(!isPasswordVisible)}
							>
								{isPasswordVisible ? (
									<EyeIcon className="opacity-50" aria-hidden="true" />
								) : (
									<EyeOffIcon className="opacity-50" aria-hidden="true" />
								)}
								<span className="sr-only">
									{isPasswordVisible ? 'Hide password' : 'Show password'}
								</span>
							</Button>
						</div>
					</FormControl>
					<FormMessageWithErrorIcon />
				</FormItem>
			)}
		/>
	);
}

function SignUpButton(props: { isButtonEnabled?: boolean }) {
	const { isButtonEnabled } = props;

	return (
		<Button
			disabled={!isButtonEnabled}
			variant={'ghost'}
			size={'lg'}
			className="flex items-center justify-center disabled:opacity-50 cursor-pointer mb-3 bg-new.primary-400 hover:bg-new.primary-400 px-9 py-[10px] rounded-8px text-sm/5 text-white-100 w-full"
		>
			<span
				className={cn(
					'text-sm text-white-100',
					!isButtonEnabled ? 'hidden' : '',
				)}
			>
				Sign Up
			</span>
			<img
				className={cn('h-4', !isButtonEnabled ? '' : 'hidden')}
				src="assets/img/button-loader.gif"
				alt="loader"
			/>
		</Button>
	);
}

function SignUpWithSAMLButton() {
	async function signUp() {
		localStorage.setItem('AUTH_TYPE', 'signup');

		try {
			const { data } = await signUpService.signUpWithSAML();
			window.open(data.redirectUrl, '_blank');
		} catch (err) {
			// TODO show user on the UI
			throw err;
		}
	}

	return (
		<Button
			type="button"
			size={'lg'}
			variant={'ghost'}
			onClick={signUp}
			className="disabled:opacity-50 cursor-pointer w-full rounded-8px text-xs/5 text-new.primary-400 hover:text-new.primary-400 py-0 hover:bg-transparent h-auto"
		>
			Sign Up with SAML
		</Button>
	);
}

const formSchema = z.object({
	email: z.string().email('Please enter your email'),
	password: z.string().min(1, 'Password is required'),
	lastName: z.string().trim().min(1, 'Please enter your last name'),
	firstName: z.string().trim().min(1, 'Please enter your first name'),
	orgName: z.string().trim().min(1, 'Please enter your business name'),
});

function SignUpPage() {
	const navigate = useNavigate();
	const [isSignUpButtonEnabled, setIsSignUpButtonEnabled] = useState(true);

	const form = useForm<z.infer<typeof formSchema>>({
		resolver: zodResolver(formSchema),
		defaultValues: {
			email: '',
			orgName: '',
			password: '',
			firstName: '',
			lastName: '',
		},
		mode: 'onTouched',
	});

	async function signUp(values: z.infer<typeof formSchema>) {
		setIsSignUpButtonEnabled(false);
		const { email, firstName, lastName, orgName, password } = values;

		try {
			await signUpService.signUp({
				email,
				password,
				org_name: orgName,
				last_name: lastName,
				first_name: firstName,
			});

			if (location.hostname == CONVOY_DASHBOARD_DOMAIN) {
				await hubSpotService.sendWelcomeEmail({
					email,
					firstname: firstName,
					lastname: lastName,
				});
			}

			setIsSignUpButtonEnabled(false);
			navigate({
				from: '/signup',
				to: '/get-started',
			});
		} catch (err) {
			// TODO show user error on UI
			setIsSignUpButtonEnabled(false);
		}
	}

	function navigateToLoginPage() {
		return navigate({
			from: '/signup',
			to: '/login',
		});
	}

	return (
		<div className="flex w-full">
			<aside className="bg-primary-100 bg-[url('/assets/img/public-layout.png')] bg-no-repeat bg-right-top min-w-[374px] desktop:w-0 h-screen transition-all duration-300 px-[36px] pt-[70px]"></aside>
			<div className="bg-[url('/assets/svg/pattern.svg')] bg-center bg-cover min-h-screen w-full">
				<div className="min-h-screen flex flex-col items-center justify-center w-full">
					<img
						src="/assets/svg/logo.svg"
						alt="convoy logo"
						className="mb-7 w-[130px]"
					/>

					<section className="max-w-[445px] mx-auto my-0 p-6 w-full bg-white-100 shadow-default rounded-[8px]">
						<Form {...form}>
							<form
								onSubmit={(...args) => void form.handleSubmit(signUp)(...args)}
							>
								<BusinessNameInputField form={form} />
								<EmailInputField form={form} />
								<FirstNameInputField form={form} />
								<LastNameInputField form={form} />
								<PasswordInputField form={form} />
								<SignUpButton isButtonEnabled={isSignUpButtonEnabled} />
								<SignUpWithSAMLButton />
							</form>
						</Form>
					</section>

					<Button
						type="button"
						size={'sm'}
						variant={'ghost'}
						onClick={navigateToLoginPage}
						className="mt-[34px] disabled:opacity-50 cursor-pointer w-full rounded-8px text-xs/5 text-new.primary-400 hover:text-new.primary-400 py-0 hover:bg-transparent h-auto underline"
					>
						Log in if you already have an account
					</Button>
				</div>
			</div>
		</div>
	);
}

export const Route = createFileRoute('/signup')({
	async beforeLoad() {
		try {
			await licensesService.setLicenses();
			const hasCreateUserLicense = licensesService.hasLicense('CREATE_USER');
			if (!hasCreateUserLicense)
				throw new Error('beforeLoad: client is not licensed to create user');
		} catch (err) {
			console.error('beforeLoad:', err);
			router.navigate({ to: '/' });
		}
	},
	component: SignUpPage,
});

// web/ui/dashboard/src/app/public/signup/signup.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ButtonComponent } from 'src/app/components/button/button.component';
import { InputDirective, InputErrorComponent, InputFieldDirective, LabelComponent } from 'src/app/components/input/input.component';
import { LoaderModule } from 'src/app/private/components/loader/loader.module';
import { HubspotService } from 'src/app/services/hubspot/hubspot.service';
import { SignupService } from './signup.service';
import { LicensesService } from 'src/app/services/licenses/licenses.service';

@Component({
	selector: 'convoy-signup',
	standalone: true,
	imports: [CommonModule, ReactiveFormsModule, ButtonComponent, InputErrorComponent, InputDirective, LabelComponent, InputFieldDirective, LoaderModule],
	templateUrl: './signup.component.html',
	styleUrls: ['./signup.component.scss']
})
export class SignupComponent implements OnInit {
	showSignupPassword = false;
	disableSignupBtn = false;
	isFetchingConfig = false;
	signupForm: FormGroup = this.formBuilder.group({
		email: ['', Validators.required],
		first_name: ['', Validators.required],
		last_name: ['', Validators.required],
		password: ['', Validators.required],
		org_name: ['', Validators.required]
	});

	constructor(private formBuilder: FormBuilder, private signupService: SignupService, public router: Router, private hubspotService: HubspotService, private licenseService: LicensesService) {}

	ngOnInit(): void {
		this.licenseService.setLicenses();

		if (!this.licenseService.hasLicense('CREATE_USER')) this.router.navigateByUrl('/login');
	}

	async signup() {
		if (this.signupForm.invalid) return this.signupForm.markAllAsTouched();

		this.disableSignupBtn = true;
		try {
			const response: any = await this.signupService.signup(this.signupForm.value);
			localStorage.setItem('CONVOY_AUTH', JSON.stringify(response.data));
			localStorage.setItem('CONVOY_AUTH_TOKENS', JSON.stringify(response.data.token));

			if (window.location.hostname === 'dashboard.getconvoy.io') await this.hubspotService.sendWelcomeEmail({ email: this.signupForm.value.email, firstname: this.signupForm.value.first_name, lastname: this.signupForm.value.last_name });

			this.router.navigateByUrl('/get-started');
			this.disableSignupBtn = false;
		} catch {
			this.disableSignupBtn = false;
		}
	}

	async getSignUpConfig() {
		this.isFetchingConfig = true;
		try {
			const response = await this.signupService.getSignupConfig();
			const isSignupEnabled = response.data;
			if (!isSignupEnabled) this.router.navigateByUrl('/login');
			this.isFetchingConfig = false;
		} catch (error) {
			this.isFetchingConfig = false;
			throw error;
		}
	}

	async signUpWithSAML() {
		try {
			const res = await this.signupService.signUpWithSAML();
			console.log(res);
            const { redirectUrl } = res.data;
			window.open(redirectUrl, '_blank');
		} catch (error) {
			throw error;
		}
	}
}

<div class="min-h-screen flex flex-col items-center justify-center w-full">
	<img src="/assets/img/logo.svg" alt="convoy logo" class="mb-28px w-130px" />
	<section class="max-w-[445px] mx-auto my-0 p-24px w-full bg-white-100 shadow-default rounded-8px">
		<!-- We don't have this component or need it yet. Temporary hold; it might be used here. -->
		<!-- <div class="bg-primary-500 mb-20px border border-primary-100 border-dashed rounded-8px py-10px px-16px flex">
             <img src="/assets/img/ideas.svg" alt="idea" class="mr-8px" />
             <div class="text-12">Please note that our cloud platform is in private beta.</div>
         </div> -->

		<form [formGroup]="signupForm" (ngSubmit)="signup()" class="flex flex-wrap justify-between">
			<convoy-input-field>
				<label for="org_name" convoy-label required="true">Business Name</label>
				<input id="org_name" convoy-input autocomplete="org_name" formControlName="org_name" placeholder="Convoy" />
				<convoy-input-error *ngIf="signupForm.get('org_name')?.touched && signupForm.get('org_name')?.invalid">Please enter your business name</convoy-input-error>
			</convoy-input-field>
			<convoy-input-field>
				<label for="email" convoy-label required="true">Email</label>
				<input type="email" id="email" convoy-input autocomplete="email" formControlName="email" placeholder="super@default.com" />
				<convoy-input-error *ngIf="signupForm.get('email')?.touched && signupForm.get('email')?.invalid">Please enter your email</convoy-input-error>
			</convoy-input-field>
			<convoy-input-field>
				<label for="first_name" convoy-label required="true">First Name</label>
				<input id="first_name" convoy-input autocomplete="first_name" formControlName="first_name" placeholder="John" />
				<convoy-input-error *ngIf="signupForm.get('first_name')?.touched && signupForm.get('first_name')?.invalid">Please enter your first name</convoy-input-error>
			</convoy-input-field>
			<convoy-input-field>
				<label for="last_name" convoy-label required="true">Last Name</label>
				<input id="last_name" convoy-input autocomplete="last_name" formControlName="last_name" placeholder="Doe" />
				<convoy-input-error *ngIf="signupForm.get('last_name')?.touched && signupForm.get('last_name')?.invalid">Please enter your last name</convoy-input-error>
			</convoy-input-field>
			<convoy-input-field>
				<label for="new-password" convoy-label required="true">Password</label>
				<input type="password" id="new-password" convoy-input autocomplete="new-password" formControlName="password" />
				<convoy-input-error *ngIf="signupForm.get('password')?.touched && signupForm.get('password')?.invalid">Password is required</convoy-input-error>
			</convoy-input-field>

			<button convoy-button [disabled]="disableSignupBtn" size="lg" class="w-full mb-12px">
				<span class="text-14 text-white-100" *ngIf="!disableSignupBtn">Signup</span>
				<img *ngIf="disableSignupBtn" src="assets/img/button-loader.gif" alt="loader" class="h-18px" />
			</button>

			<button convoy-button size="sm" type="button" fill="text" class="w-full" (click)="signUpWithSAML()">Sign Up with SAML</button>
		</form>
	</section>

	<button convoy-button fill="link" class="mt-34px w-full" (click)="router.navigateByUrl('/login')" size="sm">Log in if you already have an account</button>
</div>

<convoy-loader [isTransparent]="false" *ngIf="isFetchingConfig"></convoy-loader>
