// web/ui/dashboard/src/app/private/pages/project/sources/sources.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { PAGINATION } from 'convoy-app/lib/models/global.model';
import { SOURCE } from 'src/app/models/group.model';
import { PrivateService } from 'src/app/private/private.service';
import { SourcesService } from './sources.service';

@Component({
	selector: 'app-sources',
	templateUrl: './sources.component.html',
	styleUrls: ['./sources.component.scss']
})
export class SourcesComponent implements OnInit {
	sourcesTableHead: string[] = ['Source name', 'Source type', 'Verifier', 'URL', 'Date created', ''];
	shouldShowCreateSourceModal = this.router.url.split('/')[4] === 'new';
	activeSource?: SOURCE;
	sources!: { content: SOURCE[]; pagination: PAGINATION };
	isLoadingSources = false;
	projectId = this.privateService.activeProjectId;

	constructor(private route: ActivatedRoute, private router: Router, private sourcesService: SourcesService, private privateService: PrivateService) {
		this.route.queryParams.subscribe(params => {
			this.activeSource = this.sources?.content.find(source => source.uid === params?.id);
		});
	}

	ngOnInit() {
		this.getSources();
	}

	async getSources(requestDetails?: { page?: number }) {
		const page = requestDetails?.page || this.route.snapshot.queryParams.page || 1;
		this.isLoadingSources = true;
		try {
			const sourcesResponse = await this.privateService.getSources({ page });
			this.sources = sourcesResponse.data;
			this.isLoadingSources = false;
			this.activeSource = this.sources?.content.find(source => source.uid === this.route.snapshot.queryParams?.id);
		} catch (error) {
			this.isLoadingSources = false;
			return error;
		}
	}

	async deleteSource() {
		try {
			await this.sourcesService.deleteSource(this.activeSource?.uid);
			this.getSources();
			this.router.navigateByUrl('./');
			this.activeSource = undefined;
		} catch (error) {
			console.log(error);
		}
	}
}

<div class="text-12 font-medium flex items-center uppercase">
	<a routerLink="/projects" class="font-medium cursor-pointer">Projects</a>
	<svg width="16" height="16" class="mx-4px">
		<use xlink:href="#arrow-right-icon"></use>
	</svg>
	{{ privateService.activeProjectDetails?.name }}
	<svg width="16" height="16" class="mx-4px">
		<use xlink:href="#arrow-right-icon"></use>
	</svg>
	<span class="text-primary-100 font-medium">Sources</span>
</div>

<div class="flex justify-between items-end mt-24px border-b border-b-grey-10 pb-20px mb-24px">
	<div>
		<h1 class="text-24 font-bold text-grey-80">Sources</h1>
		<p class="text-grey-60 text-14 mt-6px max-w-2xl">Your sources are channels connected to Convoy to trigger webhook events to subscribed endpoints</p>
	</div>
	<button convoy-button size="sm" routerLink="./new">Connect a source</button>
</div>

<ng-container *ngIf="privateService.activeProjectDetails?.type === 'incoming'">
	<div class="flex flex-wrap gap-24px" *ngIf="isLoadingSources">
		<div class="bg-grey-10 rounded-8px animate-pulse w-348px h-128px"></div>
		<div class="bg-grey-10 rounded-8px animate-pulse w-348px h-128px"></div>
		<div class="bg-grey-10 rounded-8px animate-pulse w-348px h-128px"></div>
		<div class="bg-grey-10 rounded-8px animate-pulse w-348px h-128px"></div>
		<div class="bg-grey-10 rounded-8px animate-pulse w-348px h-128px"></div>
		<div class="bg-grey-10 rounded-8px animate-pulse w-348px h-128px"></div>
	</div>

	<ng-container *ngIf="!isLoadingSources && sources?.content?.length">
		<div class="flex flex-wrap gap-24px">
			<convoy-card className="py-20px" hover="true" class="w-full max-w-[348px] cursor-pointer" *ngFor="let source of sources?.content; let i = index" [id]="'app' + i" [routerLink]="['./']" [queryParams]="{ id: source.uid }">
				<div class="px-24px pb-12px border-b border-b-grey-10">
					<div class="text-grey-40 text-10 mb-4px">{{ source.provider || (source.verifier.type | sourceValue: 'verifier') }}</div>
					<div class="flex justify-between items-center">
						<div class="text-14 font-medium">{{ source.name }}</div>
						<svg width="18" height="18" class="fill-grey-60">
							<use xlink:href="#arrow-right-icon"></use>
						</svg>
					</div>
				</div>
				<div class="mt-12px mx-24px">
					<convoy-copy-button [text]="source.url" size="md" className="ml-2px" [notificationText]="source.name + ' URL has been copied to clipboard'"><span class="text14 ml-8px font-medium">Copy URL</span></convoy-copy-button>
				</div>
			</convoy-card>
		</div>
	</ng-container>
</ng-container>

<convoy-empty-state
	imgSrc="/assets/img/new-empty-state.png"
	heading="Create your first source"
	description="Sources are how your webhook events are routed into the Convoy."
	className="min-h-[65vh] mt-16px"
	id="sources-empty-state"
	*ngIf="!isLoadingSources && sources?.content?.length == 0"
></convoy-empty-state>

<div convoy-modal *ngIf="activeSource?.uid" position="right" [id]="'source-details'" [title]="activeSource?.name || 'Source Details'" (closeModal)="closeModal()">
	<ng-container modalBody>
		<ul>
			<li convoy-list-item>
				<div class="w-1/2 text-14 font-medium">Source type</div>
				<div class="w-1/2 text-14 font-medium text-grey-40 text-right capitalize mr-24px">{{ activeSource?.type || '' | sourceValue: 'sourceType' }}</div>
			</li>

			<li convoy-list-item>
				<div class="w-1/2 text-14 font-medium">Ingester Type</div>
				<div class="w-1/2 text-14 font-medium text-grey-40 text-right capitalize mr-24px">{{ activeSource?.verifier?.type ?? '' | sourceValue: 'verifier' }}</div>
			</li>

			<li convoy-list-item *ngIf="activeSource?.provider !== ''">
				<div class="w-1/2 text-14 font-medium">Provider</div>
				<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-24px capitalize">{{ activeSource?.provider }}</div>
			</li>

			<ng-container *ngIf="activeSource?.verifier?.type == 'hmac'">
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium">Encoding</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right uppercase mr-24px">{{ activeSource?.verifier?.hmac?.encoding }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium">Algorithm</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right uppercase mr-24px">{{ activeSource?.verifier?.hmac?.hash }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium">Signature header</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-24px">{{ activeSource?.verifier?.hmac?.header }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium">Signing secret</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-24px flex justify-end">
						*******
						<convoy-copy-button [text]="activeSource?.verifier?.hmac?.secret || ''" size="md" className="ml-2px" notificationText="Signing secret has been copied to clipboard"></convoy-copy-button>
					</div>
				</li>
				<ng-container *ngIf="activeSource?.provider === 'twitter' && isDateBefore(activeSource?.provider_config?.twitter?.crc_verified_at, activeSource?.created_at)">
					<li convoy-list-item>
						<div class="w-1/2 text-14 font-medium">Last verified</div>
						<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-24px">{{ activeSource?.provider_config?.twitter?.crc_verified_at | date: 'medium' }}</div>
					</li>
				</ng-container>
			</ng-container>

			<ng-container *ngIf="activeSource?.verifier?.type == 'basic_auth'">
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium">Username</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-24px">{{ activeSource?.verifier?.basic_auth?.username }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium">Password</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-24px flex justify-end">
						*******
						<convoy-copy-button [text]="activeSource?.verifier?.basic_auth?.password || ''" size="md" className="ml-2px" notificationText="Password has been copied to clipboard"></convoy-copy-button>
					</div>
				</li>
			</ng-container>

			<ng-container *ngIf="activeSource?.verifier?.type == 'api_key'">
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium">API Key Header</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-24px">{{ activeSource?.verifier?.api_key?.header_name }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium">API Key</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right flex items-center justify-end mr-24px">
						*******
						<convoy-copy-button [text]="activeSource?.verifier?.api_key?.header_value || ''" notificationText="Api Key has been copied to clipboard" className="ml-4px"></convoy-copy-button>
					</div>
				</li>
			</ng-container>
		</ul>

		<div class="flex justify-end mt-40px mr-24px">
			<button convoy-button fill="outline" color="danger" size="sm" (click)="showDeleteSourceModal = true">
				Delete
				<svg width="18" height="18" class="ml-8px fill-danger-100">
					<use xlink:href="#delete-icon"></use>
				</svg>
			</button>
			<button convoy-button size="sm" class="ml-24px" [routerLink]="'./sources/' + activeSource?.uid">
				Edit
				<svg width="18" height="18" class="ml-8px fill-white-100">
					<use xlink:href="#edit-icon"></use>
				</svg>
			</button>
		</div>
	</ng-container>
</div>

<div convoy-modal *ngIf="shouldShowCreateSourceModal || shouldShowUpdateSourceModal" position="full" [id]="'sourceForm'" [title]="shouldShowUpdateSourceModal ? 'Update Source' : 'Create source'" (closeModal)="closeCreateSourceModal({ action: 'close' })">
	<ng-container modalBody>
		<convoy-create-source showAction="true" (onAction)="closeCreateSourceModal($event)" [action]="shouldShowUpdateSourceModal ? 'update' : 'create'"></convoy-create-source>
	</ng-container>
</div>

<div convoy-modal position="right" [title]="activeSource?.name || ''" *ngIf="activeSource?.uid && privateService.activeProjectDetails?.type === 'incoming'" (closeModal)="router.navigateByUrl('/projects/' + privateService.activeProjectDetails?.uid + '/sources')">
	<div>
		<ul class="mt-20px">
			<li convoy-list-item>
				<div class="w-1/2 text-14 font-medium ml-8px">Source type</div>
				<div class="w-1/2 text-14 font-medium text-grey-40 text-right capitalize mr-8px">{{ activeSource?.type || '' | sourceValue: 'sourceType' }}</div>
			</li>

			<li convoy-list-item>
				<div class="w-1/2 text-14 font-medium ml-8px">Ingester Type</div>
				<div class="w-1/2 text-14 font-medium text-grey-40 text-right capitalize mr-8px">{{ activeSource?.verifier?.type ?? '' | sourceValue: 'verifier' }}</div>
			</li>

			<li convoy-list-item *ngIf="activeSource?.provider !== ''">
				<div class="w-1/2 text-14 font-medium ml-8px">Provider</div>
				<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-8px capitalize">{{ activeSource?.provider }}</div>
			</li>

			<ng-container *ngIf="activeSource?.verifier?.type == 'hmac'">
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium ml-8px">Encoding</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right uppercase mr-8px">{{ activeSource?.verifier?.hmac?.encoding }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium ml-8px">Algorithm</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right uppercase mr-8px">{{ activeSource?.verifier?.hmac?.hash }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium ml-8px">Signature header</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-8px">{{ activeSource?.verifier?.hmac?.header }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium ml-8px">Signing secret</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-8px flex justify-end">
						*******
						<convoy-copy-button [text]="activeSource?.verifier?.hmac?.secret || ''" size="md" className="ml-2px" notificationText="Signing secret has been copied to clipboard"></convoy-copy-button>
					</div>
				</li>
				<ng-container *ngIf="activeSource?.provider === 'twitter' && isDateBefore(activeSource?.provider_config?.twitter?.crc_verified_at, activeSource?.created_at)">
					<li convoy-list-item>
						<div class="w-1/2 text-14 font-medium ml-8px">Last verified</div>
						<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-8px">{{ activeSource?.provider_config?.twitter?.crc_verified_at | date: 'medium' }}</div>
					</li>
				</ng-container>
			</ng-container>

			<ng-container *ngIf="activeSource?.verifier?.type == 'basic_auth'">
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium ml-8px">Username</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-8px">{{ activeSource?.verifier?.basic_auth?.username }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium ml-8px">Password</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-8px flex justify-end">
						*******
						<convoy-copy-button [text]="activeSource?.verifier?.basic_auth?.password || ''" size="md" className="ml-2px" notificationText="Password has been copied to clipboard"></convoy-copy-button>
					</div>
				</li>
			</ng-container>

			<ng-container *ngIf="activeSource?.verifier?.type == 'api_key'">
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium ml-8px">API Key Header</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right mr-8px">{{ activeSource?.verifier?.api_key?.header_name }}</div>
				</li>
				<li convoy-list-item>
					<div class="w-1/2 text-14 font-medium ml-8px">API Key</div>
					<div class="w-1/2 text-14 font-medium text-grey-40 text-right flex items-center justify-end mr-8px">
						*******
						<convoy-copy-button [text]="activeSource?.verifier?.api_key?.header_value || ''" notificationText="Api Key has been copied to clipboard" className="ml-4px"></convoy-copy-button>
					</div>
				</li>
			</ng-container>
		</ul>

		<div class="flex justify-end mt-40px mr-24px">
			<button convoy-button fill="outline" color="danger" size="sm" (click)="showDeleteSourceModal = true">
				Delete Source
				<svg width="18" height="18" class="ml-8px fill-danger-100">
					<use xlink:href="#delete-icon"></use>
				</svg>
			</button>

			<button convoy-button size="sm" class="ml-24px" [routerLink]="'./' + activeSource?.uid">
				Edit Source
				<svg width="18" height="18" class="ml-8px fill-white-100">
					<use xlink:href="#edit-icon"></use>
				</svg>
			</button>
		</div>
	</div>
</div>

<app-delete-modal *ngIf="showDeleteSourceModal" [isLoading]="isDeletingSource" [deleteText]="'delete “' + activeSource?.name + '”'" (closeModal)="showDeleteSourceModal = false" (deleteData)="deleteSource()"></app-delete-modal>

// web/ui/dashboard-react/src/app/projects_/$projectId/sources/index.tsx
import { useState } from 'react';
import { createFileRoute, Link } from '@tanstack/react-router';

import { EllipsisVertical, Copy, Trash2, PencilLine } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { DashboardLayout } from '@/components/dashboard';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
	Dialog,
	DialogClose,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from '@/components/ui/dialog';

import { useProjectStore } from '@/store';
import { transformSourceValueType } from '@/lib/pipes';
import { ensureCanAccessPrivatePages } from '@/lib/auth';
import { getUserPermissions } from '@/services/auth.service';
import * as sourcesService from '@/services/sources.service';

import warningAnimation from '../../../../../assets/img/warning-animation.gif';
import sourcesEmptyState from '../../../../../assets/img/sources-empty-state.png';

export const Route = createFileRoute('/projects_/$projectId/sources/')({
	component: RouteComponent,
	beforeLoad({ context }) {
		ensureCanAccessPrivatePages(context.auth?.getTokens().isLoggedIn);
	},
	loader: async () => {
		const perms = await getUserPermissions();
		const sources = await sourcesService.getSources();

		return {
			canManageSources: perms.includes('Sources|MANAGE'),
			sources: sources,
		};
	},
});

function RouteComponent() {
	const { project } = useProjectStore();
	const { projectId } = Route.useParams();
	const { canManageSources, sources } = Route.useLoaderData();
	const [loadedSources, setLoadedSources] = useState(sources);
	const [isDeletingSource, setIsDeletingSource] = useState(false);

	async function deleteSource(sourceId: string) {
		try {
			setIsDeletingSource(true);
			await sourcesService.deleteSource(sourceId);
			const res = await sourcesService.getSources();
			setLoadedSources(res);
		} catch (error) {
			console.error(error);
			console.log('Unable to delete source');
		} finally {
			setIsDeletingSource(false);
		}
	}

	if (loadedSources.content.length === 0) {
		return (
			<DashboardLayout showSidebar={true}>
				<div className="m-auto">
					<div className="flex flex-col items-center justify-center">
						<img
							src={sourcesEmptyState}
							alt="No subscriptions created"
							className="h-40 mb-6"
						/>
						<h2 className="font-bold mb-4 text-base text-neutral-12 text-center">
							Create your first source
						</h2>

						<p className="text-neutral-10 text-sm mb-6 max-w-[410px] text-center">
							Sources are how your webhook events are routed into the Convoy.
						</p>

						<Button
							className="mt-9 mb-9 hover:bg-new.primary-400 bg-new.primary-400 text-white-100 hover:text-white-100 px-5 py-3 text-xs"
							disabled={!canManageSources}
							asChild
						>
							<Link
								to="/projects/$projectId/sources/new"
								params={{ projectId }}
							>
								<svg
									width="22"
									height="22"
									className="scale-100"
									fill="#ffffff"
								>
									<use xlinkHref="#plus-icon"></use>
								</svg>
								Connect a source
							</Link>
						</Button>
					</div>
				</div>
			</DashboardLayout>
		);
	}

	return (
		<DashboardLayout showSidebar={true}>
			<div className="mx-auto p-6 space-y-5 w-[80vw]">
				<h1 className="text-lg font-bold text-neutral-12">Sources</h1>
				<div className="grid grid-cols-2 xl:grid-cols-3 gap-6">
					<div className="rounded-[8px] border border-dashed border-new.primary-400 flex items-center justify-center hover:shadow-[0_4px_20px_-2px_rgba(50,50,71,0.08)]">
						<Link
							activeProps={{}}
							className="h-full w-full text-center py-8 flex items-center justify-center"
							to="/projects/$projectId/sources/new"
							params={{ projectId }}
							disabled={!canManageSources}
						>
							<svg
								width="22"
								height="22"
								className="mr-2 scale-75"
								fill="#477db3"
							>
								<use xlinkHref="#plus-icon"></use>
							</svg>
							<span className="text-new.primary-400 font-medium text-xs">
								Create new source
							</span>
						</Link>
					</div>

					{loadedSources.content.map(source => {
						return project?.type == 'incoming' ? (
							<div
								className="py-5 h-fit bg-white-100 rounded-[8px] border border-neutral-4 flex flex-col"
								key={source.uid}
							>
								<div className="flex flex-col px-5">
									<p className="text-[10px] text-neutral-10">
										{source.provider ||
											transformSourceValueType(
												source.verifier.type,
												'verifier',
											)}
									</p>
									<div className="flex justify-between items-center pb-2">
										<p className="text-sm text-neutral-12">{source.name}</p>
										<Dialog>
											<DropdownMenu>
												<DropdownMenuTrigger asChild>
													<Button
														variant="ghost"
														size="icon"
														className="hover:bg-transparent focus-visible:ring-0"
													>
														<EllipsisVertical className="fill-neutral-10" />
													</Button>
												</DropdownMenuTrigger>
												<DropdownMenuContent>
													<DropdownMenuItem
														className="flex items-center gap-2 hover:bg-new.primary-50 cursor-pointer"
														onClick={() =>
															navigator.clipboard
																.writeText(`${source.uid}`)
																.then()
														}
													>
														<Copy className="stroke-neutral-9 !w-3 !h-3" />
														<span className="text-xs text-neutral-9">
															Copy ID
														</span>
													</DropdownMenuItem>
													<DropdownMenuItem className="flex items-center gap-2 hover:bg-new.primary-50 cursor-pointer" disabled={!canManageSources}>
														<PencilLine className="stroke-neutral-9 !w-3 !h-3" />
														<span className="text-xs text-neutral-9">Edit</span>
													</DropdownMenuItem>
													<DialogTrigger asChild>
														<DropdownMenuItem className="flex items-center gap-2 hover:bg-new.primary-50 cursor-pointer" disabled={!canManageSources}>
															<Trash2 className="stroke-destructive !w-3 !h-3" />
															<span className="text-xs text-destructive">
																Delete
															</span>
														</DropdownMenuItem>
													</DialogTrigger>
												</DropdownMenuContent>
											</DropdownMenu>

											<DialogContent className="sm:max-w-[432px] rounded-lg">
												<DialogHeader>
													<DialogTitle className="flex justify-center items-center">
														<img
															src={warningAnimation}
															alt="warning"
															className="w-24"
														/>
													</DialogTitle>
													<DialogDescription className="flex justify-center items-center font-medium text-new.black text-sm">
														Are you sure you want to delete this &quot;
														{source.name}&quot;?
													</DialogDescription>
												</DialogHeader>
												<div className="flex flex-col items-center space-y-4">
													<p className="text-xs text-neutral-11">
														This action is irreversible.
													</p>
													<DialogClose asChild>
														<Button
															onClick={async () =>
																await deleteSource(source.uid)
															}
															disabled={isDeletingSource || !canManageSources}
															type="submit"
															size="sm"
															className="bg-destructive text-white-100 hover:bg-destructive hover:text-white-100 focus-visible:ring-0"
														>
															Yes. Delete.
														</Button>
													</DialogClose>
												</div>
												<DialogFooter className="flex flex-row sm:justify-center items-center">
													<DialogClose
														asChild
														className="flex justify-center items-center flex-row"
													>
														<Button
															type="button"
															variant="ghost"
															className="bg-transparent hover:bg-transparent text-xs text-neutral-11 hover:text-neutral-11 font-semibold"
														>
															No. Cancel
														</Button>
													</DialogClose>
												</DialogFooter>
											</DialogContent>
										</Dialog>
									</div>
								</div>
								<hr />
								<div className="mt-5 px-5">
									<div
										className="flex items-center rounded-[22px] overflow-hidden bg-new.primary-25 gap-x-2 px-2 w-fit cursor-pointer"
										onClick={() =>
											navigator.clipboard.writeText(`${source.url}`).then()
										}
									>
										<p className="text-ellipsis overflow-hidden whitespace-nowrap text-xs">
											{source.url}
										</p>
										<Button
											size="icon"
											className="rounded-full hover:bg-transparent"
											variant={'ghost'}
											onClick={() =>
												navigator.clipboard.writeText(`${source.url}`).then()
											}
										>
											<Copy />
										</Button>
									</div>
								</div>
							</div>
						) : (
							<div
								className="w-[440px] py-5 h-fit bg-white-100 rounded-[8px] border border-neutral-4 flex flex-col"
								key={source.uid}
							>
								{source.name}
							</div>
						);
					})}
				</div>
			</div>
		</DashboardLayout>
	);
}
