// web/ui/dashboard/src/app/private/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-dashboard',
	templateUrl: './dashboard.component.html',
	styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

    constructor() {
    }

    async ngOnInit() {
    }
}

<div class="dashboard">
	<header class="dashboard--header">
		<div class="dashboard--header--container">
			<div class="logo">
				<a target="_blank" href="https://getconvoy.io" rel="noreferrer">
					<img src="/assets/img/logo.svg" alt="convoy logo" />
				</a>
			</div>

			<div>
				<a target="_blank" href="https://getconvoy.io/docs" rel="noreferrer">Go to docs</a>
				<button class="user" (click)="showDropdown = !showDropdown" *ngIf="authDetails()">
					<div>
						<div class="icon">O</div>
						<div class="name">{{ authDetails().username }}</div>
					</div>
					<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
					<div *ngIf="showDropdown" class="dropdown organisations">
						<ul>
							<li (click)="logout()">Logout</li>
						</ul>
					</div>
				</button>
			</div>
		</div>
	</header>

	<div class="dashboard--page">
		<div class="dashboard--page--head">
			<div class="filter" [ngClass]="{ 'show-calendar': showFilterCalendar }">
				<div>Filter by:</div>
				<button class="filter--button" (click)="statsPicker.open()">
					<img src="/assets/img/calendar-icon.svg" alt="calender icon" />
					<mat-date-range-input [formGroup]="statsDateRange" [rangePicker]="statsPicker">
						<input matStartDate formControlName="startDate" placeholder="Start date" />
						<input matEndDate formControlName="endDate" placeholder="End date" (dateChange)="fetchDashboardData()" />
					</mat-date-range-input>
					<mat-date-range-picker #statsPicker [disabled]="false"></mat-date-range-picker>
					<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
				</button>

				<div class="select">
					<select value="daily" [(ngModel)]="dashboardFrequency" (change)="fetchDashboardData()">
						<option value="daily">Daily</option>
						<option value="weekly">Weekly</option>
						<option value="monthly">Monthly</option>
						<option value="yearly">Yearly</option>
					</select>
				</div>
			</div>

			<div class="filter" [ngClass]="{ 'show-calendar': showFilterCalendar }">
				<div>Active Group:</div>
				<div class="select">
					<select [value]="activeGroup" [(ngModel)]="activeGroup" (change)="toggleActiveGroup()">
						<option [value]="group.uid" *ngFor="let group of groups">{{ group.name }}</option>
					</select>
				</div>
			</div>
		</div>

		<div class="dashboard--page--details">
			<div class="card dashboard--page--details--chart">
				<ul class="metrics">
					<li class="messages">
						<img src="/assets/img/message-icon.svg" alt="message icon" />
						<div class="metric">
							<div>{{ dashboardData.events_sent }}</div>
							<div>Event Sent</div>
						</div>
					</li>
					<li class="apps">
						<img src="/assets/img/apps-icon.svg" alt="apps icon" />
						<div class="metric">
							<div>{{ dashboardData.apps }}</div>
							<div>Apps</div>
						</div>
					</li>
				</ul>

				<div>
					<h3>Events Sent</h3>
					<canvas id="chart" width="400" height="200"></canvas>
				</div>
			</div>

			<div class="card has-title dashboard--page--details--credentials">
				<div class="card--title">
					<h2>Configuration</h2>
				</div>

				<ul class="card--container">
					<li class="list-item">
						<div class="list-item--label">
							Request interval (Seconds)
							<div class="list-item--item">{{ organisationDetails?.strategy?.default?.intervalSeconds }}s</div>
						</div>
					</li>

					<li class="list-item">
						<div class="list-item--label">
							Retry limit
							<div class="list-item--item">{{ organisationDetails?.strategy?.default?.retryLimit }}</div>
						</div>
					</li>

					<li class="list-item">
						<div class="list-item--label">
							Signature header
							<div class="list-item--item">{{ organisationDetails?.signature?.header }}</div>
						</div>
					</li>

					<li class="list-item">
						<div class="list-item--label">
							Signature hash
							<div class="list-item--item">{{ organisationDetails?.signature?.hash }}</div>
						</div>
					</li>
				</ul>
			</div>
		</div>

		<section class="card dashboard--logs">
			<div class="dashboard--logs--tabs">
				<div class="dashboard--logs--tabs--head tabs">
					<div class="tabs">
						<button *ngFor="let tab of tabs" (click)="toggleActiveTab(tab)" class="clear tab" [ngClass]="{ active: activeTab === tab }">
							{{ tab }}
						</button>
					</div>
				</div>

				<div class="table">
					<ng-container *ngIf="activeTab === 'events'">
						<div class="filter">
							<button
								class="filter--button date-filter-button"
								(click)="eventsFilterPicker.open()"
								[ngClass]="{ active: eventsFilterDateRange.value.startDate !== '' && eventsFilterDateRange.value.endDate !== '' }"
								(click)="showEventFilterCalendar = !showEventFilterCalendar"
							>
								<img src="/assets/img/calendar-icon.svg" alt="calender icon" />
								<mat-date-range-input [formGroup]="eventsFilterDateRange" [rangePicker]="eventsFilterPicker">
									<input matStartDate formControlName="startDate" placeholder="Start date" />
									<input matEndDate formControlName="endDate" placeholder="End date" (dateChange)="getEvents({ addToURL: true })" />
								</mat-date-range-input>
								<mat-date-range-picker #eventsFilterPicker [disabled]="false"></mat-date-range-picker>
								<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
							</button>

							<div class="select">
								<select [ngClass]="{ active: !!eventApp }" aria-label="frequency" [(ngModel)]="eventApp" (change)="getEvents({ addToURL: true })">
									<option value="">All Apps</option>
									<option [value]="app.uid" *ngFor="let app of apps?.content">
										{{ app.name }}
									</option>
								</select>
							</div>

							<button
								class="filter--button primary events-filter-clear-btn"
								(click)="clearEventFilters(activeTab)"
								[disabled]="(eventsFilterDateRange.value.startDate == '' || eventsFilterDateRange.value.endDate == '') && eventApp == ''"
								[ngClass]="{ disabled: (eventsFilterDateRange.value.startDate == '' || eventsFilterDateRange.value.endDate == '') && eventApp == '' }"
							>
								Clear Filter
							</button>
						</div>

						<hr />

						<div class="table--container smaller-table" *ngIf="displayedEvents.length > 0">
							<table id="events-table">
								<thead>
									<tr class="table--head">
										<th scope="col">Event Type</th>
										<th scope="col">App Name</th>
										<th scope="col">Created At</th>
										<th scope="col"></th>
									</tr>
								</thead>
								<tbody>
									<ng-container *ngFor="let eventGroup of displayedEvents; let i = index">
										<tr class="table--date-row">
											<td>
												<div>{{ eventGroup.date }}</div>
											</td>
											<td></td>
											<td></td>
											<td></td>
										</tr>
										<tr
											*ngFor="let event of eventGroup.events; let index = index"
											[ngClass]="{ active: event.uid === detailsItem?.uid }"
											[id]="'event' + index"
											(click)="detailsItem = event; getEventDeliveriesForSidebar(event.uid)"
										>
											<td>
												<div>
													<div class="tag">{{ event.event_type }}</div>
												</div>
											</td>
											<td class="has-long-text">
												<div>{{ event.app_metadata.title }}</div>
											</td>
											<td>
												<div>{{ event.created_at | date: 'mediumTime' }}</div>
											</td>
											<td>
												<div>
													<button class="primary clear has-icon icon-right" (click)="eventDeliveryFilteredByEventId = event.uid; openDeliveriesTab()">
														Deliveries
														<img src="../../../../assets/img/angle-arrow-right-primary.svg" alt="arrow right" />
													</button>
												</div>
											</td>
										</tr>
									</ng-container>
								</tbody>
							</table>

							<div class="table--load-more button-container center" *ngIf="events.pagination.totalPage > 1">
								<button [class]="'primary clear has-icon icon-left '" [disabled]="events.pagination.page === events.pagination.totalPage" (click)="eventsPage = eventsPage + 1; getEvents()">
									<img src="/assets/img/arrow-down-icon.svg" alt="arrow down icon" />
									Load more
								</button>
							</div>
						</div>

						<div class="empty-state table--container" *ngIf="displayedEvents.length === 0">
							<img src="/assets/img/empty-state-img.svg" alt="empty state" />
							<p>No event to show here</p>
						</div>
					</ng-container>

					<ng-container *ngIf="activeTab === 'event deliveries'">
						<div class="filter">
							<button
								class="filter--button date-filter-button"
								(click)="eventDeliveriesFilterPicker.open()"
								[ngClass]="{ active: eventDeliveriesFilterDateRange.value.startDate !== '' && eventDeliveriesFilterDateRange.value.endDate !== '' }"
								(click)="showEventFilterCalendar = !showEventFilterCalendar"
							>
								<img src="/assets/img/calendar-icon.svg" alt="calender icon" />
								<mat-date-range-input [formGroup]="eventDeliveriesFilterDateRange" [rangePicker]="eventDeliveriesFilterPicker">
									<input matStartDate formControlName="startDate" placeholder="Start date" />
									<input matEndDate formControlName="endDate" placeholder="End date" (dateChange)="getEventDeliveries({ addToURL: true })" />
								</mat-date-range-input>
								<mat-date-range-picker #eventDeliveriesFilterPicker [disabled]="false"></mat-date-range-picker>
								<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
							</button>

							<div class="dropdown">
								<button
									class="filter--button dropdown--button"
									[ngClass]="{ active: eventDeliveryFilteredByStatus }"
									(click)="showOverlay = true; showEventDeliveriesStatusDropdown = !showEventDeliveriesStatusDropdown"
								>
									<img src="/assets/img/status-filter-icon.svg" alt="status filter icon" />
									<span>{{ eventDeliveryFilteredByStatus || 'Status' }}</span>
									<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
								</button>
								<div class="dropdown--list" *ngIf="showEventDeliveriesStatusDropdown">
									<div class="dropdown--list--item" *ngFor="let status of eventDeliveryStatuses">
										<input
											type="radio"
											name="status"
											[value]="status"
											[(ngModel)]="eventDeliveryFilteredByStatus"
											[id]="status"
											(change)="showOverlay = false; showEventDeliveriesStatusDropdown = false; getEventDeliveries({ addToURL: true })"
										/>
										<label [for]="status">{{ status || 'None' }}</label>
									</div>
								</div>
							</div>

							<div class="select">
								<select [ngClass]="{ active: !!eventDeliveriesApp }" aria-label="frequency" [(ngModel)]="eventDeliveriesApp" (change)="getEventDeliveries({ addToURL: true })">
									<option value="">All Apps</option>
									<option [value]="app.uid" *ngFor="let app of apps?.content">
										{{ app.name }}
									</option>
								</select>
							</div>

							<div class="filter--button event-button active" *ngIf="eventDeliveryFilteredByEventId !== ''">
								Event Filtered
								<button class="primary clear has-icon" (click)="eventDeliveryFilteredByEventId = ''; getEventDeliveries()">
									<img src="../../../../assets/img/close-icon.svg" alt="close icon" />
								</button>
							</div>

							<button
								class="filter--button primary events-filter-clear-btn"
								(click)="clearEventFilters(activeTab)"
								[disabled]="
									(eventDeliveriesFilterDateRange.value.startDate == '' || eventDeliveriesFilterDateRange.value.endDate == '') &&
									eventDeliveriesApp == '' &&
									eventDeliveryFilteredByEventId == '' &&
									!eventDeliveryFilteredByStatus
								"
							>
								Clear Filter
							</button>
						</div>

						<hr />

						<div class="table--actions button-container left">
							<button class="primary clear has-icon icon-left hover" (click)="refreshTables()">
								<img src="../../../../assets/img/refresh-icon-2.svg" alt="refresh icon" />
								Refresh
							</button>
							<button class="primary clear has-icon icon-left hover" (click)="batchRetryEvent()" [disabled]="selectedEventsFromEventDeliveriesTable.length <= 0">
								<img src="../../../../assets/img/retry-icon.svg" alt="retry icon" />
								Bulk Retry
							</button>
						</div>

						<div class="table--container" *ngIf="displayedEventDeliveries.length > 0">
							<table id="event-deliveries-table">
								<thead>
									<tr class="table--head">
										<th scope="col" class="checkbox">
											<div class="checkbox"><input type="checkbox" name="eventDeliveryTable" id="eventDeliveryTable" (change)="checkAllCheckboxes($event)" /></div>
											Status
										</th>
										<th scope="col">Event Type</th>
										<th scope="col">Attempts</th>
										<th scope="col">Created At</th>
										<th scope="col"></th>
									</tr>
								</thead>
								<tbody>
									<ng-container *ngFor="let eventDeliveriesGroup of displayedEventDeliveries; let i = index">
										<tr class="table--date-row">
											<td>
												<div>{{ eventDeliveriesGroup.date }}</div>
											</td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
										</tr>
										<tr
											*ngFor="let event of eventDeliveriesGroup.events; let index = index"
											[ngClass]="{ active: event.uid === detailsItem?.uid }"
											[id]="'event' + index"
											(click)="detailsItem = event; getDelieveryAttempts(event.uid)"
										>
											<td>
												<div class="checkbox has-retry">
													<img *ngIf="event.metadata.num_trials > event.metadata.retry_limit" src="/assets/img/retry-icon.svg" alt="retry icon" title="manually retried" />
													<input type="checkbox" [name]="'event' + index" id="event" [value]="event.uid" (change)="checkEventDeliveryBox($event)" />
													<div [class]="'tag tag--' + event.status">{{ event.status }}</div>
												</div>
											</td>
											<td>
												<div>{{ event.event_metadata.name }}</div>
											</td>
											<td>
												<div>{{ event.metadata?.num_trials }}</div>
											</td>
											<td>
												<div>{{ event.created_at | date: 'mediumTime' }}</div>
											</td>
											<td>
												<div>
													<button
														[disabled]="event.status === 'Success' || event.status === 'Scheduled'"
														[class]="'primary has-icon icon-left ' + (event.status === 'Success' || event.status === 'Scheduled' ? 'disabled' : '')"
														(click)="retryEvent({ e: $event, index: this.index, eventDeliveryId: event.uid })"
													>
														<img src="/assets/img/refresh-icon.svg" alt="refresh icon" />
														Retry
													</button>
												</div>
											</td>
										</tr>
									</ng-container>
								</tbody>
							</table>

							<div class="table--load-more button-container center" *ngIf="eventDeliveries.pagination.totalPage > 1">
								<button [class]="'primary clear has-icon icon-left'" [disabled]="eventDeliveries.pagination.page === eventDeliveries.pagination.totalPage" (click)="loadMoreEventDeliveries()">
									<img src="/assets/img/arrow-down-icon.svg" alt="arrow down icon" />
									Load more
								</button>
							</div>
						</div>

						<div class="empty-state table--container" *ngIf="displayedEventDeliveries.length === 0">
							<img src="/assets/img/empty-state-img.svg" alt="empty state" />
							<p>No event to show here</p>
						</div>
					</ng-container>

					<div class="table--container smaller-table" *ngIf="apps && apps.content.length > 0 && activeTab === 'apps'">
						<table>
							<thead>
								<tr class="table--head">
									<th scope="col">Name</th>
									<th scope="col">Created</th>
									<th scope="col">Updated</th>
									<th scope="col">Events</th>
									<th scope="col">Endpoints</th>
									<th scope="col"></th>
								</tr>
							</thead>
							<tbody>
								<tr *ngFor="let app of apps?.content" [ngClass]="{ active: app.uid === detailsItem?.uid }" (click)="detailsItem = app">
									<td class="has-long-text">
										<div>{{ app.name }}</div>
									</td>
									<td>
										<div>{{ app.created_at | date }}</div>
									</td>
									<td>
										<div>{{ app.updated_at | date }}</div>
									</td>
									<td>
										<div>{{ app.events }}</div>
									</td>
									<td>
										<div>{{ app.endpoints.length }}</div>
									</td>
									<td>
										<div>
											<button
												[disabled]="app.events <= 0"
												title="view events"
												[class]="'primary has-icon icon-left'"
												(click)="toggleActiveTab('events'); getEvents({ addToURL: true, appId: app.uid })"
											>
												<img src="/assets/img/view-events-icon.svg" alt="view events icon" />
												Events
											</button>
										</div>
									</td>
								</tr>
							</tbody>
						</table>

						<div class="table--load-more button-container margin-top center" *ngIf="apps?.pagination && apps.pagination.totalPage > 1">
							<button
								[class]="'primary clear has-icon icon-left ' + (apps.pagination.page === apps.pagination.totalPage ? 'disabled' : '')"
								[disabled]="apps.pagination.page === apps.pagination.totalPage"
							>
								<img src="/assets/img/arrow-down-icon.svg" alt="arrow down icon" />
								Load more
							</button>
						</div>
					</div>

					<div class="empty-state" *ngIf="apps?.content?.length === 0 && activeTab === 'apps'">
						<img src="/assets/img/empty-state-img.svg" alt="empty state" />
						<p>No app to show here</p>
					</div>
				</div>
			</div>

			<div class="dashboard--logs--details">
				<ng-container *ngIf="detailsItem">
					<h3>Details</h3>
					<ul class="dashboard--logs--details--meta" *ngIf="activeTab === 'apps' || activeTab === 'event deliveries'">
						<ng-container *ngIf="activeTab === 'event deliveries'">
							<li class="list-item-inline">
								<div class="list-item-inline--label">IP Address</div>
								<div class="list-item-inline--item color">{{ eventDeliveryAtempt?.ip_address || '-' }}</div>
							</li>
							<li class="list-item-inline">
								<div class="list-item-inline--label">HTTP Status</div>
								<div class="list-item-inline--item">{{ eventDeliveryAtempt?.http_status || '-' }}</div>
							</li>
							<li class="list-item-inline">
								<div class="list-item-inline--label">API Version</div>
								<div class="list-item-inline--item color">{{ eventDeliveryAtempt?.api_version || '-' }}</div>
							</li>
							<li class="list-item-inline">
								<div class="list-item-inline--label">Endpoint</div>
								<div class="list-item-inline--item color" [title]="detailsItem.endpoint?.target_url">
									{{ detailsItem.endpoint?.target_url }}
								</div>
							</li>
							<li class="list-item-inline" *ngIf="detailsItem.metadata?.num_trials < detailsItem.metadata?.retry_limit && detailsItem.status !== 'Success'">
								<div class="list-item-inline--label">Next Retry</div>
								<div class="list-item-inline--item color">
									{{ detailsItem.metadata?.next_send_time | date: 'mediumTime' }}
								</div>
							</li>
							<li class="list-item-inline">
								<div class="list-item-inline--label">App Name</div>
								<div class="list-item-inline--item color">
									{{ detailsItem.app_metadata?.title }}
								</div>
							</li>
						</ng-container>
						<li class="list-item-inline" *ngIf="activeTab === 'apps'">
							<div class="list-item-inline--label">Support Email</div>
							<div class="list-item-inline--item">{{ detailsItem?.support_email || '-' }}</div>
						</li>
					</ul>

					<ul class="tabs" *ngIf="activeTab === 'event deliveries'">
						<li *ngFor="let tab of eventDetailsTabs" [class]="'tab ' + (eventDetailsActiveTab === tab.id ? 'active' : '')">
							<button class="primary outline" (click)="eventDetailsActiveTab = tab.id">{{ tab.label }}</button>
						</li>
					</ul>

					<div class="dashboard--logs--details--req-res" *ngIf="activeTab === 'events' || activeTab === 'event deliveries'">
						<div [class]="'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'data' ? 'show' : '')">
							<h3>Event</h3>
							<app-shared language="json" [code]="getCodeSnippetString(activeTab === 'events' ? 'event' : 'event_delivery')"></app-shared>
						</div>

						<div [class]="'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'response' ? 'show' : '')">
							<h3>Header</h3>
							<app-shared language="json" [code]="getCodeSnippetString('res_head')"></app-shared>

							<h3>Body</h3>
							<app-shared language="json" [code]="getCodeSnippetString('res_body')"></app-shared>
						</div>

						<div [class]="'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'request' ? 'show' : '')">
							<h3>Header</h3>
							<app-shared language="json" [code]="getCodeSnippetString('req')"></app-shared>
						</div>
					</div>

					<ng-container *ngIf="activeTab === 'events'">
						<h4>Deliveries Overview</h4>
						<ul class="dashboard--logs--details--endpoints inline">
							<li *ngFor="let delivery of sidebarEventDeliveries">
								<div [class]="'tag tag--' + delivery.status">{{ delivery.status }}</div>
								<div class="url" [title]="delivery.endpoint.target_url">
									{{ delivery.endpoint.target_url }}
								</div>
							</li>
						</ul>
					</ng-container>

					<ng-container *ngIf="activeTab === 'apps'">
						<h4>App Event Endpoints</h4>
						<ul class="dashboard--logs--details--endpoints">
							<ng-container *ngIf="detailsItem?.endpoints">
								<li *ngFor="let endpoint of detailsItem.endpoints">
									<h5>{{ endpoint.description }}</h5>
									<p>
										<img src="/assets/img/link-icon.svg" alt="link icon" />
										{{ endpoint.target_url }}
									</p>
									<div class="events">
										<div class="tag" *ngFor="let event of endpoint.events">{{ event == '*' ? 'all events' : event }}</div>
									</div>
								</li>
							</ng-container>
						</ul>
					</ng-container>
				</ng-container>
			</div>
		</section>
	</div>
</div>

<div class="overlay" *ngIf="showOverlay" (click)="showOverlay = false; showEventDeliveriesStatusDropdown = false"></div>

// web/components/react/src/pages/dashboard/index.js
import React, { useEffect, useState, useCallback } from 'react';
import ArrowDownIcon from '../../assets/img/arrow-down-icon.svg';
import AppsIcon from '../../assets/img/apps-icon.svg';
import MessageIcon from '../../assets/img/message-icon.svg';
import RefreshIcon from '../../assets/img/refresh-icon.svg';
import CalendarIcon from '../../assets/img/calendar-icon.svg';
import LinkIcon from '../../assets/img/link-icon.svg';
import AngleArrowDownIcon from '../../assets/img/angle-arrow-down.svg';
import ConvoyLogo from '../../assets/img/logo.svg';
import RetryIcon from '../../assets/img/retry-icon.svg';
import EmptyStateImage from '../../assets/img/empty-state-img.svg';
import ViewEventsIcon from '../../assets/img/view-events-icon.svg';
import Chart from 'chart.js/auto';
import { DateRange } from 'react-date-range';
import { request } from '../../services/https.service';
import './style.scss';
import 'react-date-range/dist/styles.css';
import 'react-date-range/dist/theme/default.css';
import { showNotification } from '../../components/app-notification';
import { getDate, getTime, logout } from '../../helpers/common.helper';
import Prism from 'prismjs';
import '../../scss/prism.scss';
import '../../helpers/prism-line-plugin';

const moment = require('moment');
const authDetails = localStorage.getItem('CONVOY_AUTH');

function DashboardPage() {
	const [dashboardData, setDashboardData] = useState({ apps: 0, messages: 0, messageData: [] });
	const [showDropdown, toggleShowDropdown] = useState(false);
	const [apps, setAppsData] = useState({ content: [], pagination: { page: 1, totalPage: 0 } });
	const [events, setEventsData] = useState({ content: [], pagination: { page: 1, totalPage: 0 } });
	const [displayedEvents, setDisplayedEvents] = useState([]);
	const [tabs] = useState(['events', 'apps']);
	const [activeTab, setActiveTab] = useState('events');
	const [eventDetailsTabs] = useState([
		{ id: 'data', label: 'Event Data' },
		{ id: 'response', label: 'Response Header' },
		{ id: 'request', label: 'Request Header' }
	]);
	const [eventDetailsActiveTab, setEventDetailsActiveTab] = useState('data');
	const [showFilterCalendar, toggleShowFilterCalendar] = useState(false);
	const [eventAppFilterActive, toggleEventAppFilterActive] = useState(false);
	const [eventDateFilterActive, toggleEventDateFilterActive] = useState(false);
	const [showEventFilterCalendar, toggleShowEventFilterCalendar] = useState(false);
	const [eventApp, setEventApp] = useState('');
	const [OrganisationDetails, setOrganisationDetails] = useState({
		database: {
			dsn: ''
		},
		queue: {
			type: '',
			redis: {
				dsn: ''
			}
		},
		server: {
			http: {
				port: 0
			}
		},
		strategy: {
			type: '',
			default: {
				intervalSeconds: 0,
				retryLimit: 0
			}
		},
		signature: {
			header: '',
			hash: ''
		}
	});
	const [eventDeliveryAtempt, setEventDeliveryAtempt] = useState({
		ip_address: '',
		http_status: '',
		api_version: '',
		updated_at: 0,
		deleted_at: 0,
		response_data: '',
		response_http_header: {},
		request_http_header: {}
	});
	const [detailsItem, setDetailsItem] = useState();
	const [filterFrequency, setFilterFrequency] = useState('');
	const [filterDates, setFilterDates] = useState([
		{
			startDate: new Date(new Date().setDate(new Date().getDate() - 30)),
			endDate: new Date(),
			key: 'selection'
		}
	]);
	const [eventFilterDates, setEventFilterDates] = useState([
		{
			startDate: new Date(),
			endDate: new Date(),
			key: 'selection'
		}
	]);

	const [options] = useState({
		plugins: {
			legend: {
				display: false
			}
		},
		scales: {
			xAxis: {
				display: true,
				grid: {
					display: false
				}
			}
		}
	});

	const setEventsDisplayed = events => {
		const dateCreateds = events.map(event => getDate(event.created_at));
		const uniqueDateCreateds = [...new Set(dateCreateds)];
		const displayedEvents = [];
		uniqueDateCreateds.forEach(eventDate => {
			const filteredEventDate = events.filter(event => getDate(event.created_at) === eventDate);
			const eventsItem = { date: eventDate, events: filteredEventDate };
			displayedEvents.push(eventsItem);
		});
		setDisplayedEvents(displayedEvents);
	};

	const setDateForFilter = ({ startDate, endDate }) => {
		if (!endDate && !startDate) return { startDate: '', endDate: '' };
		startDate = String(moment(`${moment(startDate).format('YYYY[-]MM[-]DD')} 00:00:00`).toISOString(true)).split('.')[0];
		endDate = String(moment(`${moment(endDate).format('YYYY[-]MM[-]DD')} 23:59:59`).toISOString(true)).split('.')[0];
		return { startDate, endDate };
	};

	const getEvents = useCallback(
		async ({ page, eventsData, dates }) => {
			toggleShowEventFilterCalendar(false);

			if (!dates) dates = [{ startDate: null, endDate: null }];

			const dateFromPicker = dates[0];
			const { startDate, endDate } = setDateForFilter(dateFromPicker);

			try {
				const eventsResponse = await (
					await request({
						url: `/events?sort=AESC&page=${page || 1}&perPage=20&startDate=${startDate}&endDate=${endDate}&appId=${eventApp}`,
						method: 'GET'
					})
				).data;

				if (eventsData && eventsData?.pagination?.next === page) {
					const content = [...eventsData.content, ...eventsResponse.data.content];
					const pagination = eventsResponse.data.pagination;
					setEventsData({ content, pagination });
					setEventsDisplayed(content);
					return;
				}

				setEventsData(eventsResponse.data);
				setEventsDisplayed(eventsResponse.data.content);
			} catch (error) {
				return error;
			}
		},
		[eventApp]
	);

	const getApps = useCallback(async ({ page, appsData }) => {
		try {
			const appsResponse = await (
				await request({
					url: `/apps?sort=AESC&page=${page || 1}&perPage=10`
				})
			).data;

			if (appsData?.pagination?.next === page) {
				const content = [...appsData.content, ...appsResponse.data.content];
				const pagination = appsResponse.data.pagination;
				setAppsData({ content, pagination });
				return;
			}
			setAppsData(appsResponse.data);
		} catch (error) {
			return error;
		}
	}, []);

	const getDelieveryAttempts = async eventId => {
		try {
			const deliveryAttemptsResponse = await (
				await request({
					url: `/events/${eventId}/deliveryattempts`
				})
			).data;
			setEventDeliveryAtempt(deliveryAttemptsResponse.data[deliveryAttemptsResponse.data.length - 1]);
			Prism.highlightAll();
		} catch (error) {
			return error;
		}
	};

	const retryEvent = async ({ eventId, appId, e, index }) => {
		e.stopPropagation();
		const retryButton = document.querySelector(`#event${index} button`);
		retryButton.classList.add(['spin', 'disable_action']);
		retryButton.disabled = true;

		try {
			await (
				await request({
					method: 'PUT',
					url: `/apps/${appId}/events/${eventId}/resend`
				})
			).data;
			showNotification({ message: 'Retry Request Sent' });
			retryButton.classList.remove(['spin', 'disable_action']);
			retryButton.disabled = false;
			getEvents({ page: events.pagination.page });
		} catch (error) {
			showNotification({ message: error.response.data.message });
			retryButton.classList.remove(['spin', 'disable_action']);
			retryButton.disabled = false;
			return error;
		}
	};

	const toggleActiveTab = tab => {
		setActiveTab(tab);
		setDetailsItem();
		setEventDeliveryAtempt({
			ip_address: '',
			http_status: '',
			api_version: '',
			updated_at: 0,
			deleted_at: 0
		});
	};

	useEffect(() => {
		const getOrganisationDetails = async () => {
			try {
				const organisationDetailsResponse = await (
					await request({
						url: `/dashboard/config`
					})
				).data;
				setOrganisationDetails(organisationDetailsResponse.data);
			} catch (error) {
				return error;
			}
		};

		const fetchDashboardData = async () => {
			try {
				const { startDate, endDate } = setDateForFilter(filterDates[0]);
				const dashboardResponse = await request({
					url: `/dashboard/summary?startDate=${startDate}&endDate=${endDate}&type=${filterFrequency || 'daily'}`
				});
				setDashboardData(dashboardResponse.data.data);

				const chartData = dashboardResponse.data.data.message_data;
				const labels = [0, ...chartData.map(label => label.data.date)];
				const dataSet = [0, ...chartData.map(label => label.count)];
				const data = {
					labels,
					datasets: [
						{
							data: dataSet,
							fill: false,
							borderColor: '#477DB3',
							tension: 0.5,
							yAxisID: 'yAxis',
							xAxisID: 'xAxis'
						}
					]
				};

				if (!Chart.getChart('chart') || !Chart.getChart('chart')?.canvas) {
					new Chart(document.getElementById('chart'), { type: 'line', data, options });
				} else {
					const currentChart = Chart.getChart('chart');
					currentChart.data.labels = labels;
					currentChart.data.datasets[0].data = dataSet;
					currentChart.update();
				}
			} catch (error) {
				return error;
			}
		};

		fetchDashboardData();
		getOrganisationDetails();
		getApps({ page: 1 });
		getEvents({ page: 1 });
	}, [options, activeTab, filterDates, filterFrequency, getEvents, getApps]);

	return (
		<div className="dashboard">
			<header className="dashboard--header">
				<div className="dashboard--header--container">
					<div className="logo">
						<img src={ConvoyLogo} alt="convoy logo" />
					</div>

					<div>
						<a target="_blank" href="https://getconvoy.io/docs" rel="noreferrer">
							Go to docs
						</a>
						{authDetails && (
							<button className="user" onClick={() => toggleShowDropdown(!showDropdown)}>
								<div>
									<div className="icon">O</div>
									<div className="name">{JSON.parse(authDetails).username}</div>
								</div>
								<img src={AngleArrowDownIcon} alt="arrow down icon" />
								{showDropdown && (
									<div className="dropdown organisations">
										<ul>
											<li onClick={() => logout()}>Logout</li>
										</ul>
									</div>
								)}
							</button>
						)}
					</div>
				</div>
			</header>

			<div className="dashboard--page">
				<div className={`filter ${showFilterCalendar ? 'show-calendar' : ''}`}>
					<div>Filter by:</div>
					<button className="filter--button" onClick={() => toggleShowFilterCalendar(!showFilterCalendar)}>
						<img src={CalendarIcon} alt="calender icon" />
						<div>
							{getDate(filterDates[0].startDate)} - {getDate(filterDates[0].endDate)}
						</div>
						<img src={AngleArrowDownIcon} alt="arrow down icon" />
					</button>
					<DateRange onChange={item => setFilterDates([item.selection])} moveRangeOnFirstSelection={false} ranges={filterDates} />

					<div className="select">
						<select value={filterFrequency} onChange={event => setFilterFrequency(event.target.value)} aria-label="frequency">
							<option value="daily">Daily</option>
							<option value="weekly">Weekly</option>
							<option value="monthly">Monthly</option>
							<option value="yearly">Yearly</option>
						</select>
					</div>
				</div>

				<div className="dashboard--page--details">
					<div className="card dashboard--page--details--chart">
						<ul>
							<li className="messages">
								<img src={MessageIcon} alt="message icon" />
								<div className="metric">
									<div>{dashboardData.messages_sent}</div>
									<div>{dashboardData.messages_sent === 1 ? 'Event' : 'Events'} Sent</div>
								</div>
							</li>
							<li className="apps">
								<img src={AppsIcon} alt="apps icon" />
								<div className="metric">
									<div>{dashboardData.apps}</div>
									<div>{dashboardData.apps === 1 ? 'App' : 'Apps'}</div>
								</div>
							</li>
						</ul>

						<div>
							<h3>Events Sent</h3>
							<canvas id="chart" width="400" height="200"></canvas>
						</div>
					</div>

					<div className="card has-title dashboard--page--details--credentials">
						<div className="card--title">
							<h2>Configuration</h2>
						</div>

						<ul className="card--container">
							<li className="list-item">
								<div className="list-item--label">
									Request interval Seconds
									<div className="list-item--item">{OrganisationDetails.strategy.default.intervalSeconds}s</div>
								</div>
							</li>

							<li className="list-item">
								<div className="list-item--label">
									Retry limit
									<div className="list-item--item">{OrganisationDetails.strategy.default.retryLimit}</div>
								</div>
							</li>

							<li className="list-item">
								<div className="list-item--label">
									Signature header
									<div className="list-item--item">{OrganisationDetails.signature.header}</div>
								</div>
							</li>

							<li className="list-item">
								<div className="list-item--label">
									Signature hash
									<div className="list-item--item">{OrganisationDetails.signature.hash}</div>
								</div>
							</li>
						</ul>
					</div>
				</div>

				<section className="card dashboard--logs">
					<div className="dashboard--logs--tabs">
						<div className="dashboard--logs--tabs--head tabs">
							<div className="tabs">
								{tabs.map((tab, index) => (
									<button onClick={() => toggleActiveTab(tab)} key={index} className={'clear tab ' + (activeTab === tab ? 'active' : '')}>
										{tab}
									</button>
								))}
							</div>

							{activeTab === 'events' && (
								<div className="filter">
									<button className={'filter--button ' + (eventDateFilterActive ? 'active' : '')} onClick={() => toggleShowEventFilterCalendar(!showEventFilterCalendar)}>
										<img src={CalendarIcon} alt="calender icon" />
										<div>Date</div>
										<img src={AngleArrowDownIcon} alt="arrow down icon" />
									</button>
									{showEventFilterCalendar && (
										<div className="date-filter--container">
											<DateRange onChange={item => setEventFilterDates([item.selection])} editableDateInputs={true} moveRangeOnFirstSelection={false} ranges={eventFilterDates} />
											<div className="button-container">
												<button
													className="primary"
													onClick={() => {
														getEvents({ dates: eventFilterDates });
														toggleEventDateFilterActive(true);
													}}>
													Apply
												</button>
												<button
													className="primary outline"
													onClick={() => {
														getEvents({ page: 1 });
														toggleEventDateFilterActive(false);
													}}>
													Clear
												</button>
											</div>
										</div>
									)}

									<div className="select">
										<select
											value={eventApp}
											className={eventAppFilterActive ? 'active' : ''}
											onChange={event => {
												setEventApp(event.target.value);
												toggleEventAppFilterActive(!!event.target.value);
											}}
											aria-label="frequency">
											<option value="">All Apps</option>
											{apps.content.map((app, index) => (
												<option key={index} value={app.uid}>
													{app.name}
												</option>
											))}
										</select>
									</div>
								</div>
							)}
						</div>

						<div className="table">
							{displayedEvents.length > 0 && activeTab && activeTab === 'events' && (
								<div>
									<table>
										<thead>
											<tr className="table--head">
												<th scope="col">Status</th>
												<th scope="col">Event Type</th>
												<th scope="col">Attempts</th>
												<th scope="col">Next Retry</th>
												<th scope="col">Created At</th>
												<th scope="col">Next Entry</th>
											</tr>
										</thead>
										<tbody>
											{displayedEvents.map((eventGroup, index) => (
												<React.Fragment key={'eventGroup' + index}>
													<tr className="table--date-row">
														<td>
															<div>{eventGroup.date}</div>
														</td>
														<td></td>
														<td></td>
														<td></td>
														<td></td>
														<td></td>
													</tr>
													{eventGroup.events.map((event, index) => (
														<tr
															key={index}
															onClick={() => {
																Prism.highlightAll();
																setDetailsItem(event);
																getDelieveryAttempts(event.uid);
															}}
															className={event.uid === detailsItem?.uid ? 'active' : ''}
															id={'event' + index}>
															<td>
																<div className="has-retry">
																	{event.metadata.num_trials > event.metadata.retry_limit && <img src={RetryIcon} alt="retry icon" title="manual retried" />}
																	<div className={'tag tag--' + event.status}>{event.status}</div>
																</div>
															</td>
															<td>
																<div>{event.event_type}</div>
															</td>
															<td>
																<div>{event.metadata.num_trials}</div>
															</td>
															<td>
																<div>{event.metadata.num_trials < event.metadata.retry_limit && event.status !== 'Success' ? getTime(event.metadata.next_send_time) : '-'}</div>
															</td>
															<td>
																<div>{getTime(event.created_at)}</div>
															</td>
															<td>
																<div>
																	<button
																		disabled={event.status === 'Success' || event.status === 'Scheduled'}
																		className={'primary has-icon icon-left ' + (event.status === 'Success' || event.status === 'Scheduled' ? 'disable_action' : '')}
																		onClick={e => retryEvent({ eventId: event.uid, appId: event.app_id, e, index })}>
																		<img src={RefreshIcon} alt="refresh icon" />
																		Retry
																	</button>
																</div>
															</td>
														</tr>
													))}
												</React.Fragment>
											))}
										</tbody>
									</table>

									{events.pagination.totalPage > 1 && (
										<div className=" table--load-more button-container margin-top center">
											<button
												className={'primary clear has-icon icon-left ' + (events.pagination.page === events.pagination.totalPage ? 'disable_action' : '')}
												disabled={events.pagination.page === events.pagination.totalPage}
												onClick={() => getEvents({ page: events.pagination.page + 1, eventsData: events, dates: eventDateFilterActive ? eventFilterDates : null })}>
												<img src={ArrowDownIcon} alt="arrow down icon" />
												Load more
											</button>
										</div>
									)}
								</div>
							)}

							{activeTab === 'events' && displayedEvents.length === 0 && (
								<div className="empty-state">
									<img src={EmptyStateImage} alt="empty state" />
									<p>No {activeTab} to show here</p>
								</div>
							)}

							{apps.content.length > 0 && activeTab && activeTab === 'apps' && (
								<div>
									<table>
										<thead>
											<tr className="table--head">
												<th scope="col">Name</th>
												<th scope="col">Created</th>
												<th scope="col">Updated</th>
												<th scope="col">Events No</th>
												<th scope="col">Endpoints No</th>
												<th scope="col"></th>
											</tr>
										</thead>
										<tbody>
											{apps.content.map((app, index) => (
												<tr key={index} onClick={() => setDetailsItem(app)} className={app.uid === detailsItem?.uid ? 'active' : ''}>
													<td>
														<div>{app.name}</div>
													</td>
													<td>
														<div>{getDate(app.created_at)}</div>
													</td>
													<td>
														<div>{getDate(app.updated_at)}</div>
													</td>
													<td>
														<div>{app.events}</div>
													</td>
													<td>
														<div>{app.endpoints.length}</div>
													</td>
													<td>
														<div>
															<button
																disabled={app.events <= 0}
																title="view events"
																className={'primary has-icon icon-left ' + (app.events <= 0 ? 'disable_action' : '')}
																onClick={e => {
																	e.stopPropagation();
																	setEventApp(app.uid);
																	toggleActiveTab('events');
																	toggleEventAppFilterActive(true);
																}}>
																<img src={ViewEventsIcon} alt="view events icon" />
																Events
															</button>
														</div>
													</td>
												</tr>
											))}
										</tbody>
									</table>

									{apps.pagination.totalPage > 1 && (
										<div className="table--load-more button-container margin-top center">
											<button
												className={'primary clear has-icon icon-left ' + (apps.pagination.page === apps.pagination.totalPage ? 'disable_action' : '')}
												disabled={apps.pagination.page === apps.pagination.totalPage}
												onClick={() => getApps({ page: apps.pagination.page + 1, appsData: apps })}>
												<img src={ArrowDownIcon} alt="arrow down icon" />
												Load more
											</button>
										</div>
									)}
								</div>
							)}

							{apps.content.length === 0 && activeTab === 'apps' && (
								<div className="empty-state">
									<img src={EmptyStateImage} alt="empty state" />
									<p>No eve to show here</p>
								</div>
							)}
						</div>
					</div>

					{detailsItem && (
						<div className="dashboard--logs--details">
							<h3>Details</h3>
							<ul className="dashboard--logs--details--meta">
								{eventDeliveryAtempt && eventDeliveryAtempt.ip_address && (
									<React.Fragment>
										<li>
											<div className="label">IP Address</div>
											<div className="value color">{eventDeliveryAtempt.ip_address}</div>
										</li>
										<li>
											<div className="label">HTTP Status</div>
											<div className="value">{eventDeliveryAtempt.http_status}</div>
										</li>
										<li>
											<div className="label">API Version</div>
											<div className="value color">{eventDeliveryAtempt.api_version}</div>
										</li>
									</React.Fragment>
								)}
								<li>
									<div className="label">Date Created</div>
									<div className="value">{getDate(detailsItem.created_at)}</div>
								</li>
								<li>
									<div className="label">Last Updated</div>
									<div className="value">{getDate(detailsItem.updated_at)}</div>
								</li>
								{detailsItem.support_email && (
									<li>
										<div className="label">Support Email</div>
										<div className="value">{detailsItem.support_email}</div>
									</li>
								)}
							</ul>

							{activeTab === 'events' && (
								<ul className="tabs">
									{eventDetailsTabs.map(tab => (
										<li className={'tab ' + (eventDetailsActiveTab === tab.id ? 'active' : '')} key={tab.id}>
											<button className="primary outline" onClick={() => setEventDetailsActiveTab(tab.id)}>
												{tab.label}
											</button>
										</li>
									))}
								</ul>
							)}

							{activeTab === 'events' && (
								<div className="dashboard--logs--details--req-res">
									<div className={'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'data' ? 'show' : '')}>
										<pre className="line-numbers">
											<code className="lang-javascript">{detailsItem.data ? JSON.stringify(detailsItem.data, null, 4).replaceAll(/"([^"]+)":/g, '$1:') : ''}</code>
										</pre>
									</div>

									<div className={'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'response' ? 'show' : '')}>
										<h3>Body</h3>
										<pre className="line-numbers">
											<code className="lang-html">{eventDeliveryAtempt?.response_data ? eventDeliveryAtempt.response_data : ''}</code>
										</pre>

										<h3>Header</h3>
										<pre className="line-numbers">
											<code className="lang-javascript">
												{eventDeliveryAtempt?.response_http_header
													? JSON.stringify(eventDeliveryAtempt.response_http_header, null, 4).replaceAll(/"([^"]+)":/g, '$1:')
													: 'No response header was sent'}
											</code>
										</pre>
									</div>

									<div className={'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'request' ? 'show' : '')}>
										<h3>Header</h3>
										<pre className="line-numbers">
											<code className="lang-javascript">
												{eventDeliveryAtempt?.request_http_header
													? JSON.stringify(eventDeliveryAtempt.request_http_header, null, 4).replaceAll(/"([^"]+)":/g, '$1:')
													: 'No request header was sent'}
											</code>
										</pre>
									</div>
								</div>
							)}

							{activeTab === 'apps' && (
								<React.Fragment>
									<h4>App Event Endpoints</h4>
									<ul className="dashboard--logs--details--endpoints">
										{detailsItem.endpoints &&
											detailsItem.endpoints.map((endpoint, index) => (
												<li key={index}>
													<h5>{endpoint.description}</h5>
													<p>
														<img src={LinkIcon} alt="link icon" />
														{endpoint.target_url}
													</p>
												</li>
											))}
									</ul>
								</React.Fragment>
							)}
						</div>
					)}
				</section>
			</div>
		</div>
	);
}

export { DashboardPage };
