// web/ui/dashboard/src/app/private/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-dashboard',
	templateUrl: './dashboard.component.html',
	styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

    constructor() {
    }

    async ngOnInit() {
    }
}

<div class="dashboard">
	<header class="dashboard--header">
		<div class="dashboard--header--container">
			<div class="logo">
				<a target="_blank" href="https://getconvoy.io" rel="noreferrer">
					<img src="/assets/img/logo.svg" alt="convoy logo" />
				</a>
			</div>

			<div>
				<a target="_blank" href="https://getconvoy.io/docs" rel="noreferrer">Go to docs</a>
				<button class="user" (click)="showDropdown = !showDropdown" *ngIf="authDetails()">
					<div>
						<div class="icon">O</div>
						<div class="name">{{ authDetails().username }}</div>
					</div>
					<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
					<div *ngIf="showDropdown" class="dropdown organisations">
						<ul>
							<li (click)="logout()">Logout</li>
						</ul>
					</div>
				</button>
			</div>
		</div>
	</header>

	<div class="dashboard--page">
		<div class="dashboard--page--head">
			<div class="filter" [ngClass]="{ 'show-calendar': showFilterCalendar }">
				<div>Filter by:</div>
				<button class="filter--button" (click)="statsPicker.open()">
					<img src="/assets/img/calendar-icon.svg" alt="calender icon" />
					<mat-date-range-input [formGroup]="statsDateRange" [rangePicker]="statsPicker">
						<input matStartDate formControlName="startDate" placeholder="Start date" />
						<input matEndDate formControlName="endDate" placeholder="End date" (dateChange)="fetchDashboardData()" />
					</mat-date-range-input>
					<mat-date-range-picker #statsPicker [disabled]="false"></mat-date-range-picker>
					<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
				</button>

				<div class="select">
					<select value="daily" [(ngModel)]="dashboardFrequency" (change)="fetchDashboardData()">
						<option value="daily">Daily</option>
						<option value="weekly">Weekly</option>
						<option value="monthly">Monthly</option>
						<option value="yearly">Yearly</option>
					</select>
				</div>
			</div>

			<div class="filter" [ngClass]="{ 'show-calendar': showFilterCalendar }">
				<div>Active Group:</div>
				<div class="select">
					<select [value]="activeGroup" [(ngModel)]="activeGroup" (change)="toggleActiveGroup()">
						<option [value]="group.uid" *ngFor="let group of groups">{{ group.name }}</option>
					</select>
				</div>
			</div>
		</div>

		<div class="dashboard--page--details">
			<div class="card dashboard--page--details--chart">
				<ul class="metrics">
					<li class="messages">
						<img src="/assets/img/message-icon.svg" alt="message icon" />
						<div class="metric">
							<div>{{ dashboardData.events_sent }}</div>
							<div>Event Sent</div>
						</div>
					</li>
					<li class="apps">
						<img src="/assets/img/apps-icon.svg" alt="apps icon" />
						<div class="metric">
							<div>{{ dashboardData.apps }}</div>
							<div>Apps</div>
						</div>
					</li>
				</ul>

				<div>
					<h3>Events Sent</h3>
					<canvas id="chart" width="400" height="200"></canvas>
				</div>
			</div>

			<div class="card has-title dashboard--page--details--credentials">
				<div class="card--title">
					<h2>Configuration</h2>
				</div>

				<ul class="card--container">
					<li class="list-item">
						<div class="list-item--label">
							Request interval (Seconds)
							<div class="list-item--item">{{ organisationDetails?.strategy?.default?.intervalSeconds }}s</div>
						</div>
					</li>

					<li class="list-item">
						<div class="list-item--label">
							Retry limit
							<div class="list-item--item">{{ organisationDetails?.strategy?.default?.retryLimit }}</div>
						</div>
					</li>

					<li class="list-item">
						<div class="list-item--label">
							Signature header
							<div class="list-item--item">{{ organisationDetails?.signature?.header }}</div>
						</div>
					</li>

					<li class="list-item">
						<div class="list-item--label">
							Signature hash
							<div class="list-item--item">{{ organisationDetails?.signature?.hash }}</div>
						</div>
					</li>
				</ul>
			</div>
		</div>

		<section class="card dashboard--logs">
			<div class="dashboard--logs--tabs">
				<div class="dashboard--logs--tabs--head tabs">
					<div class="tabs">
						<button *ngFor="let tab of tabs" (click)="toggleActiveTab(tab)" class="clear tab" [ngClass]="{ active: activeTab === tab }">
							{{ tab }}
						</button>
					</div>
				</div>

				<div class="table">
					<ng-container *ngIf="activeTab === 'events'">
						<div class="filter">
							<button
								class="filter--button date-filter-button"
								(click)="eventsFilterPicker.open()"
								[ngClass]="{ active: eventsFilterDateRange.value.startDate !== '' && eventsFilterDateRange.value.endDate !== '' }"
								(click)="showEventFilterCalendar = !showEventFilterCalendar"
							>
								<img src="/assets/img/calendar-icon.svg" alt="calender icon" />
								<mat-date-range-input [formGroup]="eventsFilterDateRange" [rangePicker]="eventsFilterPicker">
									<input matStartDate formControlName="startDate" placeholder="Start date" />
									<input matEndDate formControlName="endDate" placeholder="End date" (dateChange)="getEvents({ addToURL: true })" />
								</mat-date-range-input>
								<mat-date-range-picker #eventsFilterPicker [disabled]="false"></mat-date-range-picker>
								<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
							</button>

							<div class="select">
								<select [ngClass]="{ active: !!eventApp }" aria-label="frequency" [(ngModel)]="eventApp" (change)="getEvents({ addToURL: true })">
									<option value="">All Apps</option>
									<option [value]="app.uid" *ngFor="let app of apps?.content">
										{{ app.name }}
									</option>
								</select>
							</div>

							<button
								class="filter--button primary events-filter-clear-btn"
								(click)="clearEventFilters(activeTab)"
								[disabled]="(eventsFilterDateRange.value.startDate == '' || eventsFilterDateRange.value.endDate == '') && eventApp == ''"
								[ngClass]="{ disabled: (eventsFilterDateRange.value.startDate == '' || eventsFilterDateRange.value.endDate == '') && eventApp == '' }"
							>
								Clear Filter
							</button>
						</div>

						<hr />

						<div class="table--container smaller-table" *ngIf="displayedEvents.length > 0">
							<table id="events-table">
								<thead>
									<tr class="table--head">
										<th scope="col">Event Type</th>
										<th scope="col">App Name</th>
										<th scope="col">Created At</th>
										<th scope="col"></th>
									</tr>
								</thead>
								<tbody>
									<ng-container *ngFor="let eventGroup of displayedEvents; let i = index">
										<tr class="table--date-row">
											<td>
												<div>{{ eventGroup.date }}</div>
											</td>
											<td></td>
											<td></td>
											<td></td>
										</tr>
										<tr
											*ngFor="let event of eventGroup.events; let index = index"
											[ngClass]="{ active: event.uid === detailsItem?.uid }"
											[id]="'event' + index"
											(click)="detailsItem = event; getEventDeliveriesForSidebar(event.uid)"
										>
											<td>
												<div>
													<div class="tag">{{ event.event_type }}</div>
												</div>
											</td>
											<td class="has-long-text">
												<div>{{ event.app_metadata.title }}</div>
											</td>
											<td>
												<div>{{ event.created_at | date: 'mediumTime' }}</div>
											</td>
											<td>
												<div>
													<button class="primary clear has-icon icon-right" (click)="eventDeliveryFilteredByEventId = event.uid; openDeliveriesTab()">
														Deliveries
														<img src="../../../../assets/img/angle-arrow-right-primary.svg" alt="arrow right" />
													</button>
												</div>
											</td>
										</tr>
									</ng-container>
								</tbody>
							</table>

							<div class="table--load-more button-container center" *ngIf="events.pagination.totalPage > 1">
								<button [class]="'primary clear has-icon icon-left '" [disabled]="events.pagination.page === events.pagination.totalPage" (click)="eventsPage = eventsPage + 1; getEvents()">
									<img src="/assets/img/arrow-down-icon.svg" alt="arrow down icon" />
									Load more
								</button>
							</div>
						</div>

						<div class="empty-state table--container" *ngIf="displayedEvents.length === 0">
							<img src="/assets/img/empty-state-img.svg" alt="empty state" />
							<p>No event to show here</p>
						</div>
					</ng-container>

					<ng-container *ngIf="activeTab === 'event deliveries'">
						<div class="filter">
							<button
								class="filter--button date-filter-button"
								(click)="eventDeliveriesFilterPicker.open()"
								[ngClass]="{ active: eventDeliveriesFilterDateRange.value.startDate !== '' && eventDeliveriesFilterDateRange.value.endDate !== '' }"
								(click)="showEventFilterCalendar = !showEventFilterCalendar"
							>
								<img src="/assets/img/calendar-icon.svg" alt="calender icon" />
								<mat-date-range-input [formGroup]="eventDeliveriesFilterDateRange" [rangePicker]="eventDeliveriesFilterPicker">
									<input matStartDate formControlName="startDate" placeholder="Start date" />
									<input matEndDate formControlName="endDate" placeholder="End date" (dateChange)="getEventDeliveries({ addToURL: true })" />
								</mat-date-range-input>
								<mat-date-range-picker #eventDeliveriesFilterPicker [disabled]="false"></mat-date-range-picker>
								<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
							</button>

							<div class="dropdown">
								<button
									class="filter--button dropdown--button"
									[ngClass]="{ active: eventDeliveryFilteredByStatus }"
									(click)="showOverlay = true; showEventDeliveriesStatusDropdown = !showEventDeliveriesStatusDropdown"
								>
									<img src="/assets/img/status-filter-icon.svg" alt="status filter icon" />
									<span>{{ eventDeliveryFilteredByStatus || 'Status' }}</span>
									<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" />
								</button>
								<div class="dropdown--list" *ngIf="showEventDeliveriesStatusDropdown">
									<div class="dropdown--list--item" *ngFor="let status of eventDeliveryStatuses">
										<input
											type="radio"
											name="status"
											[value]="status"
											[(ngModel)]="eventDeliveryFilteredByStatus"
											[id]="status"
											(change)="showOverlay = false; showEventDeliveriesStatusDropdown = false; getEventDeliveries({ addToURL: true })"
										/>
										<label [for]="status">{{ status || 'None' }}</label>
									</div>
								</div>
							</div>

							<div class="select">
								<select [ngClass]="{ active: !!eventDeliveriesApp }" aria-label="frequency" [(ngModel)]="eventDeliveriesApp" (change)="getEventDeliveries({ addToURL: true })">
									<option value="">All Apps</option>
									<option [value]="app.uid" *ngFor="let app of apps?.content">
										{{ app.name }}
									</option>
								</select>
							</div>

							<div class="filter--button event-button active" *ngIf="eventDeliveryFilteredByEventId !== ''">
								Event Filtered
								<button class="primary clear has-icon" (click)="eventDeliveryFilteredByEventId = ''; getEventDeliveries()">
									<img src="../../../../assets/img/close-icon.svg" alt="close icon" />
								</button>
							</div>

							<button
								class="filter--button primary events-filter-clear-btn"
								(click)="clearEventFilters(activeTab)"
								[disabled]="
									(eventDeliveriesFilterDateRange.value.startDate == '' || eventDeliveriesFilterDateRange.value.endDate == '') &&
									eventDeliveriesApp == '' &&
									eventDeliveryFilteredByEventId == '' &&
									!eventDeliveryFilteredByStatus
								"
							>
								Clear Filter
							</button>
						</div>

						<hr />

						<div class="table--actions button-container left">
							<button class="primary clear has-icon icon-left hover" (click)="refreshTables()">
								<img src="../../../../assets/img/refresh-icon-2.svg" alt="refresh icon" />
								Refresh
							</button>
							<button class="primary clear has-icon icon-left hover" (click)="batchRetryEvent()" [disabled]="selectedEventsFromEventDeliveriesTable.length <= 0">
								<img src="../../../../assets/img/retry-icon.svg" alt="retry icon" />
								Bulk Retry
							</button>
						</div>

						<div class="table--container" *ngIf="displayedEventDeliveries.length > 0">
							<table id="event-deliveries-table">
								<thead>
									<tr class="table--head">
										<th scope="col" class="checkbox">
											<div class="checkbox"><input type="checkbox" name="eventDeliveryTable" id="eventDeliveryTable" (change)="checkAllCheckboxes($event)" /></div>
											Status
										</th>
										<th scope="col">Event Type</th>
										<th scope="col">Attempts</th>
										<th scope="col">Created At</th>
										<th scope="col"></th>
									</tr>
								</thead>
								<tbody>
									<ng-container *ngFor="let eventDeliveriesGroup of displayedEventDeliveries; let i = index">
										<tr class="table--date-row">
											<td>
												<div>{{ eventDeliveriesGroup.date }}</div>
											</td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
										</tr>
										<tr
											*ngFor="let event of eventDeliveriesGroup.events; let index = index"
											[ngClass]="{ active: event.uid === detailsItem?.uid }"
											[id]="'event' + index"
											(click)="detailsItem = event; getDelieveryAttempts(event.uid)"
										>
											<td>
												<div class="checkbox has-retry">
													<img *ngIf="event.metadata.num_trials > event.metadata.retry_limit" src="/assets/img/retry-icon.svg" alt="retry icon" title="manually retried" />
													<input type="checkbox" [name]="'event' + index" id="event" [value]="event.uid" (change)="checkEventDeliveryBox($event)" />
													<div [class]="'tag tag--' + event.status">{{ event.status }}</div>
												</div>
											</td>
											<td>
												<div>{{ event.event_metadata.name }}</div>
											</td>
											<td>
												<div>{{ event.metadata?.num_trials }}</div>
											</td>
											<td>
												<div>{{ event.created_at | date: 'mediumTime' }}</div>
											</td>
											<td>
												<div>
													<button
														[disabled]="event.status === 'Success' || event.status === 'Scheduled'"
														[class]="'primary has-icon icon-left ' + (event.status === 'Success' || event.status === 'Scheduled' ? 'disabled' : '')"
														(click)="retryEvent({ e: $event, index: this.index, eventDeliveryId: event.uid })"
													>
														<img src="/assets/img/refresh-icon.svg" alt="refresh icon" />
														Retry
													</button>
												</div>
											</td>
										</tr>
									</ng-container>
								</tbody>
							</table>

							<div class="table--load-more button-container center" *ngIf="eventDeliveries.pagination.totalPage > 1">
								<button [class]="'primary clear has-icon icon-left'" [disabled]="eventDeliveries.pagination.page === eventDeliveries.pagination.totalPage" (click)="loadMoreEventDeliveries()">
									<img src="/assets/img/arrow-down-icon.svg" alt="arrow down icon" />
									Load more
								</button>
							</div>
						</div>

						<div class="empty-state table--container" *ngIf="displayedEventDeliveries.length === 0">
							<img src="/assets/img/empty-state-img.svg" alt="empty state" />
							<p>No event to show here</p>
						</div>
					</ng-container>

					<div class="table--container smaller-table" *ngIf="apps && apps.content.length > 0 && activeTab === 'apps'">
						<table>
							<thead>
								<tr class="table--head">
									<th scope="col">Name</th>
									<th scope="col">Created</th>
									<th scope="col">Updated</th>
									<th scope="col">Events</th>
									<th scope="col">Endpoints</th>
									<th scope="col"></th>
								</tr>
							</thead>
							<tbody>
								<tr *ngFor="let app of apps?.content" [ngClass]="{ active: app.uid === detailsItem?.uid }" (click)="detailsItem = app">
									<td class="has-long-text">
										<div>{{ app.name }}</div>
									</td>
									<td>
										<div>{{ app.created_at | date }}</div>
									</td>
									<td>
										<div>{{ app.updated_at | date }}</div>
									</td>
									<td>
										<div>{{ app.events }}</div>
									</td>
									<td>
										<div>{{ app.endpoints.length }}</div>
									</td>
									<td>
										<div>
											<button
												[disabled]="app.events <= 0"
												title="view events"
												[class]="'primary has-icon icon-left'"
												(click)="toggleActiveTab('events'); getEvents({ addToURL: true, appId: app.uid })"
											>
												<img src="/assets/img/view-events-icon.svg" alt="view events icon" />
												Events
											</button>
										</div>
									</td>
								</tr>
							</tbody>
						</table>

						<div class="table--load-more button-container margin-top center" *ngIf="apps?.pagination && apps.pagination.totalPage > 1">
							<button
								[class]="'primary clear has-icon icon-left ' + (apps.pagination.page === apps.pagination.totalPage ? 'disabled' : '')"
								[disabled]="apps.pagination.page === apps.pagination.totalPage"
							>
								<img src="/assets/img/arrow-down-icon.svg" alt="arrow down icon" />
								Load more
							</button>
						</div>
					</div>

					<div class="empty-state" *ngIf="apps?.content?.length === 0 && activeTab === 'apps'">
						<img src="/assets/img/empty-state-img.svg" alt="empty state" />
						<p>No app to show here</p>
					</div>
				</div>
			</div>

			<div class="dashboard--logs--details">
				<ng-container *ngIf="detailsItem">
					<h3>Details</h3>
					<ul class="dashboard--logs--details--meta" *ngIf="activeTab === 'apps' || activeTab === 'event deliveries'">
						<ng-container *ngIf="activeTab === 'event deliveries'">
							<li class="list-item-inline">
								<div class="list-item-inline--label">IP Address</div>
								<div class="list-item-inline--item color">{{ eventDeliveryAtempt?.ip_address || '-' }}</div>
							</li>
							<li class="list-item-inline">
								<div class="list-item-inline--label">HTTP Status</div>
								<div class="list-item-inline--item">{{ eventDeliveryAtempt?.http_status || '-' }}</div>
							</li>
							<li class="list-item-inline">
								<div class="list-item-inline--label">API Version</div>
								<div class="list-item-inline--item color">{{ eventDeliveryAtempt?.api_version || '-' }}</div>
							</li>
							<li class="list-item-inline">
								<div class="list-item-inline--label">Endpoint</div>
								<div class="list-item-inline--item color" [title]="detailsItem.endpoint?.target_url">
									{{ detailsItem.endpoint?.target_url }}
								</div>
							</li>
							<li class="list-item-inline" *ngIf="detailsItem.metadata?.num_trials < detailsItem.metadata?.retry_limit && detailsItem.status !== 'Success'">
								<div class="list-item-inline--label">Next Retry</div>
								<div class="list-item-inline--item color">
									{{ detailsItem.metadata?.next_send_time | date: 'mediumTime' }}
								</div>
							</li>
							<li class="list-item-inline">
								<div class="list-item-inline--label">App Name</div>
								<div class="list-item-inline--item color">
									{{ detailsItem.app_metadata?.title }}
								</div>
							</li>
						</ng-container>
						<li class="list-item-inline" *ngIf="activeTab === 'apps'">
							<div class="list-item-inline--label">Support Email</div>
							<div class="list-item-inline--item">{{ detailsItem?.support_email || '-' }}</div>
						</li>
					</ul>

					<ul class="tabs" *ngIf="activeTab === 'event deliveries'">
						<li *ngFor="let tab of eventDetailsTabs" [class]="'tab ' + (eventDetailsActiveTab === tab.id ? 'active' : '')">
							<button class="primary outline" (click)="eventDetailsActiveTab = tab.id">{{ tab.label }}</button>
						</li>
					</ul>

					<div class="dashboard--logs--details--req-res" *ngIf="activeTab === 'events' || activeTab === 'event deliveries'">
						<div [class]="'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'data' ? 'show' : '')">
							<h3>Event</h3>
							<app-shared language="json" [code]="getCodeSnippetString(activeTab === 'events' ? 'event' : 'event_delivery')"></app-shared>
						</div>

						<div [class]="'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'response' ? 'show' : '')">
							<h3>Header</h3>
							<app-shared language="json" [code]="getCodeSnippetString('res_head')"></app-shared>

							<h3>Body</h3>
							<app-shared language="json" [code]="getCodeSnippetString('res_body')"></app-shared>
						</div>

						<div [class]="'dashboard--logs--details--tabs-data ' + (eventDetailsActiveTab === 'request' ? 'show' : '')">
							<h3>Header</h3>
							<app-shared language="json" [code]="getCodeSnippetString('req')"></app-shared>
						</div>
					</div>

					<ng-container *ngIf="activeTab === 'events'">
						<h4>Deliveries Overview</h4>
						<ul class="dashboard--logs--details--endpoints inline">
							<li *ngFor="let delivery of sidebarEventDeliveries">
								<div [class]="'tag tag--' + delivery.status">{{ delivery.status }}</div>
								<div class="url" [title]="delivery.endpoint.target_url">
									{{ delivery.endpoint.target_url }}
								</div>
							</li>
						</ul>
					</ng-container>

					<ng-container *ngIf="activeTab === 'apps'">
						<h4>App Event Endpoints</h4>
						<ul class="dashboard--logs--details--endpoints">
							<ng-container *ngIf="detailsItem?.endpoints">
								<li *ngFor="let endpoint of detailsItem.endpoints">
									<h5>{{ endpoint.description }}</h5>
									<p>
										<img src="/assets/img/link-icon.svg" alt="link icon" />
										{{ endpoint.target_url }}
									</p>
									<div class="events">
										<div class="tag" *ngFor="let event of endpoint.events">{{ event == '*' ? 'all events' : event }}</div>
									</div>
								</li>
							</ng-container>
						</ul>
					</ng-container>
				</ng-container>
			</div>
		</section>
	</div>
</div>

<div class="overlay" *ngIf="showOverlay" (click)="showOverlay = false; showEventDeliveriesStatusDropdown = false"></div>

// web/ui/react-app/src/pages/dashboard/index.js
import React, { useEffect, useState, useCallback } from 'react';
import * as axios from 'axios';
import ArrowDownIcon from '../../assets/img/arrow-down-icon.svg';
import AppsIcon from '../../assets/img/apps-icon.svg';
import MessageIcon from '../../assets/img/message-icon.svg';
import RefreshIcon from '../../assets/img/refresh-icon.svg';
import CalendarIcon from '../../assets/img/calendar-icon.svg';
import CopyIcon from '../../assets/img/copy-icon.svg';
import LinkIcon from '../../assets/img/link-icon.svg';
import ViewIcon from '../../assets/img/view-icon.svg';
import AngleArrowLeftIcon from '../../assets/img/angle-arrow-left.svg';
import AngleArrowRightIcon from '../../assets/img/angle-arrow-right.svg';
import AngleArrowDownIcon from '../../assets/img/angle-arrow-down.svg';
import AngleArrowUpIcon from '../../assets/img/angle-arrow-up.svg';
import ConvoyLogo from '../../assets/img/logo.svg';
import Chart from 'chart.js/auto';
import { DateRange } from 'react-date-range';
import ReactJson from 'react-json-view';
import './app.scss';
import 'react-date-range/dist/styles.css';
import 'react-date-range/dist/theme/default.css';

const _axios = axios.default;
// eslint-disable-next-line no-restricted-globals
const request = _axios.create({ baseURL: `${location.port === '3000' ? 'http://localhost:5005' : location.origin}/v1` });
const months = ['Jan', 'Feb', 'Mar', 'April', 'May', 'June', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'];

function DashboardPage() {
	const [dashboardData, setDashboardData] = useState({ apps: 0, messages: 0, messageData: [] });
	const [authDetails, setAuthDetails] = useState({ basic: { username: '', password: '' }, type: '' });
	const [viewPassword, toggleViewPassword] = useState(false);
	const [viewAllEventData, toggleViewAllEventDataState] = useState(false);
	const [viewAllResponseData, toggleViewAllResponseData] = useState(false);
	const [apps, setAppsData] = useState([]);
	const [events, setEventsData] = useState({ content: [], pagination: { page: 1, totalPage: 0 } });
	const [tabs] = useState(['events', 'apps']);
	const [activeTab, setActiveTab] = useState('events');
	const [showFilterCalendar, toggleShowFilterCalendar] = useState(false);
	const [organisations, setOrganisations] = useState([]);
	const [activeorganisation, setActiveOrganisation] = useState({
		uid: '',
		name: '',
		created_at: 0,
		updated_at: 0,
		deleted_at: 0,
	});
	const [eventDeliveryAtempt, setEventDeliveryAtempt] = useState({
		ip_address: '',
		http_status: '',
		api_version: '',
		updated_at: 0,
		deleted_at: 0,
		response_data: '',
	});
	const [detailsItem, setDetailsItem] = useState();
	const [filterFrequency, setFilterFrequency] = useState('daily');
	const [filterDates, setFilterDates] = useState([
		{
			startDate: new Date(new Date().setDate(new Date().getDate() - 20)),
			endDate: new Date(),
			key: 'selection',
		},
	]);

	const [jsonStyle] = useState({
		fontSize: '12px',
		lineHeight: '25px',
	});

	const [options] = useState({
		plugins: {
			legend: {
				display: false,
			},
		},
		scales: {
			xAxis: {
				display: true,
				grid: {
					display: false,
				},
			},
		},
	});

	const getDate = (date) => {
		const _date = new Date(date);
		const day = _date.getDate();
		const month = _date.getMonth();
		const year = _date.getFullYear();
		return `${day} ${months[month]}, ${year}`;
	};

	const copyText = (copyText) => {
		const el = document.createElement('textarea');
		el.value = copyText;
		document.body.appendChild(el);
		el.select();
		document.execCommand('copy');
		el.style.display = 'none';
	};

	const getRequestHeaders = useCallback(() => {
		const response =
			authDetails.type === 'none'
				? {}
				: {
						Authorization: `Basic ${btoa(authDetails.basic.username + ':' + authDetails.basic.password)}`,
				  };
		return response;
	}, [authDetails.basic.password, authDetails.basic.username, authDetails.type]);

	const getEvents = useCallback(
		async ({ page }) => {
			try {
				const appsResponse = await (
					await request({
						url: `/events?sort=AESC&page=${page || 1}&perPage=10&orgId=${activeorganisation.uid}`,
						method: 'GET',
						headers: getRequestHeaders(),
					})
				).data;
				setEventsData(appsResponse.data);
			} catch (error) {
				return error;
			}
		},
		[getRequestHeaders, activeorganisation],
	);

	const getApps = useCallback(
		async ({ page }) => {
			try {
				const appsResponse = await (
					await request({
						url: `/apps?sort=AESC&page=${page || 1}&perPage=10&orgId=${activeorganisation.uid}`,
						headers: getRequestHeaders(),
					})
				).data;
				setAppsData(appsResponse.data);
			} catch (error) {
				return error;
			}
		},
		[activeorganisation, getRequestHeaders],
	);

	const getDelieveryAttempts = async (eventId) => {
		try {
			const deliveryAttemptsResponse = await (
				await request({
					url: `/events/${eventId}/deliveryattempts`,
					headers: getRequestHeaders(),
				})
			).data;
			setEventDeliveryAtempt(deliveryAttemptsResponse.data[deliveryAttemptsResponse.data.length - 1]);
		} catch (error) {
			return error;
		}
	};

	const retryEvent = async ({ eventId, appId }) => {
		try {
			await (
				await request({
					method: 'PUT',
					url: `/apps/${appId}/events/${eventId}/resend`,
					headers: getRequestHeaders(),
				})
			).data;
		} catch (error) {
			return error;
		}
	};

	useEffect(() => {
		const getOrganisations = async () => {
			try {
				const organisationsResponse = await (
					await request({
						url: '/organisations',
						headers: getRequestHeaders(),
					})
				).data;
				setOrganisations(organisationsResponse.data);
				setActiveOrganisation(organisationsResponse.data[0]);
			} catch (error) {
				return error;
			}
		};

		const getAuthDetails = async () => {
			try {
				if (authDetails.type) return;
				const authDetailsResponse = await (await request.get('/auth/details')).data;
				setAuthDetails(authDetailsResponse.data);
			} catch (error) {
				return error;
			}
		};

		const fetchDashboardData = async () => {
			try {
				if (organisations.length === 0) await getOrganisations();
				if (!activeorganisation.uid) return;
				const dashboardResponse = await request({
					url: `/dashboard/${activeorganisation.uid}/summary?startDate=${filterDates[0].startDate.toISOString().split('.')[0]}&endDate=${filterDates[0].endDate.toISOString().split('.')[0]}&type=${
						filterFrequency || 'daily'
					}`,
					headers: getRequestHeaders(),
				});
				setDashboardData(dashboardResponse.data.data);

				const chartData = dashboardResponse.data.data.message_data;
				const labels = [0, ...chartData.map((label) => label.data.date)];
				const dataSet = [0, ...chartData.map((label) => label.count)];
				const data = {
					labels,
					datasets: [
						{
							data: dataSet,
							fill: false,
							borderColor: '#477DB3',
							tension: 0.5,
							yAxisID: 'yAxis',
							xAxisID: 'xAxis',
						},
					],
				};

				if (!Chart.getChart('chart') || !Chart.getChart('chart')?.canvas) {
					new Chart(document.getElementById('chart'), { type: 'line', data, options });
				} else {
					const currentChart = Chart.getChart('chart');
					currentChart.data.labels = labels;
					currentChart.data.datasets[0].data = dataSet;
					currentChart.update();
				}
			} catch (error) {
				return error;
			}
		};

		getAuthDetails().then(() => {
			fetchDashboardData();
			if (activeTab === 'apps') getApps({ page: 1 });
			if (activeTab === 'events') getEvents({ page: 1 });
		});
	}, [options, activeTab, filterDates, activeorganisation, organisations, filterFrequency, authDetails, getRequestHeaders, getEvents, getApps]);

	return (
		<div className="dashboard">
			<header className="dashboard--header">
				<div className="dashboard--header--container">
					<div className="logo">
						<img src={ConvoyLogo} alt="convoy logo" />
					</div>

					<button className="user">
						<div>
							<div className="icon">O</div>
							<div className="name">{activeorganisation && activeorganisation.name}</div>
						</div>
						<img src={ArrowDownIcon} alt="arrow down icon" />
					</button>
				</div>
			</header>

			<div className="dashboard--page">
				<div className={`filter ${showFilterCalendar ? 'show-calendar' : ''}`}>
					Filter by:
					<button className="filter--button" onClick={() => toggleShowFilterCalendar(!showFilterCalendar)}>
						<img src={CalendarIcon} alt="calender icon" />
						<div>
							{getDate(filterDates[0].startDate)} - {getDate(filterDates[0].endDate)}
						</div>
						<img src={ArrowDownIcon} alt="arrow down icon" />
					</button>
					<DateRange onChange={(item) => setFilterDates([item.selection])} moveRangeOnFirstSelection={false} ranges={filterDates} />
					<select value={filterFrequency} onChange={(event) => setFilterFrequency(event.target.value)}>
						<option value="daily">Daily</option>
						<option value="weekly">Weekly</option>
						<option value="monthly">Monthly</option>
						<option value="yearly">Yearly</option>
					</select>
				</div>

				<div className="dashboard--page--details">
					<div className="card dashboard--page--details--chart">
						<ul>
							<li className="messages">
								<img src={MessageIcon} alt="message icon" />
								<div className="metric">
									<div>{dashboardData.messages_sent}</div>
									<div>{dashboardData.messages_sent === 1 ? 'Event' : 'Events'} Sent</div>
								</div>
							</li>
							<li className="apps">
								<img src={AppsIcon} alt="apps icon" />
								<div className="metric">
									<div>{dashboardData.apps}</div>
									<div>{dashboardData.apps === 1 ? 'App' : 'Apps'}</div>
								</div>
							</li>
						</ul>

						<div>
							<h3>Events Sent</h3>
							<canvas id="chart" width="400" height="200"></canvas>
						</div>
					</div>

					<div className="card has-title dashboard--page--details--credentials">
						<div className="card--title">
							<h2>Organization Details</h2>
						</div>

						<div className="card--container">
							{authDetails.type === 'none' && (
								<div className="card--empty-state">
									<p>You don't have any organisation auth details set</p>
								</div>
							)}

							{authDetails.type !== 'none' && (
								<React.Fragment>
									<div className="auth-item">
										<div>
											<div className="auth-item--label">Username</div>
											<div className="auth-item--item">{authDetails.basic.username}</div>
										</div>
										<button className="copy" onClick={() => copyText(authDetails.basic.username)}>
											<img src={CopyIcon} alt="copy icon" />
										</button>
									</div>

									<div className="auth-item">
										<div>
											<div className="auth-item--label">Password</div>
											{viewPassword && <div className="auth-item--item">{authDetails.basic.password}</div>}
											{!viewPassword && <div className="auth-item--item">********</div>}
										</div>
										<button className="copy" onClick={() => toggleViewPassword(!viewPassword)}>
											<img src={ViewIcon} alt="view icon" />
										</button>
									</div>

									<div className="auth-item">
										<div>
											<div className="auth-item--label">Organisation ID</div>
											<div className="auth-item--item">{activeorganisation.uid}</div>
										</div>
										<button className="copy" onClick={() => copyText(activeorganisation.uid)}>
											<img src={CopyIcon} alt="copy icon" />
										</button>
									</div>
								</React.Fragment>
							)}
						</div>

						<div className="card--footer">
							<p>Our documentation contains the libraries, API and SDKs you need to integrate Fhooks on your platform.</p>
							<button className="primary" onClick={() => (window.location = 'https://github.com/frain-dev/convoy')}>
								Go to docs
							</button>
						</div>
					</div>
				</div>

				<section className="card dashboard--logs">
					<div className="dashboard--logs--tabs">
						<div className="tabs">
							{tabs.map((tab, index) => (
								<button
									onClick={() => {
										setActiveTab(tab);
										setDetailsItem();
										setEventDeliveryAtempt({
											ip_address: '',
											http_status: '',
											api_version: '',
											updated_at: 0,
											deleted_at: 0,
										});
									}}
									key={index}
									className={'clear tab ' + (activeTab === tab ? 'active' : '')}
								>
									{tab}
								</button>
							))}
						</div>

						<div className="table">
							{activeTab && activeTab === 'events' && (
								<React.Fragment>
									<table>
										<thead>
											<tr className="table--head">
												<th scope="col">Status</th>
												<th scope="col">Event Type</th>
												<th scope="col">Attempts</th>
												<th scope="col">Next Retry</th>
												<th scope="col">Date Created</th>
												<th scope="col">Next Entry</th>
											</tr>
										</thead>
										<tbody>
											{events.content.map((event, index) => (
												<tr
													key={index}
													onClick={() => {
														setDetailsItem(event);
														getDelieveryAttempts(event.uid);
													}}
												>
													<td>
														<div>
															<div className="tag">{event.status}</div>
														</div>
													</td>
													<td>
														<div>{event.event_type}</div>
													</td>
													<td>
														<div>{event.metadata.num_trials}</div>
													</td>
													<td>
														<div>{getDate(event.metadata.next_send_time)}</div>
													</td>
													<td>
														<div>{getDate(event.created_at)}</div>
													</td>
													<td>
														<div>
															<button
																disabled={event.status === 'Success' || event.status === 'Scheduled'}
																className={'primary has-icon icon-left ' + (event.status === 'Success' || event.status === 'Scheduled' ? 'disable_action' : '')}
																onClick={() => retryEvent({ eventId: event.uid, appId: event.app_id })}
															>
																<img src={RefreshIcon} alt="refresh icon" /> Retry
															</button>
														</div>
													</td>
												</tr>
											))}
										</tbody>
									</table>

									{events.pagination.totalPage > 1 && (
										<div className="pagination">
											<button disabled={events.pagination.page === 1} onClick={() => getEvents({ page: events.pagination.page + 1 })} className="has-icon">
												<img src={AngleArrowLeftIcon} alt="angle icon left" />
											</button>
											<button disabled={events.pagination.page === events.pagination.totalPage} onClick={() => getEvents({ page: events.pagination.page + 1 })} className="has-icon">
												<img src={AngleArrowRightIcon} alt="angle icon right" />
											</button>
										</div>
									)}
								</React.Fragment>
							)}

							{activeTab && activeTab === 'apps' && (
								<table>
									<thead>
										<tr className="table--head">
											<th scope="col">Name</th>
											<th scope="col">Created</th>
											<th scope="col">Updated</th>
											<th scope="col">Number of Events</th>
											<th scope="col">Number of Endpoints</th>
										</tr>
									</thead>
									<tbody>
										{apps.map((app, index) => (
											<tr key={index} onClick={() => setDetailsItem(app)}>
												<td>
													<div>{app.name}</div>
												</td>
												<td>
													<div>{getDate(app.created_at)}</div>
												</td>
												<td>
													<div>{getDate(app.updated_at)}</div>
												</td>
												<td>
													<div>{app.events}</div>
												</td>
												<td>
													<div>{app.endpoints.length}</div>
												</td>
											</tr>
										))}
									</tbody>
								</table>
							)}
						</div>
					</div>

					{detailsItem && (
						<div className="dashboard--logs--details">
							<h3>Details</h3>
							<ul className="dashboard--logs--details--meta">
								{eventDeliveryAtempt && eventDeliveryAtempt.ip_address && (
									<React.Fragment>
										<li>
											<div className="label">IP Address</div>
											<div className="value color">{eventDeliveryAtempt.ip_address}</div>
										</li>
										<li>
											<div className="label">HTTP Status</div>
											<div className="value">{eventDeliveryAtempt.http_status}</div>
										</li>
										<li>
											<div className="label">API Version</div>
											<div className="value color">{eventDeliveryAtempt.api_version}</div>
										</li>
									</React.Fragment>
								)}
								<li>
									<div className="label">Date Created</div>
									<div className="value">{getDate(detailsItem.created_at)}</div>
								</li>
								<li>
									<div className="label">Last Updated</div>
									<div className="value">{getDate(detailsItem.updated_at)}</div>
								</li>
							</ul>

							{activeTab === 'events' && (
								<React.Fragment>
									<h4>Event Data</h4>
									<div className={'dashboard--logs--details--event-data ' + (viewAllEventData && detailsItem.data ? '' : 'data-hidden')}>
										<ReactJson src={detailsItem.data} iconStyle="square" displayDataTypes={false} enableClipboard={false} style={jsonStyle} name={false} />
									</div>
									{detailsItem.data && (
										<div className="dashboard--logs--details--view-more">
											<button className="has-icon" onClick={() => toggleViewAllEventDataState(!viewAllEventData)}>
												<img src={AngleArrowDownIcon} alt="angle arrow down" />
												{viewAllEventData ? 'Hide more' : 'View more'}
											</button>
										</div>
									)}

									<hr />

									<h4>Response Data</h4>
									{eventDeliveryAtempt && (
										<div>
											<div className={'dashboard--logs--details--response-data ' + (viewAllResponseData && eventDeliveryAtempt.response_data ? '' : 'data-hidden')}>
												{eventDeliveryAtempt.response_data}
											</div>
											{eventDeliveryAtempt.response_data && eventDeliveryAtempt.response_data.length > 60 && (
												<div className="dashboard--logs--details--view-more">
													<button className="has-icon" onClick={() => toggleViewAllResponseData(!viewAllResponseData)}>
														{!viewAllResponseData && <img src={AngleArrowDownIcon} alt="angle arrow down" />}
														{viewAllResponseData && <img src={AngleArrowUpIcon} alt="angle arrow up" />}
														{viewAllResponseData ? 'Hide more' : 'View more'}
													</button>
												</div>
											)}
										</div>
									)}
								</React.Fragment>
							)}

							{activeTab === 'apps' && (
								<React.Fragment>
									<h4>App Event Endpoints</h4>
									<ul className="dashboard--logs--details--endpoints">
										{detailsItem.endpoints &&
											detailsItem.endpoints.map((endpoint, index) => (
												<li key={index}>
													<h5>{endpoint.description}</h5>
													<p>
														<img src={LinkIcon} alt="link icon" />
														{endpoint.target_url}
													</p>
												</li>
											))}
									</ul>
								</React.Fragment>
							)}
						</div>
					)}
				</section>
			</div>
		</div>
	);
}

export { DashboardPage };
