// web/ui/dashboard-react/src/app/login.tsx
import { Button } from '@/components/ui/button';
import {
	FormField,
	FormItem,
	FormLabel,
	FormControl,
	FormMessageWithErrorIcon,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Form } from '@/components/ui/form';
import { cn } from '@/lib/utils';
import { zodResolver } from '@hookform/resolvers/zod';
import { EyeIcon, EyeOffIcon } from 'lucide-react';
import { useEffect, useReducer, useState } from 'react';
import { useForm } from 'react-hook-form';
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { z } from 'zod';
import { ConvoyLoader } from '@/components/ConvoyLoader';
import * as loginService from '@/services/login.service';
import * as signUpService from '@/services/signup.service';
import * as privateService from '@/services/private.service';
import * as licensesService from '@/services/licenses.service';

import type { UseFormReturn } from 'react-hook-form';

const formSchema = z.object({
	email: z.string().email('Please enter your email'),
	password: z.string().min(1, 'Please enter your password'),
});

type EmailInputFieldProps = {
	form: UseFormReturn<z.infer<typeof formSchema>>;
};

function EmailInputField({ form }: EmailInputFieldProps) {
	return (
		<FormField
			control={form.control}
			name="email"
			render={({ field, fieldState }) => (
				<FormItem className="w-full relative mb-6 block">
					<div className="w-full mb-2 flex items-center justify-between">
						<FormLabel className="text-xs/5 text-neutral-9">Email</FormLabel>
					</div>
					<FormControl>
						<Input
							autoComplete="email"
							type="email"
							className={cn(
								'mt-0 outline-none focus-visible:ring-0 border-neutral-4 shadow-none w-full h-auto transition-all duration-300 bg-white-100 py-3 px-4 text-neutral-11 !text-xs/5 rounded-[4px] placeholder:text-new.gray-300 placeholder:text-sm/5 font-normal disabled:text-neutral-6 disabled:border-new.primary-25',
								fieldState.error
									? 'border-new.error-500 focus-visible:ring-0 hover:border-new.error-500'
									: ' hover:border-new.primary-100 focus:border-new.primary-300',
							)}
							placeholder="super@default.com"
							{...field}
						/>
					</FormControl>
					<FormMessageWithErrorIcon />
				</FormItem>
			)}
		/>
	);
}

type PasswordInputFieldProps = {
	form: UseFormReturn<z.infer<typeof formSchema>>;
};

function PasswordInputField({ form }: PasswordInputFieldProps) {
	const [isPasswordVisible, setIsPasswordVisible] = useState(false);

	return (
		<FormField
			control={form.control}
			name="password"
			render={({ field, fieldState }) => (
				<FormItem className="w-full relative mb-2 block">
					<div className="w-full mb-[8px] flex items-center justify-between">
						<FormLabel
							className="text-xs/5 text-neutral-9"
							htmlFor="password_input"
						>
							Password
						</FormLabel>
					</div>
					<FormControl className="w-full relative">
						<div className="relative">
							<Input
								id="password_input"
								autoComplete="current-password"
								type={isPasswordVisible ? 'text' : 'password'}
								className={cn(
									'hide-password-toggle mt-0 outline-none focus-visible:ring-0 border-neutral-4 shadow-none w-full h-auto transition-all duration-300 bg-white-100 py-3 px-4 text-neutral-11 !text-xs/5 rounded-[4px] placeholder:text-new.gray-300 placeholder:text-sm/5 font-normal disabled:text-neutral-6 disabled:border-new.primary-25',
									fieldState.error
										? 'border-new.error-500 focus-visible:ring-0 hover:border-new.error-500'
										: 'hover:border-new.primary-100 focus:border-new.primary-300',
								)}
								placeholder="super@default.com"
								{...field}
							/>
							<Button
								type="button"
								variant="ghost"
								size="sm"
								className="absolute right-[1%] top-0 h-full px-3 py-2 hover:bg-transparent"
								onClick={() => setIsPasswordVisible(!isPasswordVisible)}
							>
								{isPasswordVisible ? (
									<EyeIcon className="opacity-50" aria-hidden="true" />
								) : (
									<EyeOffIcon className="opacity-50" aria-hidden="true" />
								)}
								<span className="sr-only">
									{isPasswordVisible ? 'Hide password' : 'Show password'}
								</span>
							</Button>
						</div>
					</FormControl>
					<FormMessageWithErrorIcon />
				</FormItem>
			)}
		/>
	);
}

function ForgotPasswordSection() {
	const navigate = useNavigate();

	function navigateToPasswordPage() {
		navigate({
			from: '/login',
			to: '/forgot-password',
		});
	}

	return (
		<div className="flex items-center text-xs/5 mb-[20px]">
			Forgot password?
			<Button
				variant={'link'}
				type="button"
				className="p-2 ml-[16px] text-new.primary-400 underline underline-offset-1"
				onClick={navigateToPasswordPage}
				size="sm"
			>
				Reset it here
			</Button>
		</div>
	);
}

function LoginButton(props: { isButtonEnabled?: boolean }) {
	const { isButtonEnabled } = props;

	return (
		<Button
			disabled={!isButtonEnabled}
			variant={'ghost'}
			size={'lg'}
			className="flex items-center justify-center disabled:opacity-50 cursor-pointer mb-3 bg-new.primary-400 hover:bg-new.primary-400 px-9 py-[10px] rounded-8px text-sm/5 text-white-100 w-full"
		>
			<span
				className={cn(
					'text-sm text-white-100',
					!isButtonEnabled ? 'hidden' : '',
				)}
			>
				Login
			</span>
			<img
				className={cn('h-4', !isButtonEnabled ? '' : 'hidden')}
				src="assets/img/button-loader.gif"
				alt="loader"
			/>
		</Button>
	);
}

function LoginWithSAMLButton() {
	async function login() {
		localStorage.setItem('AUTH_TYPE', 'login');

		try {
			const res = await loginService.loginWithSAML();
			const { redirectUrl } = res.data;
			window.open(redirectUrl);
		} catch (error) {
			// TODO should notify user here with UI
			throw error;
		}
	}

	return (
		<Button
			type="button"
			size={'lg'}
			variant={'ghost'}
			onClick={login}
			className="disabled:opacity-50 cursor-pointer w-full rounded-8px text-xs/5 text-new.primary-400 hover:text-new.primary-400 py-0 hover:bg-transparent h-auto"
		>
			Login with SAML
		</Button>
	);
}

function SignUpButton() {
	const navigate = useNavigate();

	function navigateToSignUpPage() {
		navigate({
			from: '/login',
			to: '/signup',
		});
	}

	return (
		<Button
			type="button"
			size={'lg'}
			variant={'ghost'}
			onClick={navigateToSignUpPage}
			className="disabled:opacity-50 cursor-pointer w-full rounded-8px text-xs/5 text-new.primary-400 hover:text-new.primary-400 py-0 hover:bg-transparent h-auto mt-3"
		>
			Sign Up
		</Button>
	);
}

type ReducerPayload = Partial<{
	isSignUpEnabled: boolean;
	isFetchingConfig: boolean;
	isLoadingProject: boolean;
	hasCreateUserLicense: boolean;
	isLoginButtonEnabled: boolean;
}>;

const initialReducerState = {
	isSignUpEnabled: false,
	isFetchingConfig: false,
	isLoadingProject: false,
	isLoginButtonEnabled: true,
	hasCreateUserLicense: false,
};

function reducer(state: ReducerPayload, payload: ReducerPayload) {
	return {
		...state,
		...payload,
	};
}

function LoginPage() {
	const navigate = useNavigate();
	const [state, dispatchState] = useReducer(reducer, initialReducerState);

	useEffect(function () {
		getSignUpConfig();
		licensesService.setLicenses();
		const hasCreateUserLicense = licensesService.hasLicense('CREATE_USER');
		dispatchState({ hasCreateUserLicense });
	}, []);

	const form = useForm<z.infer<typeof formSchema>>({
		resolver: zodResolver(formSchema),
		defaultValues: {
			email: '',
			password: '',
		},
		mode: 'onTouched',
	});

	async function login(values: z.infer<typeof formSchema>) {
		dispatchState({ isLoginButtonEnabled: false });

		try {
			await loginService.login(values);
			dispatchState({ isLoadingProject: true });
			await getOrganisations();
			dispatchState({ isLoginButtonEnabled: true, isLoadingProject: false });

			navigate({
				to: '/',
				from: '/login',
			});
		} catch (err) {
			// TODO notify user using the UI
			console.error(login.name, err);
		}
	}

	async function getSignUpConfig() {
		dispatchState({ isFetchingConfig: true });
		try {
			const { data } = await signUpService.getSignUpConfig();
			dispatchState({ isSignUpEnabled: data });
		} catch (err) {
			// TODO notify user using the UI
			console.error(getSignUpConfig.name, err);
		} finally {
			dispatchState({ isFetchingConfig: false });
		}
	}

	async function getOrganisations() {
		try {
			await privateService.getOrganisations({ refresh: true });
		} catch (err) {
			console.error(getOrganisations.name, err);
		}
	}

	return (
		<>
			<div className="flex w-full">
				<aside className="bg-primary-100 bg-[url('/assets/img/public-layout.png')] bg-no-repeat bg-right-top min-w-[374px] desktop:w-0 h-screen transition-all duration-300 px-[36px] pt-[70px]"></aside>
				<div className="bg-[url('/assets/svg/pattern.svg')] bg-center bg-cover min-h-screen w-full">
					<div className="min-h-screen flex flex-col items-center justify-center w-full">
						<img
							src="/assets/svg/logo.svg"
							alt="convoy logo"
							className="mb-7 w-[130px]"
						/>

						<section className="max-w-[445px] mx-auto my-0 p-6 w-full bg-white-100 shadow-default rounded-[8px]">
							<Form {...form}>
								<form
									onSubmit={(...args) => void form.handleSubmit(login)(...args)}
								>
									<EmailInputField form={form} />
									<PasswordInputField form={form} />
									<ForgotPasswordSection />
									<LoginButton isButtonEnabled={state.isLoginButtonEnabled} />
									<LoginWithSAMLButton />
								</form>
							</Form>

							{state.isSignUpEnabled && state.hasCreateUserLicense && (
								<SignUpButton />
							)}
						</section>
					</div>
				</div>
			</div>

			<ConvoyLoader
				isTransparent={false}
				isVisible={state.isLoadingProject || state.isFetchingConfig}
			/>
		</>
	);
}

export const Route = createFileRoute('/login')({
	component: LoginPage,
});

// TODO loginService and other impure extraneous deps should be injected as a
// dependency for testing and flexibility/maintainability

// web/ui/dashboard/src/app/public/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ButtonComponent } from 'src/app/components/button/button.component';
import { InputDirective, InputErrorComponent, InputFieldDirective, LabelComponent, PasswordInputFieldComponent } from 'src/app/components/input/input.component';
import { LoginService } from './login.service';
import { LoaderModule } from 'src/app/private/components/loader/loader.module';
import { PrivateService } from 'src/app/private/private.service';
import { ORGANIZATION_DATA } from 'src/app/models/organisation.model';
import { SignupService } from '../signup/signup.service';
import { LicensesService } from 'src/app/services/licenses/licenses.service';

@Component({
	selector: 'app-login',
	standalone: true,
	imports: [CommonModule, ReactiveFormsModule, ButtonComponent, InputFieldDirective, InputDirective, LabelComponent, InputErrorComponent, PasswordInputFieldComponent, LoaderModule],
	templateUrl: './login.component.html',
	styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
	showLoginPassword = false;
	disableLoginBtn = false;
	loginForm: FormGroup = this.formBuilder.group({
		username: ['', Validators.required],
		password: ['', Validators.required]
	});
	isLoadingProject = false;
	isFetchingConfig = false;
	isSignupEnabled = false;
	organisations?: ORGANIZATION_DATA[];

	constructor(private formBuilder: FormBuilder, public router: Router, private loginService: LoginService, private signupService: SignupService, private privateService: PrivateService, public licenseService: LicensesService) {}

	ngOnInit() {
		this.getSignUpConfig();
		this.licenseService.setLicenses();
	}

	async getSignUpConfig() {
		this.isFetchingConfig = true;
		try {
			const response = await this.signupService.getSignupConfig();
			this.isSignupEnabled = response.data;
			this.isFetchingConfig = false;
		} catch (error) {
			this.isFetchingConfig = false;
		}
	}

	async login() {
		if (this.loginForm.invalid) return this.loginForm.markAllAsTouched();

		this.disableLoginBtn = true;
		try {
			const response: any = await this.loginService.login(this.loginForm.value);
			localStorage.setItem('CONVOY_AUTH', JSON.stringify(response.data));
			localStorage.setItem('CONVOY_AUTH_TOKENS', JSON.stringify(response.data.token));

			this.isLoadingProject = true;
			await this.getOrganisations();
			return this.router.navigateByUrl('/');
		} catch {
			return (this.disableLoginBtn = false);
		}
	}

	async getOrganisations() {
		try {
			await this.privateService.getOrganizations({ refresh: true });
			return;
		} catch (error) {
			return error;
		}
	}
}

<div class="min-h-screen flex flex-col items-center justify-center w-full">
	<img src="/assets/img/logo.svg" alt="convoy logo" class="mb-28px w-130px" />
	<section class="max-w-[445px] mx-auto my-0 p-24px w-full bg-white-100 shadow-default rounded-8px">
		<form [formGroup]="loginForm" (ngSubmit)="login()">
			<div convoy-input-field>
				<label for="username" convoy-label>Username</label>
				<input type="text" id="username" convoy-input autocomplete="username" formControlName="username" placeholder="super@default.com" />
				<convoy-input-error *ngIf="loginForm.controls.username.touched && loginForm.controls.username.invalid">Please enter your username</convoy-input-error>
			</div>

			<div convoy-input-field>
				<label convoy-label for="password">Password</label>
				<convoy-password-field>
					<input [type]="showLoginPassword ? 'text' : 'password'" convoy-input autocomplete="username" formControlName="password" placeholder="super@default.com" id="password" />
					<button class="bg-transparent w-18px h-18px absolute top-[55%] right-16px border-none translate-x-0 translate-y-[-50%]" type="button" (click)="showLoginPassword = !showLoginPassword">
						<img class="w-full" [src]="!showLoginPassword ? '/assets/img/password-invisible-icon.svg' : '/assets/img/password-visible-icon.svg'" alt="showLoginPassword ? 'hide password icon' : 'view password icon'" />
					</button>
				</convoy-password-field>
				<convoy-input-error *ngIf="loginForm.controls.password.touched && loginForm.controls.password.invalid">Please enter your password</convoy-input-error>
			</div>

			<div class="flex items-center text-12 mb-20px -mt-18px">
				Forgot password?
				<button convoy-button fill="link" type="button" class="px-0 ml-6px" (click)="router.navigateByUrl('/forgot-password')" size="sm">Reset it here</button>
			</div>

			<button convoy-button [disabled]="disableLoginBtn" size="lg" class="mb-12px">
				<span class="text-14 text-white-100" *ngIf="!disableLoginBtn">Login</span>
				<img *ngIf="disableLoginBtn" src="assets/img/button-loader.gif" alt="loader" class="h-18px" />
			</button>

			<button *ngIf="isSSOEnabled" convoy-button size="sm" type="button" fill="text" class="w-full" (click)="loginWithSSO()">Login with SSO</button>

			<button *ngIf="isGoogleOAuthEnabled" convoy-button size="sm" type="button" fill="text" class="w-full mt-12px" (click)="loginWithGoogle()" [disabled]="isGoogleSigningIn">
				<img *ngIf="!isGoogleSigningIn" src="/assets/img/svg/google.svg" alt="Google icon" class="w-16px h-16px inline mr-8px" />
				<div *ngIf="isGoogleSigningIn" class="loading-dots inline mr-8px">
					<span></span>
					<span></span>
					<span></span>
				</div>
				<span *ngIf="!isGoogleSigningIn">Sign in with Google</span>
				<span *ngIf="isGoogleSigningIn">Signing in...</span>
			</button>
		</form>

		<button *ngIf="isSignupEnabled && licenseService.hasLicense('user_limit')" convoy-button fill="link" class="mt-12px w-full" (click)="router.navigateByUrl('/signup')" size="sm">Signup</button>
	</section>
</div>

<convoy-loader [isTransparent]="false" *ngIf="isLoadingProject || isFetchingConfig"></convoy-loader>
