// web/ui/dashboard-react/src/app/projects_/$projectId/events/index.tsx
import { useState, useEffect } from 'react';
import { formatInTimeZone } from 'date-fns-tz';
import { subDays, setHours, setMinutes, format } from 'date-fns';
import { createFileRoute, useNavigate } from '@tanstack/react-router';

import { Copy, Clock7, CalendarIcon } from 'lucide-react';

import {
	Popover,
	PopoverTrigger,
	PopoverContent,
	PopoverClose,
} from '@/components/ui/popover';
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select';
import {
	type ChartConfig,
	ChartContainer,
	ChartTooltip,
	ChartTooltipContent,
} from '@/components/ui/chart';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { DashboardLayout } from '@/components/dashboard';
import { Bar, BarChart, CartesianGrid, XAxis } from 'recharts';

import { cn } from '@/lib/utils';
import { useProjectStore } from '@/store';
import { ensureCanAccessPrivatePages } from '@/lib/auth';
import * as sourcesService from '@/services/sources.service';
import * as projectsService from '@/services/projects.service';
import * as eventsService from '@/services/events.service';

import type { DateRange } from 'react-day-picker';

import appsIcon from '../../../../../assets/svg/apps-icon.svg';
import messageIcon from '../../../../../assets/svg/message-icon.svg';
import emptyStateImg from '../../../../../assets/svg/events-empty-state-image.svg';

const chartData = [
	{ month: 'January', desktop: 186 },
	{ month: 'February', desktop: 0 },
	{ month: 'March', desktop: 237 },
	{ month: 'April', desktop: 73 },
	{ month: 'May', desktop: 209 },
	{ month: 'June', desktop: 214 },
	{ month: 'January', desktop: 0 },
	{ month: 'February', desktop: 305 },
	{ month: 'March', desktop: 237 },
	{ month: 'April', desktop: 0 },
	{ month: 'May', desktop: 209 },
	{ month: 'June', desktop: 214 },
];

const chartConfig = {
	desktop: {
		label: 'Desktop',
		color: '#477db3b3',
	},
} satisfies ChartConfig;

export const Route = createFileRoute('/projects_/$projectId/events/')({
	beforeLoad({ context }) {
		ensureCanAccessPrivatePages(context.auth?.getTokens().isLoggedIn);
	},
	async loader() {
		const stats = await projectsService.getStats();
		const sources = await sourcesService.getSources();
		const latestDeliveries = await eventsService.getEventDeliveries();

		return {
			stats,
			latestSource: sources.content[sources.content.length - 1],
			latestDeliveries,
		};
	},
	component: EventsDeliveriesPage,
});

function EventsDeliveriesPage() {
	const { project } = useProjectStore();
	const navigate = useNavigate();
	const { stats, latestSource, latestDeliveries } = Route.useLoaderData();
	const [date, setDate] = useState<DateRange | undefined>({
		from: subDays(new Date(), 30),
		to: new Date(),
	});
	const [endTimeValue, setEndTimeValue] = useState('23:59');
	const [startTimeValue, setStartTimeValue] = useState('00:00');
	const [dashboardFrequency, setDashboardFrequency] = useState('daily');
	const [dashboardSummary, setDashboardSummary] = useState(null)

	// useEffect(() => {
	// 	let startDate = date?.from ? new Date(search.startDate).toISOString().split('.')[0]
	// 	: undefined
	// 	eventsService.getDashboardSummary(

	// 	)
	
	// 	return () => {
			
	// 	}
	// }, [date])
	

	function setTimeOnDate(time: string, date: Date) {
		const [hours, minutes] = time.split(':').map(str => parseInt(str, 10));
		return setHours(setMinutes(new Date(date), minutes), hours);
	}

	function setTagColour(status: string) {
		switch (status) {
			case 'Success':
				return 'bg-new.success-25 text-new.success-600 hover:bg-new.success-25 hover:new.success-600';
			case 'Failure':
			case 'Failed':
				return 'bg-destructive/10 text-destructive hover:bg-destructive/10 hover:text-destructive';
			// Pending
			default:
				return 'bg-neutral-3 text-neutral-10 hover:bg-neutral-3 hover:text-neutral-10';
		}
	}

	return (
		<DashboardLayout showSidebar={true}>
			{/* Has no events */}
			{!stats.events_exist && (
				<div className="m-auto">
					<div className="flex flex-col items-center justify-center gap-y-6">
						<img
							src={emptyStateImg}
							alt="No subscriptions created"
							className="h-40"
						/>

						<h2 className="font-bold mb-4 text-base text-neutral-sm text-center">
							{project?.type == 'incoming'
								? 'You have no incoming events.'
								: 'You have no outgoing events yet'}
						</h2>

						{stats.subscriptions_exist ? (
							<p className="text-neutral-11 text-xs max-w-[410px] text-center">
								{project?.type == 'incoming'
									? `Start receiving webhooks by adding your webhook URL into your webhook sender platform "${latestSource?.name}"`
									: `You have not sent any webhook events yet. Learn how to do that in our docs`}
							</p>
						) : (
							<p className="text-neutral-11 text-xs max-w-[410px] text-center">
								{project?.type == 'incoming'
									? 'You need to create an endpoint subscribe it to an event source (sender of your webhooks) to start receiving events'
									: 'You need to create an endpoint and subscribe it to listen to events'}
							</p>
						)}

						{stats.subscriptions_exist && project?.type == 'incoming' && (
							<div className="w-full flex flex-col gap-y-6">
								<div className="flex items-center justify-between rounded-8px py-2 border px-4 border-neutral-a3 bg-new.primary-25/50 gap-x-6 w-full">
									<p className="text-xs text-neutral-10 ml-10">
										{latestSource.url}
									</p>
									<Button
										size={'icon'}
										variant={'ghost'}
										className="hover:bg-transparent"
										onClick={() =>
											navigator.clipboard.writeText(latestSource.url || '')
										}
									>
										<Copy className="stroke-neutral-10" />
									</Button>
								</div>

								{latestDeliveries.content.length == 0 && (
									<div className="flex flex-col gap-y-6 w-full items-center">
										<div className="flex items-center justify-center rounded-8px py-4 border px-4 border-neutral-a3 gap-x-4 w-4/5">
											<Clock7 className="w-4 h-4  rounded-[100%] bg-new.primary-25 stroke-new.primary-400" />
											<p className="text-xs text-neutral-10">
												Waiting on your first webhook event
											</p>
										</div>

										<Button
											variant="link"
											className="text-new.primary-400 text-base hover:no-underline"
											asChild
										>
											<a
												href="https://docs.getconvoy.io/guides/receiving-webhook-example"
												target="_blank"
												rel="noreferrer"
												className="text-new.primary-400 text-base"
											>
												Don&apos;t See Your Events Yet?
											</a>
										</Button>
									</div>
								)}

								{latestDeliveries.content.length > 0 && (
									<div className="w-full max-w-[500px]">
										<div className="flex w-full border-b border-b-neutral-a3 text-neutral-11 text-sm p-[10px]">
											<div className="w-1/5 text-left">Status</div>
											<div className="w-1/3 text-left ml-2px">Subscription</div>
											<div className="w-1/5 text-left ml-2px">Event Time</div>
											<div className="w-1/5 text-left ml-2px">Retry Time</div>
										</div>
										{latestDeliveries.content.map(event => (
											<div
												key={event.uid}
												onClick={() => {
													navigate({
														to: '/projects/$projectId/events/event-deliveries/$eventId',
														params: {
															projectId: project.uid,
															eventId: event.uid,
														},
													});
												}}
												className="hover:bg-neutral-a3 cursor-pointer"
											>
												<div className="flex text-left text-sm p-[10px]">
													<div className="w-1/5">
														<Badge
															className={`shadow-none font-normal text-xs border-0 !rounded-22px py-1.5 px-3 ${setTagColour(event.status)}`}
														>
															{event.status}
														</Badge>
													</div>
													<div className="w-1/3">
														{project.type == 'incoming' && (
															<div>
																<span className="max-w-[146px] overflow-hidden overflow-ellipsis">
																	{event?.source_metadata?.name || 'Rest API'}
																</span>
																<span className="px-20px font-light">→</span>
															</div>
														)}

														<span
															className={`${project.type == 'incoming' ? 'max-w-[140px] overflow-hidden overflow-ellipsis' : 'w-[156px] overflow-hidden overflow-ellipsis'}`}
														>
															{event.endpoint_metadata.title ||
																event.endpoint_metadata.name}
														</span>
													</div>
													<div className="w-1/5 ml-2px">
														{Intl.DateTimeFormat('en-GB', {
															timeStyle: 'medium',
															hour12: true,
														}).format(new Date(event.created_at))}
													</div>
													<div className="w-1/5 ml-2px">
														{Intl.DateTimeFormat('en-GB', {
															timeStyle: 'medium',
															hour12: true,
														}).format(new Date(event.updated_at))}
													</div>
												</div>

												<Button
													variant={'ghost'}
													onClick={e => {
														e.stopPropagation();
														console.log('continue to dashboard');
													}}
												>
													Continue to Dashboard
												</Button>
											</div>
										))}
									</div>
								)}
							</div>
						)}

						{!stats.subscriptions_exist && (
							<Button
								variant={'ghost'}
								className="text-xs bg-new.primary-400 text-white-100 hover:bg-new.primary-400 hover:text-white-100"
							>
								Complete Project Setup{' '}
								<svg width="24" height="24" className="ml-8px fill-white-100">
									<use xlinkHref="#arrow-right-icon"></use>
								</svg>
							</Button>
						)}

						{stats.subscriptions_exist && project?.type == 'outgoing' && (
							<Button asChild>
								<a
									href="https://docs.getconvoy.io/guides/sending-webhook-example"
									target="_blank"
									rel="noreferrer"
									referrerPolicy="no-referrer"
									className="mt-48px"
								>
									Go to documentation
									<svg className="ml-8px fill-primary-100 w-20px h-20px">
										<use xlinkHref="#external-link-icon"></use>
									</svg>
								</a>
							</Button>
						)}
					</div>
				</div>
			)}

			{/* Has events */}
			{stats.events_exist && (
				<div className="p-6">
					<div className="flex flex-col justify-center gap-y-6">
						<h2 className="text-12 font-medium text-neutral-10 mb-16px">
							Events Summary
						</h2>
						<div className="flex items-center gap-x-4">
							{/* Date range selector */}
							<div className="flex flex-col gap-y-2">
								<label className="text-neutral-9 text-xs" htmlFor="date">
									Select a date range
								</label>
								<div className="grid gap-2">
									<Popover>
										<PopoverTrigger asChild className="shadow-none">
											<Button
												id="date"
												variant={'outline'}
												className={cn(
													'w-[320px] justify-start text-left font-normal text-xs text-neutral-9',
												)}
											>
												<CalendarIcon className="stroke-neutral-9" />
												{date?.from ? (
													date.to ? (
														<>
															{formatInTimeZone(
																date.from,
																'UTC',
																'dd/LL/y, h:mm aa',
															)}{' '}
															-{' '}
															{formatInTimeZone(
																date.to,
																'UTC',
																'dd/LL/y, h:mm aa',
															)}
														</>
													) : (
														format(date.from, 'dd/LL/y, h:mm aa')
													)
												) : (
													<span className="text-neutral-9">
														Pick a date range
													</span>
												)}
											</Button>
										</PopoverTrigger>
										<PopoverContent className="w-auto p-0" align="start">
											<Calendar
												initialFocus
												mode="range"
												defaultMonth={date?.from}
												selected={date}
												onSelect={setDate}
												numberOfMonths={2}
											/>
											<form
												className="px-4 flex gap-x-6 items-center"
												style={{ marginBlockEnd: '1em' }}
											>
												<div className="">
													<label className="text-sm">
														Start time:{' '}
														<input
															type="time"
															value={startTimeValue}
															onChange={e => {
																const time = e.target.value;
																setStartTimeValue(time);
															}}
														/>
													</label>
												</div>
												<div>
													<label className="text-sm">
														End time:{' '}
														<input
															type="time"
															value={endTimeValue}
															onChange={e => {
																const time = e.target.value;
																setEndTimeValue(time);
															}}
														/>
													</label>
												</div>
											</form>
											<div className="px-4 pb-2 flex justify-between gap-x-4 items-center">
												<span className="text-xs text-neutral-9 ">
													Time would be converted to UTC after selection
												</span>
												<div className="flex items-center gap-x-2">
													<PopoverClose asChild>
														<Button
															variant={'ghost'}
															size={'sm'}
															className="border border-destructive bg-transparent hover:bg-transparent hover:text-destructive text-destructive text-xs"
															onClick={() => setDate(undefined)}
														>
															Clear
														</Button>
													</PopoverClose>
													<PopoverClose asChild>
														<Button
															variant={'ghost'}
															size={'sm'}
															className="bg-new.primary-400 text-white-100 hover:text-white-100 hover:bg-new.primary-400 text-xs"
															onClick={() => {
																if (!date?.from || !date?.to) return;

																const from = setTimeOnDate(
																	startTimeValue,
																	date.from,
																);
																const to = setTimeOnDate(endTimeValue, date.to);
																setDate({ from, to });
															}}
														>
															Apply
														</Button>
													</PopoverClose>
												</div>
											</div>
										</PopoverContent>
									</Popover>
								</div>
							</div>
							{/* Dashboard Frequency */}
							<div className="flex flex-col gap-y-2">
								<label
									htmlFor="select_filter_period"
									className="text-neutral-9 text-xs"
								>
									Filter by
								</label>
								<Select
									defaultValue={dashboardFrequency}
									onValueChange={setDashboardFrequency}
								>
									<SelectTrigger
										className="w-[100px] h-9 shadow-none focus:ring-0 text-xs text-neutral-9"
										id="select_filter_period"
									>
										<SelectValue
											className="text-xs text-neutral-9"
											placeholder="Sort"
										/>
									</SelectTrigger>
									<SelectContent>
										{['daily', 'weekly', 'monthly', 'yearly'].map(v => (
											<SelectItem
												className="text-xs hover:cursor-pointer"
												value={v}
												key={v}
											>
												<span className="text-neutral-9 capitalize">{v}</span>
											</SelectItem>
										))}
									</SelectContent>
								</Select>
							</div>
						</div>
						<div className="border rounded-8px">
							<div className="flex justify-start items-center">
								<div className="flex items-center gap-x-8 pl-4 py-4 border-r p-1">
									<img src={messageIcon} alt="events sent" />
									<div className="flex flex-col justify-center">
										<p>10</p>
										<p className="font-normal text-sm">Events sent</p>
									</div>
									<img
										src={messageIcon}
										alt="events sent"
										className="opacity-50"
									/>
								</div>
								<div className="flex items-center gap-x-8 pl-4 py-4 border-r p-1">
									<img src={appsIcon} alt="events sent" />
									<div className="flex flex-col justify-center">
										<p>8</p>
										<p className="font-normal text-sm">Endpoints</p>
									</div>
									<img src={appsIcon} alt="endpoints" className="opacity-50" />
								</div>
							</div>
							<div className="border-t px-4">
								<ChartContainer
									config={chartConfig}
									className="h-[150px] w-full"
								>
									<BarChart accessibilityLayer data={chartData}>
										<CartesianGrid vertical={false} />
										<XAxis
											dataKey="month"
											tickLine={false}
											tickMargin={10}
											axisLine={true}
											// tickFormatter={value => value.slice(0, 3)}
										/>
										<ChartTooltip
											cursor={false}
											content={<ChartTooltipContent hideLabel />}
										/>
										<Bar
											dataKey="desktop"
											fill="var(--color-desktop)"
											radius={[4, 4, 0, 0]}
										/>
									</BarChart>
								</ChartContainer>
							</div>
						</div>
					</div>
				</div>
			)}
		</DashboardLayout>

		// <DashboardLayout showSidebar={true}>
		// 	<div className="p-6">
		// 		<section className="space-y-6">
		// 			<h1 className="text-lg font-bold text-neutral-12">
		// 				Event Deliveries
		// 			</h1>
		// 		</section>
		// 	</div>
		// </DashboardLayout>
	);
}

// web/ui/dashboard/src/app/private/pages/project/events/events.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { format } from 'date-fns';
import { HTTP_RESPONSE } from 'src/app/models/global.model';
import { EventsService } from './events.service';
import { EVENT_DELIVERY } from 'src/app/models/event.model';
import { CHARTDATA, PAGINATION } from 'src/app/models/global.model';
import { PrivateService } from 'src/app/private/private.service';
import { Router } from '@angular/router';
import { SOURCE } from 'src/app/models/source.model';

@Component({
	selector: 'app-events',
	templateUrl: './events.component.html',
	styleUrls: ['./events.component.scss']
})
export class EventsComponent implements OnInit {
	dateOptions = ['Last Year', 'Last Month', 'Last Week', 'Yesterday'];
	isloadingDashboardData: boolean = false;
	showFilterDropdown: boolean = false;
	selectedDateOption: string = '';
	dashboardFrequency: 'daily' | 'weekly' | 'monthly' | 'yearly' = 'daily';
	filterOptions: ['daily', 'weekly', 'monthly', 'yearly'] = ['daily', 'weekly', 'monthly', 'yearly'];
	dashboardData = { apps: 0, events_sent: 0 };
	eventDeliveries!: { pagination: PAGINATION; content: EVENT_DELIVERY[] };
	statsDateRange: FormGroup = this.formBuilder.group({
		startDate: [{ value: new Date(new Date().setDate(new Date().getDate() - 30)), disabled: true }],
		endDate: [{ value: new Date(), disabled: true }]
	});
	dateRangeValue?: {
		startDate: string | Date;
		endDate: string | Date;
	};
	hasEvents: boolean = false;
	chartData!: CHARTDATA[];
	showAddEventModal = false;
	lastestSource?: SOURCE;
	lastestEventDeliveries: EVENT_DELIVERY[] = [];
	eventDelTableHead: string[] = ['Status', 'Event Type', 'Event Time', 'Next Attempt'];
	eventDelievryIntervalTime: any;
	labelsDateFormat!: string;
	isProjectConfigurationComplete = false;
	isPageLoading = false;
	reloadSubscription: any;

	constructor(private formBuilder: FormBuilder, private eventsService: EventsService, public privateService: PrivateService, public router: Router) {}

	async ngOnInit() {
		this.isloadingDashboardData = true;
		this.isPageLoading = true;
		await this.getProjectStats();

		if (this.isProjectConfigurationComplete) {
			await this.checkEventsOnFirstLoad();

			if (this.privateService.getProjectDetails?.type === 'incoming' && !this.hasEvents) {
				this.eventDelievryIntervalTime = setInterval(() => {
					this.getLatestEvent();
				}, 2000);
			}

			this.isPageLoading = false;
			this.isloadingDashboardData = false;
		} else {
			this.isloadingDashboardData = false;
			this.isPageLoading = false;
		}
	}

	async getLatestSource() {
		try {
			const sources = await this.privateService.getSources();
			this.lastestSource = sources.data.content[sources.data.content.length - 1];
			return;
		} catch (error) {
			return error;
		}
	}

	async getLatestEvent() {
		try {
			const eventDeliveries = await this.eventsService.getEventDeliveries();
			this.lastestEventDeliveries = eventDeliveries.data.content;
			return;
		} catch (error) {
			this.isloadingDashboardData = false;
			this.isPageLoading = false;
			return error;
		}
	}

	async checkEventsOnFirstLoad() {
		if (this.hasEvents) {
			clearInterval(this.eventDelievryIntervalTime);
			this.isPageLoading = false;

			await this.fetchDashboardData();
			return;
		}

		if (this.privateService.getProjectDetails?.type === 'incoming' && this.isProjectConfigurationComplete) await this.getLatestSource();
	}

	setDateForFilter(requestDetails: { startDate: Date; endDate: Date; startTime?: string; endTime?: string }) {
		if (!requestDetails.endDate && !requestDetails.startDate) return { startDate: '', endDate: '' };
		const startDate = requestDetails.startDate ? `${format(requestDetails.startDate, 'yyyy-MM-dd')}${requestDetails?.startTime || 'T00:00:00'}` : '';
		const endDate = requestDetails.endDate ? `${format(requestDetails.endDate, 'yyyy-MM-dd')}${requestDetails?.endTime || 'T23:59:59'}` : '';
		return { startDate, endDate };
	}

	continueToDashboard() {
		this.fetchDashboardData();
		this.privateService.getProjectStat({ refresh: true });
		this.hasEvents = true;
		clearInterval(this.eventDelievryIntervalTime);
	}

	async fetchDashboardData() {
        const setDate = typeof this.statsDateRange.value.startDate !== 'string';

		const { startDate, endDate } = setDate ? this.setDateForFilter(this.statsDateRange.value) : this.statsDateRange.value;

        try {
			const dashboardResponse = await this.eventsService.dashboardSummary({ startDate, endDate, type: this.dashboardFrequency });
			this.dashboardData = dashboardResponse.data;
			this.initConvoyChart(dashboardResponse);

			this.isloadingDashboardData = false;
			return;
		} catch (error: any) {
			this.isloadingDashboardData = false;
			this.isPageLoading = false;
			return;
		}
	}

	getSelectedDateRange(dateRange?: { startDate: Date; endDate: Date }) {
		this.dateRangeValue = dateRange;
		this.statsDateRange.patchValue({
			startDate: dateRange?.startDate || new Date(new Date().setDate(new Date().getDate() - 30)),
			endDate: dateRange?.endDate || new Date()
		});
		this.fetchDashboardData();
	}

	initConvoyChart(dashboardResponse: HTTP_RESPONSE) {
		let chartData: { label: string; data: any }[] = [];

		const eventData = dashboardResponse.data.event_data.reverse();
		const labelFormat = this.getDateLabelFormat();
		eventData.forEach((data: any) => {
			chartData.push({
				label: format(new Date(data.data.date), labelFormat),
				data: data.count || 0
			});
		});

		this.chartData = chartData;
	}

	getDateLabelFormat() {
		let labelsDateFormat = '';
		switch (this.dashboardFrequency) {
			case 'daily':
				labelsDateFormat = 'do, MMM, yyyy';
				break;
			case 'weekly':
				labelsDateFormat = 'yyyy-MM';
				break;
			case 'monthly':
				labelsDateFormat = 'MMM, yyyy';
				break;
			case 'yearly':
				labelsDateFormat = 'yyyy';
				break;
			default:
				break;
		}

		return labelsDateFormat;
	}

	async getProjectStats() {
		try {
			const projectStats = await this.privateService.getProjectStat();
			this.isProjectConfigurationComplete = projectStats.data?.total_subscriptions;
			this.hasEvents = projectStats.data?.messages_sent;
			return;
		} catch (error) {
			return error;
		}
	}
}

<div class="h-[705px]" *ngIf="isPageLoading">
	<convoy-loader [isTransparent]="true"></convoy-loader>
</div>

<ng-container *ngIf="!isPageLoading">
	<ng-container *ngIf="!hasEvents">
		<div class="flex items-center justify-center flex-col py-82px h-full text-center px-40px">
			<img src="/assets/img/events-empty-state-image.svg" alt="events empty state image" class="mb-48px" />
			<h3 class="mb-10px text-14 font-bold">{{ privateService.getProjectDetails?.type === 'incoming' ? 'You have no incoming events.' : 'You have no outgoing events yet' }}</h3>
			<p class="text-12 text-neutral-11 max-w-[428px]" *ngIf="isProjectConfigurationComplete">
				{{ privateService.getProjectDetails?.type === 'incoming' ? 'Start receiving webhooks by adding your webhook URL into your webhook sender platform "' + lastestSource?.name + '"' : 'You have not sent any webhook events yet. Learn how to do that in our docs' }}
			</p>
			<p class="text-12 text-neutral-11 max-w-[428px]" *ngIf="!isProjectConfigurationComplete">
				{{ privateService.getProjectDetails?.type === 'incoming' ? 'You need to create an endpoint subscribe it to an event source (sender of your webhooks) to start receiving events' : 'You need to create an endpoint and subscribe it to listen to events' }}
			</p>

			<ng-container *ngIf="privateService.getProjectDetails?.type === 'incoming' && isProjectConfigurationComplete">
				<div class="flex items-center justify-between w-full h-50px border border-neutral-a3 bg-[#F7F9FC] rounded-[6px] px-16px mb-32px max-w-[400px] mt-42px">
					<span class="text-12 text-neutral-11 font-normal whitespace-nowrap w-[440px] overflow-hidden text-ellipsis">{{ lastestSource?.url }}</span>
					<convoy-copy-button [text]="lastestSource?.url || ''" notificationText="Source URL copied to clipboard"></convoy-copy-button>
				</div>

				<ng-container *ngIf="lastestEventDeliveries.length === 0">
					<div convoy-card class="flex py-10px px-20px items-center">
						<img src="/assets/img/time-icon.svg" alt="timer icon" class="mr-20px w-30px" />
						<p class="mr-12px text-12 text-neutral-12">Waiting on your first web-hook event</p>
					</div>
					<a href="https://docs.getconvoy.io/guides/receiving-webhook-example" target="_blank" referrerpolicy="no-referrer" convoy-button fill="text" class="mt-48px font-medium">Don't See Your Events Yet?</a>
				</ng-container>

				<ng-container *ngIf="lastestEventDeliveries.length > 0">
					<div class="w-full max-w-[500px]" convoy-card>
						<div class="flex w-full border-b border-b-neutral-a3 text-neutral-11 text-14 p-10px">
							<div class="w-1/5 text-left">Status</div>
							<div class="w-1/3 text-left ml-2px">Subscription</div>
							<div class="w-1/5 text-left ml-2px">Event Time</div>
							<div class="w-1/5 text-left ml-2px">Retry Time</div>
						</div>
						<div class="flex text-left text-14 p-10px cursor-pointer hover:bg-neutral-a3" *ngFor="let event of lastestEventDeliveries" [routerLink]="['./event-deliveries/' + event.uid]">
							<div class="w-1/5">
								<div convoy-tag [color]="event.status | statuscolor">{{ event?.status }}</div>
							</div>
							<div class="w-1/3">
								<ng-container *ngIf="privateService.getProjectDetails?.type === 'incoming'">
									<span class="max-w-[146px] overflow-hidden overflow-ellipsis">
										{{ event?.source_metadata?.name || 'Rest API' }}
									</span>

									<span class="px-20px font-light">→</span>
								</ng-container>

								<span [class]="privateService.getProjectDetails?.type === 'incoming' ? 'max-w-[140px] overflow-hidden overflow-ellipsis' : 'w-156px' + ' overflow-hidden overflow-ellipsis'">
									{{ event.endpoint_metadata.title || event.endpoint_metadata.name }}
								</span>
							</div>
							<!-- <div class="w-1/3 ml-2px max-w-[159px] whitespace-nowrap overflow-hidden text-ellipsis">{{ event?.endpoint_metadata?.name || event?.endpoint_metadata?.title }}</div> -->
							<div class="w-1/5 ml-2px">{{ event.created_at | date : 'mediumTime' }}</div>
							<div class="w-1/5 ml-2px">{{ event.updated_at | date : 'mediumTime' }}</div>
						</div>
					</div>

					<button (click)="continueToDashboard()" convoy-button class="mt-48px font-medium">Continue to Dashboard</button>
				</ng-container>
			</ng-container>

			<button convoy-button size="sm" *ngIf="!isProjectConfigurationComplete" class="!py-12px mt-48px" convoy-permission="Project Setup|MANAGE" (click)="router.navigateByUrl('/projects/' + privateService.getProjectDetails?.uid + '/setup')">
				Complete project setup
				<svg width="24" height="24" class="ml-8px fill-white-100">
					<use xlink:href="#arrow-right-icon"></use>
				</svg>
			</button>

			<a href="https://docs.getconvoy.io/guides/sending-webhook-example" convoy-button target="_blank" referrerpolicy="no-referrer" fill="outline" class="mt-48px" *ngIf="privateService.getProjectDetails?.type === 'outgoing' && isProjectConfigurationComplete">
				Go to documentation
				<svg class="ml-8px fill-primary-100 w-20px h-20px">
					<use xlink:href="#external-link-icon"></use>
				</svg>
			</a>
		</div>
	</ng-container>

	<ng-container *ngIf="hasEvents">
		<h2 class="text-12 font-medium text-neutral-10 mb-16px">Events Summary</h2>

		<div class="pb-24px flex items-center">
			<convoy-date-picker (selectedDateRange)="getSelectedDateRange($event)" (clearDates)="getSelectedDateRange()">
				<button dropdownTrigger convoy-button fill="outline" size="sm" class="px-10px !border-primary-400 justify-between gap-10px" [ngClass]="{ 'text-primary-100 !bg-primary-500': !!dateRangeValue?.startDate && !!dateRangeValue?.endDate }">
					<svg width="18" height="18" class="transition-all fill-none scale-75" [class]="!!dateRangeValue?.startDate && !!dateRangeValue?.endDate ? 'stroke-new.primary-300' : 'stroke-neutral-11'">
						<use xlink:href="#calendar-icon"></use>
					</svg>
					<span class="text-neutral-11 mr-4px">Date</span>

					<button type="button" *ngIf="dateRangeValue?.startDate && dateRangeValue?.endDate" (click)="getSelectedDateRange()">
						<svg width="10" height="10" class="fill-primary-100">
							<use xlink:href="#close-icon"></use>
						</svg>
					</button>
				</button>
			</convoy-date-picker>

			<div convoy-dropdown size="sm" position="left">
				<button dropdownTrigger convoy-button size="sm" fill="outline" class="px-10px !border-primary-400 ml-16px">
					<span class="text-neutral-11 mr-4px">Filter By:</span>
					<span class="text-primary-100 capitalize">{{ dashboardFrequency }}</span>
					<img src="/assets/img/angle-arrow-down.svg" alt="arrow down icon" class="w-14px h-14px ml-10px" />
				</button>

				<ul dropdownOptions>
					<li convoy-dropdown-option convoy-list-item *ngFor="let filterOption of filterOptions" class="text-14 px-20px" [active]="dashboardFrequency == filterOption ? 'true' : 'false'" [hasBorder]="true">
						<button convoy-button color="neutral" fill="text" (click)="dashboardFrequency = filterOption; fetchDashboardData()" class="capitalize font-normal text-left w-full !justify-start text-12">
							{{ filterOption }}
						</button>
					</li>
				</ul>
			</div>
		</div>

		<div convoy-card class="relative mb-22px">
			<ul class="flex flex-wrap items-center min-h-[76px] metrics">
				<li class="bg-[url(/assets/img/message-icon-transparent.svg)] bg-[length:30px_30px] bg-no-repeat flex items-center px-30px py-16px border-r border-neutral-a3 [background-position-x:185px] [background-position-y:46px] min-w-[220px]">
					<img src="/assets/img/message-icon.svg" class="mr-30px" alt="message icon" />
					<div *ngIf="isloadingDashboardData">
						<convoy-skeleton-loader className="w-60px h-16px mb-10px"></convoy-skeleton-loader>
						<convoy-skeleton-loader className="w-120px h-16px"></convoy-skeleton-loader>
					</div>
					<div *ngIf="!isloadingDashboardData">
						<div class="text-16 font-medium">{{ dashboardData.events_sent | number }}</div>
						<div class="text-neutral-11 text-14">
							<span class="font-normal">Event</span>
							<span class="font-normal" *ngIf="dashboardData.events_sent > 1">s</span>
							{{ privateService.getProjectDetails?.type === 'incoming' ? 'Ingested' : 'Sent' }}
						</div>
					</div>
				</li>

				<li class="bg-[url(/assets/img/apps-icon-transparent.svg)] bg-[length:30px_30px] bg-no-repeat flex items-center px-30px py-16px border-r border-neutral-a3 [background-position-x:185px] [background-position-y:46px] min-w-[220px]">
					<img src="/assets/img/apps-icon.svg" class="mr-30px" alt="apps icon" />
					<div *ngIf="isloadingDashboardData">
						<convoy-skeleton-loader className="w-60px h-16px mb-10px"></convoy-skeleton-loader>
						<convoy-skeleton-loader className="w-100px h-16px"></convoy-skeleton-loader>
					</div>
					<div *ngIf="!isloadingDashboardData">
						<div class="text-16 font-medium">{{ dashboardData.apps | number }}</div>
						<div class="text-neutral-11 text-14">
							<span class="font-normal">Endpoint</span>
							<span class="font-normal" *ngIf="dashboardData.apps > 1">s</span>
						</div>
					</div>
				</li>
			</ul>

			<div class="border-t border-neutral-a3 p-16px">
				<convoy-chart [chartData]="chartData" [isLoading]="isloadingDashboardData"></convoy-chart>
			</div>
		</div>

		<app-event-deliveries (pushEventDeliveries)="eventDeliveries = $event"></app-event-deliveries>
	</ng-container>
</ng-container>
